using Disruptor.Surface.Generator.Emit;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace Disruptor.Surface.Tests.Generator;

public sealed class CodeWriterTests
{
    [Fact]
    public void Line_WritesIndentedLines()
    {
        var writer = new CodeWriter();

        writer.Line("first");
        writer.Line("second");

        Assert.Equal(Expected("first", "second"), writer.ToString());
    }

    [Fact]
    public void Indent_RestoresPreviousIndentation()
    {
        var writer = new CodeWriter();

        writer.Line("root");
        using (writer.Indent())
        {
            writer.Line("child");
            using (writer.Indent())
            {
                writer.Line("grandchild");
            }

            writer.Line("child2");
        }

        writer.Line("root2");

        Assert.Equal(Expected(
            "root",
            "    child",
            "        grandchild",
            "    child2",
            "root2"), writer.ToString());
    }

    [Fact]
    public void Block_WritesBalancedBracesAndRestoresIndentation()
    {
        var writer = new CodeWriter();

        using (writer.Block("if (enabled)"))
        {
            writer.Line("Run();");
        }

        writer.Line("Done();");

        Assert.Equal(Expected(
            "if (enabled)",
            "{",
            "    Run();",
            "}",
            "Done();"), writer.ToString());
    }

    [Fact]
    public void BracedBlock_WritesAnonymousBlock()
    {
        var writer = new CodeWriter();

        writer.Line("void M()");
        using (writer.BracedBlock())
        {
            using (writer.BracedBlock())
            {
                writer.Line("var x = 1;");
            }
        }

        Assert.Equal(Expected(
            "void M()",
            "{",
            "    {",
            "        var x = 1;",
            "    }",
            "}"), writer.ToString());
    }

    [Fact]
    public void Namespace_IsNoopForMissingNamespace_AndBlockForNamespace()
    {
        var noNamespace = new CodeWriter();
        using (noNamespace.Namespace(null))
        {
            noNamespace.Line("public sealed class C { }");
        }

        Assert.Equal(Expected("public sealed class C { }"), noNamespace.ToString());

        var withNamespace = new CodeWriter();
        using (withNamespace.Namespace("M"))
        {
            withNamespace.Line("public sealed class C { }");
        }

        Assert.Equal(Expected(
            "namespace M",
            "{",
            "    public sealed class C { }",
            "}"), withNamespace.ToString());
    }

    [Fact]
    public void Header_MatchesGeneratedFilePreamble()
    {
        var writer = new CodeWriter();

        writer.Header();

        Assert.Equal(Expected(
            "// <auto-generated />",
            "#nullable enable",
            ""), writer.ToString());
    }

    [Fact]
    public void ToSourceText_UsesUtf8Encoding()
    {
        var writer = new CodeWriter();

        writer.Line("first");

        var source = writer.ToSourceText();

        Assert.Equal(Expected("first"), source.ToString());
        Assert.Equal(System.Text.Encoding.UTF8, source.Encoding);
    }

    [Fact]
    public void Delimited_LetsCallerControlCommaShape()
    {
        var writer = new CodeWriter();

        writer.Line("new[]");
        using (writer.BracedBlock())
        {
            writer.Delimited(["alpha", "beta", "gamma"], (item, isLast) =>
                writer.Line($"\"{item}\"{(isLast ? string.Empty : ",")}"));
        }

        Assert.Equal(Expected(
            "new[]",
            "{",
            "    \"alpha\",",
            "    \"beta\",",
            "    \"gamma\"",
            "}"), writer.ToString());
    }

    [Fact]
    public void GeneratedSource_ParsesAsCSharp()
    {
        var writer = new CodeWriter();

        writer.Header();
        using (writer.Namespace("M"))
        {
            using (writer.Block("public static class Demo"))
            {
                using (writer.Block("public static int Add(int left, int right)"))
                {
                    writer.Line("return left + right;");
                }
            }
        }

        var tree = CSharpSyntaxTree.ParseText(writer.ToString(), new CSharpParseOptions(LanguageVersion.Preview));
        Assert.DoesNotContain(tree.GetDiagnostics(), d => d.Severity == DiagnosticSeverity.Error);
    }

    [Fact]
    public void NameAllocator_CreatesStableUniqueNames()
    {
        var allocator = new NameAllocator();

        Assert.Equal("__source", allocator.Create("source"));
        Assert.Equal("__source2", allocator.Create("source"));
        Assert.Equal("__target", allocator.Create("__target"));
    }

    [Fact]
    public void NameAllocator_RespectsReservations()
    {
        var allocator = new NameAllocator();

        allocator.Reserve("__source");

        Assert.Equal("__source2", allocator.Create("source"));
    }

    [Fact]
    public void NameAllocator_SanitizesInvalidHints()
    {
        var allocator = new NameAllocator();

        Assert.Equal("__source_id", allocator.Create("source-id"));
        Assert.Equal("__9_lives", allocator.Create("9 lives"));
        Assert.Equal("__value", allocator.Create("!!!"));
    }

    private static string Expected(params string[] lines)
    {
        var builder = new System.Text.StringBuilder();
        foreach (var line in lines)
        {
            builder.AppendLine(line);
        }

        return builder.ToString();
    }
}
