using System.Text;
using Surface.Generator.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Surface.Generator.Emit;

/// <summary>
/// Emits a partial declaration of the user's <c>[CompositionRoot]</c>-tagged class with
/// one instance <c>Load{Root}Async(ISurrealTransport, {Root}Id, CancellationToken)</c>
/// method per <c>[AggregateRoot]</c>. The user owns construction (transport wiring,
/// caches, telemetry, …) entirely — this emitter only contributes the load methods, no
/// ctor, no fields, no base class. No <c>[CompositionRoot]</c> in the compilation → no
/// <c>.g.cs</c> emitted at all.
/// </summary>
internal static class CompositionRootEmitter
{
    private const string SessionFqn   = "global::Surface.Runtime.SurrealSession";
    private const string TransportFqn = "global::Surface.Runtime.ISurrealTransport";
    private const string CtFqn        = "global::System.Threading.CancellationToken";
    private const string TaskFqn      = "global::System.Threading.Tasks.Task";

    public static void Emit(SourceProductionContext spc, ModelGraph graph)
    {
        if (graph.CompositionRoots.Count == 0)
        {
            return;
        }

        var root = graph.CompositionRoots[0];

        var aggregateRoots = new List<TableModel>();
        foreach (var t in graph.Tables)
        {
            if (t.IsAggregateRoot)
            {
                aggregateRoots.Add(t);
            }
        }

        if (aggregateRoots.Count == 0)
        {
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(root.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(root.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        var indent = hasNamespace ? "    " : string.Empty;
        var memberIndent = $"{indent}    ";

        sb.Append(indent).Append(FormatAccessibility(root.DeclaredAccessibility))
          .Append(" partial class ").AppendLine(root.Name);
        sb.Append(indent).AppendLine("{");

        for (var i = 0; i < aggregateRoots.Count; i++)
        {
            if (i > 0)
            {
                sb.AppendLine();
            }

            var aggRoot = aggregateRoots[i];
            var idType = $"global::{aggRoot.FullName}Id";
            var rootName = aggRoot.Name;
            var loaderFqn = $"global::Surface.Runtime.{rootName}AggregateLoader";

            sb.Append(memberIndent)
              .Append("/// <summary>Hydrates a snapshot of the ").Append(rootName)
              .Append(" aggregate rooted at <paramref name=\"rootId\"/>. The returned session is in-memory only — to persist changes, acquire a <see cref=\"global::Surface.Runtime.WriterLease\"/> and pass it to <see cref=\"global::Surface.Runtime.SurrealSession.CommitAsync\"/>.</summary>")
              .AppendLine();
            sb.Append(memberIndent).Append("public async ").Append(TaskFqn).Append('<').Append(SessionFqn)
              .Append("> Load").Append(rootName).Append("Async(")
              .Append(TransportFqn).Append(" transport, ")
              .Append(idType).Append(" rootId, ")
              .Append(CtFqn).AppendLine(" ct = default)");
            sb.Append(memberIndent).AppendLine("{");
            sb.Append(memberIndent).Append("    var ws = new ").Append(SessionFqn).AppendLine("(ReferenceRegistry);");
            sb.Append(memberIndent).Append("    await ").Append(loaderFqn).AppendLine(".PopulateAsync(ws, transport, rootId, ct);");
            sb.Append(memberIndent).AppendLine("    return ws;");
            sb.Append(memberIndent).AppendLine("}");
        }

        sb.Append(indent).AppendLine("}");

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        var hint = $"{root.FullName}.CompositionRoot.g.cs";
        spc.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string FormatAccessibility(string raw) => raw switch
    {
        "Public" => "public",
        "Internal" => "internal",
        "Private" => "private",
        "Protected" => "protected",
        "ProtectedOrInternal" => "protected internal",
        "ProtectedAndInternal" => "private protected",
        "NotApplicable" => string.Empty,
        _ => raw.ToLowerInvariant(),
    };
}
