using System.Text;
using Surface.Generator.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Surface.Generator.Emit;

/// <summary>
/// Emits the implementing half of every partial property and method on a <c>[Table]</c>
/// class. Reads are sync property bodies that hit the in-memory <c>SurrealSession</c>
/// snapshot; writes are sync <c>void</c> methods that record into the session's dirty
/// batch. Async only happens at the session boundary (load + commit) — nothing the
/// generator emits returns <see cref="System.Threading.Tasks.Task"/>.
/// <list type="bullet">
///   <item>[Id] — lazy-cached field; defaults to <c>{Name}Id.New()</c> on first access.</item>
///   <item>[Property] — getter-only or get/set partial property; setters write the backing
///         field then call <c>Session.SetField(this.Id, field, value)</c>.</item>
///   <item>[Reference] — sync getter-only partial property; non-nullable maps to
///         <c>Session.GetReference</c> (throws on miss), nullable to
///         <c>GetReferenceOrDefault</c>. Mandatory references emit an <c>OnCreate{Name}</c>
///         partial hook plus an entry in <c>IEntity.Initialize</c>. Settable references
///         route through <c>SetField/UnsetField</c> with <c>FieldKind.Reference</c>.</item>
///   <item>[Parent] — sync property; setter calls <c>SetField</c> with
///         <c>FieldKind.Parent</c>.</item>
///   <item>[Children] — sync getter-only partial property over <c>QueryChildren</c>.</item>
///   <item>Forward/inverse relation property — sync collection from <c>QueryRelated</c> /
///         <c>QueryRelatedIds</c> / <c>QueryInverseRelatedIds</c>; default protected
///         <c>Add/Remove/Clear</c> emit sync <c>void</c> writers that call
///         <c>Session.Relate</c> / <c>Unrelate</c> / <c>UnrelateAllFrom</c> /
///         <c>UnrelateAllTo</c>.</item>
/// </list>
/// </summary>
internal static class PartialEmitter
{
    private const string SessionType = "global::Surface.Runtime.SurrealSession";
    private const string EntityInterface = "global::Surface.Runtime.IEntity";
    private const string SurrealArrayMetadata = "Surface.Runtime.SurrealArray`1";

    public static void Emit(SourceProductionContext spc, TableModel table, ModelGraph graph)
    {
        if (!table.IsPartial)
        {
            return;
        }

        var partialProps = table.Properties.Where(p => p.IsPartial).ToArray();
        var partialMethods = table.Methods.Where(m => m.IsPartial).ToArray();
        if (partialProps.Length == 0 && partialMethods.Length == 0)
        {
            return;
        }

        var builder = new StringBuilder()
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(table.Namespace);
        if (hasNamespace)
        {
            builder
                .Append("namespace ")
                .Append(table.Namespace)
                .AppendLine()
                .AppendLine("{");
        }

        var indent = hasNamespace ? "    " : string.Empty;

        builder
            .Append(indent)
            .Append(FormatAccessibility(table.DeclaredAccessibility))
            .Append(' ');
        if (table.IsAbstract)
        {
            builder.Append("abstract ");
        }

        if (table.IsSealed)
        {
            builder.Append("sealed ");
        }

        builder
            .Append("partial class ")
            .Append(table.Name);
        if (table.TypeParameters.Count > 0)
        {
            builder
                .Append('<')
                .Append(string.Join(", ", table.TypeParameters))
                .Append('>');
        }

        builder
            .Append(" : ")
            .Append(EntityInterface);
        foreach (var union in graph.UnionsForTable(table.FullName))
        {
            builder
                .Append(", global::")
                .Append(union.InterfaceFullName);
        }
        builder
            .AppendLine()
            .Append(indent)
            .AppendLine("{");

        var memberIndent = $"{indent}    ";

        WriteSessionPlumbing(builder, memberIndent);

        var mandatoryRefs = new List<PropertyModel>();

        foreach (var t in partialProps)
        {
            builder.AppendLine();
            EmitProperty(builder, memberIndent, t, graph);

            if (IsMandatoryReference(t))
            {
                mandatoryRefs.Add(t);
            }
        }

        foreach (var t in partialMethods)
        {
            builder.AppendLine();
            EmitMethod(builder, memberIndent, t, graph);
        }

        // Initialize hook always emitted, even when empty — IEntity demands it and a
        // no-op for entities without mandatory refs is the cleanest path.
        builder.AppendLine();
        EmitInitialize(builder, memberIndent, mandatoryRefs);

        // Hydrate hook — invoked by the per-aggregate loader on each loaded row.
        builder.AppendLine();
        EmitHydrate(builder, memberIndent, table, graph);

        // OnDeleting hook — invoked by Session.Delete(IEntity) before the entity's own
        // delete command is queued. User can implement the simple-form partial method to
        // queue child deletes / clears.
        builder.AppendLine();
        EmitOnDeleting(builder, memberIndent);

        builder
            .Append(indent)
            .AppendLine("}");

        if (hasNamespace)
        {
            builder.AppendLine("}");
        }

        spc.AddSource(table.FileHintName, SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    // ──────────────────────────── per-table preamble ─────────────────────────

    /// <summary>
    /// Emits per-entity session plumbing: a private <c>_session</c> field, a private
    /// <c>_pendingWrites</c> buffer for object-initializer values that arrive before the
    /// entity is tracked, the explicit <c>IEntity.Session</c> getter (nullable),
    /// <c>IEntity.Bind</c> (one-shot setter for <c>_session</c>), <c>IEntity.Flush</c>
    /// (drains the buffer into the bound session), the protected <c>Session</c> property
    /// for entity-body reads (throws when unbound — reading from an unbound entity is a
    /// programmer error), and the <c>__WriteField</c> / <c>__ClearField</c> setter
    /// helpers that buffer when unbound or route through the session when bound.
    /// </summary>
    private static void WriteSessionPlumbing(StringBuilder builder, string indent)
    {
        builder
            .Append(indent)
            .Append("private ")
            .Append(SessionType)
            .AppendLine("? _session;")
            .Append(indent)
            .Append("private global::System.Collections.Generic.List<(string Field, object? Value, global::Surface.Runtime.FieldKind Kind)>? _pendingWrites;")
            .AppendLine()
            .AppendLine();

        builder
            .Append(indent)
            .Append(SessionType)
            .Append("? ")
            .Append(EntityInterface)
            .AppendLine(".Session => _session;")
            .AppendLine()
            .Append(indent)
            .Append("void ")
            .Append(EntityInterface)
            .Append(".Bind(")
            .Append(SessionType)
            .AppendLine(" session) => _session = session;")
            .AppendLine()
            .Append(indent)
            .Append("void ")
            .Append(EntityInterface)
            .Append(".Flush(")
            .Append(SessionType)
            .AppendLine(" session)")
            .Append(indent).AppendLine("{")
            .Append(indent).AppendLine("    if (_pendingWrites is null) return;")
            .Append(indent).AppendLine("    foreach (var (f, v, k) in _pendingWrites) session.SetField(this.Id, f, v, k);")
            .Append(indent).AppendLine("    _pendingWrites = null;")
            .Append(indent).AppendLine("}")
            .AppendLine();

        builder
            .Append(indent)
            .Append("protected ")
            .Append(SessionType)
            .AppendLine(" Session")
            .Append(indent)
            .AppendLine("    => _session ?? throw new global::System.InvalidOperationException(\"Entity is not bound to a session — call session.Track(...) or hydrate via Sessions.Load*Async first.\");")
            .AppendLine();

        builder
            .Append(indent)
            .Append("private void __WriteField(string field, object? value, global::Surface.Runtime.FieldKind kind = global::Surface.Runtime.FieldKind.Property)")
            .AppendLine()
            .Append(indent).AppendLine("{")
            .Append(indent).AppendLine("    if (_session is null) (_pendingWrites ??= new()).Add((field, value, kind));")
            .Append(indent).AppendLine("    else _session.SetField(this.Id, field, value, kind);")
            .Append(indent).AppendLine("}")
            .AppendLine()
            .Append(indent)
            .Append("private void __ClearField(string field, global::Surface.Runtime.FieldKind kind = global::Surface.Runtime.FieldKind.Property)")
            .AppendLine()
            .Append(indent).AppendLine("{")
            .Append(indent).AppendLine("    if (_session is null) _pendingWrites?.RemoveAll(p => p.Field == field);")
            .Append(indent).AppendLine("    else _session.UnsetField(this.Id, field, kind);")
            .Append(indent).AppendLine("}");
    }

    // ──────────────────────────── property emission ──────────────────────────

    private static void EmitProperty(StringBuilder builder, string indent, PropertyModel p, ModelGraph graph)
    {
        if (p.RelationRole is MethodRole.ForwardRelation or MethodRole.InverseRelation)
        {
            EmitRelationProperty(builder, indent, p, graph);
            return;
        }

        if (p.Kinds.HasFlag(PropertyKind.Id))
        {
            EmitIdProperty(builder, indent, p);
        }
        else if (p.Kinds.HasFlag(PropertyKind.Property))
        {
            EmitPropertyMember(builder, indent, p);
        }
        else if (p.Kinds.HasFlag(PropertyKind.Parent))
        {
            EmitParentProperty(builder, indent, p);
        }
        else if (p.Kinds.HasFlag(PropertyKind.Children))
        {
            EmitChildrenProperty(builder, indent, p);
        }
        else if (p.Kinds.HasFlag(PropertyKind.Reference))
        {
            EmitReferenceProperty(builder, indent, p);
        }
        else
        {
            EmitFallbackProperty(builder, indent, p);
        }
    }

    /// <summary>
    /// <c>[Property]</c> on a property declaration: scalar columns go through
    /// <see cref="EmitDataProperty"/> (backing field + setter routing through
    /// <c>SetField</c>); inline ordered collections typed as <c>SurrealArray&lt;T&gt;</c>
    /// go through <see cref="EmitSurrealArrayProperty"/> (lazy-cached wrapper that
    /// notifies the workspace on every mutation).
    /// </summary>
    private static void EmitPropertyMember(StringBuilder builder, string indent, PropertyModel p)
    {
        if (p.Type.MetadataName == SurrealArrayMetadata)
        {
            EmitSurrealArrayProperty(builder, indent, p);
        }
        else
        {
            EmitDataProperty(builder, indent, p);
        }
    }

    /// <summary>
    /// Emits the lazy-cached wrapper for an inline <c>array&lt;object&gt;</c> column.
    /// The wrapper is created once per entity instance (never replaced), so any reference
    /// the user holds stays valid as the list mutates. Mutations route through
    /// <see>
    ///     <cref>SurrealArray{T}</cref>
    /// </see>
    /// 's own notify path — the generator doesn't emit a
    /// setter or any per-verb method.
    /// </summary>
    private static void EmitSurrealArrayProperty(StringBuilder builder, string indent, PropertyModel p)
    {
        var declaredType = p.Type.FullyQualifiedName;
        var access = FormatAccessibility(p.DeclaredAccessibility);
        var backing = $"_{ToCamel(p.Name)}";
        var fieldLit = Quote(SurrealNaming.ToFieldName(p.Name));

        builder
            .Append(indent)
            .Append("private ")
            .Append(declaredType)
            .Append("? ")
            .Append(backing)
            .AppendLine(";")
            .Append(indent)
            .Append(access)
            .Append(" partial ")
            .Append(declaredType)
            .Append(' ')
            .Append(p.Name)
            .Append(" => ")
            .Append(backing)
            .Append(" ??= new ")
            .Append(declaredType)
            .Append("(this, ")
            .Append(fieldLit)
            .AppendLine(");");
    }

    private static void EmitIdProperty(StringBuilder builder, string indent, PropertyModel p)
    {
        var idType = p.Type.FullyQualifiedName;
        var idArg = StripNullable(idType);
        var access = FormatAccessibility(p.DeclaredAccessibility);

        // Id is lazy-minted on first read (`Id.New()`) and overridable via the setter so
        // callers can construct entity handles with a known id — handy for "look this
        // record up in a freshly loaded workspace" patterns. Hydrate also goes through
        // the setter (well, the backing field — same effect) when reloading.
        builder
            .Append(indent)
            .Append("private ")
            .Append(idArg)
            .AppendLine("? _id;")
            .Append(indent)
            .Append(access)
            .Append(" partial ")
            .Append(idType)
            .Append(' ')
            .AppendLine(p.Name)
            .Append(indent)
            .AppendLine("{")
            .Append(indent)
            .Append("    get => _id ??= ")
            .Append(idArg)
            .AppendLine(".New();")
            .Append(indent)
            .AppendLine("    set => _id = value;")
            .Append(indent)
            .AppendLine("}")
            // IEntity.Id needs the canonical RecordId; the typed id's implicit conversion
            // bridges the two so workspace internals key off a single struct type.
            .Append(indent)
            .Append("global::Surface.Runtime.RecordId ")
            .Append(EntityInterface)
            .AppendLine(".Id => this.Id;");
    }

    private static void EmitDataProperty(StringBuilder builder, string indent, PropertyModel p)
    {
        var type = p.Type.FullyQualifiedName;
        var access = FormatAccessibility(p.DeclaredAccessibility);
        var backing = $"_{ToCamel(p.Name)}";

        // = default! silences CS8618 for non-nullable types; CS0649 covers the case where
        // the user declares no setter (read-only [Property] is legal). Reading before any
        // setter runs returns the type's default — the schema's DEFAULT clause is the
        // contract for what the database hands back, not something we synthesise.
        builder
            .Append(indent)
            .AppendLine("#pragma warning disable CS0649")
            .Append(indent)
            .Append("private ")
            .Append(type)
            .Append(' ')
            .Append(backing)
            .AppendLine(" = default!;")
            .Append(indent)
            .AppendLine("#pragma warning restore CS0649");

        if (!p.HasSetter && !p.HasInitOnlySetter)
        {
            builder.Append(indent)
                .Append(access)
                .Append(" partial ")
                .Append(type)
                .Append(' ')
                .Append(p.Name)
                .Append(" => ")
                .Append(backing)
                .AppendLine(";");
            return;
        }

        var fieldLit = Quote(SurrealNaming.ToFieldName(p.Name));
        builder
            .Append(indent)
            .Append(access)
            .Append(" partial ")
            .Append(type)
            .Append(' ')
            .AppendLine(p.Name)
            .Append(indent)
            .AppendLine("{")
            .Append(indent)
            .Append("    get => ")
            .Append(backing)
            .AppendLine(";")
            .Append(indent)
            .Append("    ")
            .AppendLine(p.HasInitOnlySetter ? "init" : "set")
            .Append(indent)
            .AppendLine("    {")
            .Append(indent)
            .Append("        ")
            .Append(backing)
            .AppendLine(" = value;")
            .Append(indent)
            .Append("        __WriteField(")
            .Append(fieldLit)
            .AppendLine(", value);")
            .Append(indent)
            .AppendLine("    }")
            .Append(indent)
            .AppendLine("}");
    }

    private static void EmitParentProperty(StringBuilder builder, string indent, PropertyModel p)
    {
        var declared = p.Type.FullyQualifiedName;
        var typeArg = StripNullable(declared);
        var access = FormatAccessibility(p.DeclaredAccessibility);
        var fieldLit = Quote(SurrealNaming.ToFieldName(p.Name));

        if (!p.HasSetter && !p.HasInitOnlySetter)
        {
            builder.Append(indent)
                .Append(access)
                .Append(" partial ")
                .Append(declared)
                .Append(' ')
                .Append(p.Name)
                .Append(" => Session.GetParent<")
                .Append(typeArg)
                .AppendLine(">(this);");
            return;
        }

        builder
            .Append(indent)
            .Append(access)
            .Append(" partial ")
            .Append(declared)
            .Append(' ')
            .AppendLine(p.Name)
            .Append(indent)
            .AppendLine("{")
            .Append(indent)
            .Append("    get => Session.GetParent<")
            .Append(typeArg)
            .AppendLine(">(this);")
            .Append(indent)
            .Append("    ")
            .AppendLine(p.HasInitOnlySetter ? "init" : "set")
            .Append(indent)
            .Append("        => __WriteField(")
            .Append(fieldLit)
            .AppendLine(", value, global::Surface.Runtime.FieldKind.Parent);")
            .Append(indent)
            .AppendLine("}");
    }

    private static void EmitChildrenProperty(StringBuilder builder, string indent, PropertyModel p)
    {
        var declared = p.Type.FullyQualifiedName;
        var element = p.Type.ElementType ?? p.Type;
        var (elementTypeArg, elementNameExpr) = ResolveElement(element);
        var access = FormatAccessibility(p.DeclaredAccessibility);

        builder
            .Append(indent)
            .Append(access)
            .Append(" partial ")
            .Append(declared)
            .Append(' ')
            .Append(p.Name)
            .Append(" => Session.QueryChildren<")
            .Append(elementTypeArg)
            .Append(">(this, ")
            .Append(elementNameExpr)
            .AppendLine(");");
    }

    /// <summary>
    /// Sync property body for <c>[Reference]</c>:
    /// <list type="bullet">
    ///   <item>Get-only non-nullable → mandatory; <c>GetReference</c> (throws on miss).
    ///         Pairs with the <c>OnCreate{Name}</c> hook the workspace runs from
    ///         <see cref="EmitInitialize"/> when <c>Create&lt;T&gt;()</c> mints a fresh
    ///         entity.</item>
    ///   <item>Get-only nullable → optional; <c>GetReferenceOrDefault</c>.</item>
    ///   <item>Get + set non-nullable → user controls init themselves; setter calls
    ///         <c>SetField(..., FieldKind.Reference)</c>.</item>
    ///   <item>Get + set nullable → setter branches: null calls <c>UnsetField</c>,
    ///         non-null calls <c>SetField</c> — both with <c>FieldKind.Reference</c>.</item>
    /// </list>
    /// </summary>
    private static void EmitReferenceProperty(StringBuilder builder, string indent, PropertyModel p)
    {
        var declared = p.Type.FullyQualifiedName;
        var typeArg = StripNullable(declared);
        var access = FormatAccessibility(p.DeclaredAccessibility);
        var fieldLit = Quote(SurrealNaming.ToFieldName(p.Name));
        var nullable = p.Type.IsNullable;
        var getMethod = nullable ? "GetReferenceOrDefault" : "GetReference";

        if (!p.HasSetter && !p.HasInitOnlySetter)
        {
            builder
                .Append(indent)
                .Append(access)
                .Append(" partial ")
                .Append(declared)
                .Append(' ')
                .Append(p.Name)
                .Append(" => Session.")
                .Append(getMethod)
                .Append('<')
                .Append(typeArg)
                .Append(">(this, ")
                .Append(fieldLit)
                .AppendLine(");");
            return;
        }

        builder
            .Append(indent)
            .Append(access)
            .Append(" partial ")
            .Append(declared)
            .Append(' ')
            .AppendLine(p.Name)
            .Append(indent)
            .AppendLine("{")
            .Append(indent)
            .Append("    get => Session.")
            .Append(getMethod)
            .Append('<')
            .Append(typeArg)
            .Append(">(this, ")
            .Append(fieldLit)
            .AppendLine(");")
            .Append(indent)
            .Append("    ")
            .AppendLine(p.HasInitOnlySetter ? "init" : "set");

        if (nullable)
        {
            builder
                .Append(indent)
                .AppendLine("    {")
                .Append(indent)
                .Append("        if (value is null) __ClearField(")
                .Append(fieldLit)
                .AppendLine(", global::Surface.Runtime.FieldKind.Reference);")
                .Append(indent)
                .Append("        else __WriteField(")
                .Append(fieldLit)
                .AppendLine(", value, global::Surface.Runtime.FieldKind.Reference);")
                .Append(indent)
                .AppendLine("    }");
        }
        else
        {
            builder
                .Append(indent)
                .Append("        => __WriteField(")
                .Append(fieldLit)
                .AppendLine(", value, global::Surface.Runtime.FieldKind.Reference);");
        }

        builder
            .Append(indent)
            .AppendLine("}");
    }

    /// <summary>
    /// A getter-only collection property carrying a forward/inverse relation attribute
    /// maps to either:
    /// <list type="bullet">
    ///   <item>Within-aggregate → <c>Session.QueryRelated&lt;TKind, TElement&gt;(this)</c>
    ///         (entity-typed, joins against the snapshot's <c>entities</c> dict; the kind
    ///         marker carries the edge name).</item>
    ///   <item>Cross-aggregate → <c>Session.QueryRelatedIds&lt;TKind&gt;(this)</c> /
    ///         <c>QueryInverseRelatedIds&lt;TKind&gt;(this)</c> (id-typed, since
    ///         target/source entities live in a different aggregate snapshot).</item>
    /// </list>
    /// </summary>
    private static void EmitRelationProperty(StringBuilder builder, string indent, PropertyModel p, ModelGraph graph)
    {
        var declared = p.Type.FullyQualifiedName;
        var access = FormatAccessibility(p.DeclaredAccessibility);
        var kindMarker = ResolveKindMarkerFqn(p.RelationKindFullName, graph);

        var forwardKindFullName = ForwardKindFullNameFor(p.RelationKindFullName, p.RelationRole, graph);
        var crossAggregate = forwardKindFullName is not null && graph.IsCrossAggregate(forwardKindFullName);

        if (crossAggregate)
        {
            var method = p.RelationRole == MethodRole.ForwardRelation ? "QueryRelatedIds" : "QueryInverseRelatedIds";
            builder
                .Append(indent)
                .Append(access)
                .Append(" partial ")
                .Append(declared)
                .Append(' ')
                .Append(p.Name)
                .Append(" => Session.")
                .Append(method)
                .Append('<')
                .Append(kindMarker)
                .AppendLine(">(this);");
            return;
        }

        var elementType = p.Type.ElementType ?? p.Type;
        var elementArg = elementType.IsTypeParameter
            ? elementType.DisplayName
            : StripNullable(elementType.FullyQualifiedName);

        builder
            .Append(indent)
            .Append(access)
            .Append(" partial ")
            .Append(declared)
            .Append(' ')
            .Append(p.Name)
            .Append(" => Session.QueryRelated<")
            .Append(kindMarker)
            .Append(", ")
            .Append(elementArg)
            .AppendLine(">(this);");
    }

    /// <summary>
    /// Resolves the FQN of the typed-kind marker class emitted alongside a forward
    /// relation attribute. <paramref name="memberKindFullName"/> may be either side —
    /// inverse kinds resolve to their paired forward's marker.
    /// </summary>
    private static string ResolveKindMarkerFqn(string? memberKindFullName, ModelGraph graph)
    {
        var kind = graph.FindKind(memberKindFullName);
        if (kind is null)
        {
            return "global::Surface.Runtime.IRelationKind";
        }

        var forward = kind.Direction == RelationDirection.Forward
            ? kind
            : graph.FindKind(kind.PairedForwardFullName);
        if (forward is null)
        {
            return "global::Surface.Runtime.IRelationKind";
        }

        var markerName = SurrealNaming.StripAttributeSuffix(forward.Name);
        return string.IsNullOrEmpty(forward.Namespace)
            ? $"global::{markerName}"
            : $"global::{forward.Namespace}.{markerName}";
    }

    /// <summary>
    /// Resolves the forward kind FQN whether the member sits on the forward or inverse
    /// side. Forward-side members carry the forward kind directly; inverse-side members
    /// carry the inverse kind and we walk to the paired forward.
    /// </summary>
    private static string? ForwardKindFullNameFor(string? memberKindFullName, MethodRole role, ModelGraph graph)
    {
        if (memberKindFullName is null)
        {
            return null;
        }

        if (role == MethodRole.ForwardRelation)
        {
            return memberKindFullName;
        }

        var kind = graph.FindKind(memberKindFullName);
        return kind?.PairedForwardFullName;
    }

    private static void EmitFallbackProperty(StringBuilder builder, string indent, PropertyModel p)
    {
        var type = p.Type.FullyQualifiedName;
        var access = FormatAccessibility(p.DeclaredAccessibility);
        builder
            .Append(indent)
            .Append(access)
            .Append(" partial ")
            .Append(type)
            .Append(' ')
            .Append(p.Name)
            .AppendLine(" => throw new global::System.NotImplementedException();");
    }

    // ──────────────────────────── method emission ────────────────────────────

    /// <summary>
    /// Methods only carry meaning for relation Add/Remove/Clear today — <c>[Property]</c>,
    /// <c>[Parent]</c>, <c>[Reference]</c>, <c>[Children]</c> are property-only attributes.
    /// Anything else falls through to a NotImplementedException body so a stale partial
    /// method declaration surfaces clearly instead of silently emitting nothing.
    /// </summary>
    private static void EmitMethod(StringBuilder builder, string indent, MethodModel m, ModelGraph graph)
    {
        var body = m.Role switch
        {
            MethodRole.ForwardRelation or MethodRole.InverseRelation => BuildRelationBody(m, graph),
            _ => "throw new global::System.NotImplementedException()",
        };
        WriteMethodSignature(builder, indent, m);
        builder
            .Append(" => ")
            .Append(body)
            .AppendLine(";");
    }

    private static string ToCamel(string s) =>
        s.Length == 0 ? s : char.ToLowerInvariant(s[0]) + s[1..];

    private static string BuildRelationBody(MethodModel m, ModelGraph graph)
    {
        var kindMarker = ResolveKindMarkerFqn(m.RelationKindFullName, graph);
        var (a, b) = m.Role == MethodRole.ForwardRelation
            ? ("this", FirstParamName(m))
            : (FirstParamName(m), "this");

        return m.Verb switch
        {
            MethodVerb.Add =>
                $"Session.Relate<{kindMarker}>({a}, {b})",
            MethodVerb.Remove =>
                $"Session.Unrelate<{kindMarker}>({a}, {b})",
            MethodVerb.Clear =>
                m.Role == MethodRole.ForwardRelation
                    ? $"Session.UnrelateAllFrom<{kindMarker}>(this)"
                    : $"Session.UnrelateAllTo<{kindMarker}>(this)",
            _ => "throw new global::System.NotImplementedException()",
        };
    }

    /// <summary>
    /// Resolves element info for a TypeRef. The <c>NameExpr</c> is the Surreal table-name
    /// string the runtime keys off (lower_snake_case + pluralised). For concrete types we
    /// bake the literal at codegen time; for type parameters we fall back to
    /// <c>typeof(T).Name</c> — only ever hit by generic <c>[Children]</c>, which CG009
    /// rejects, so the unresolved-name path is effectively dead.
    /// </summary>
    private static (string TypeArg, string NameExpr) ResolveElement(TypeRef t)
    {
        if (t.IsTypeParameter)
        {
            return (t.DisplayName, $"typeof({t.DisplayName}).Name");
        }

        var stripped = StripNullable(t.FullyQualifiedName);
        return (stripped, Quote(SurrealNaming.ToTableName(SurrealNaming.SimpleName(stripped))));
    }

    // ──────────────────────────── relation default mutators ─────────────────
    // Empty section — no default Add/Remove/Clear methods are emitted any more. The
    // typed `Session.Relate<TKind>(...)` etc. is the canonical surface; users who want a
    // domain-named verb write a one-line passthrough in their own partial:
    //
    //     public void Restricts(IRestrictedBy x) => Session.Relate<Restricts>(this, x);

    // ──────────────────────────── Initialize emission ────────────────────────

    private static bool IsMandatoryReference(PropertyModel p)
        => p.Kinds.HasFlag(PropertyKind.Reference)
           && !p.Type.IsNullable
           && p.HasGetter
           && !p.HasSetter
           && !p.HasInitOnlySetter;

    /// <summary>
    /// Emits the <c>void IEntity.Initialize(SurrealSession)</c> impl that <c>Session.Track</c>
    /// invokes immediately after a fresh entity is tracked. For each mandatory
    /// <c>[Reference]</c> we also emit the <c>OnCreate{Name}</c> partial declaration so
    /// the user supplies the seed logic, then mint the target, run the hook, and write
    /// the reference. Entities without mandatory refs get an empty body.
    /// </summary>
    private static void EmitInitialize(StringBuilder builder, string indent, List<PropertyModel> mandatoryRefs)
    {
        foreach (var p in mandatoryRefs)
        {
            var typeArg = StripNullable(p.Type.FullyQualifiedName);
            // Simple-form partial — no accessibility, no body required. If the user
            // doesn't implement it, the call below is elided at compile time and
            // the new entity just keeps its DEFAULT-clause field values.
            builder
                .Append(indent)
                .Append("partial void OnCreate")
                .Append(p.Name)
                .Append('(')
                .Append(typeArg)
                .AppendLine(" entity);");
        }

        if (mandatoryRefs.Count > 0)
        {
            builder.AppendLine();
        }

        builder
            .Append(indent)
            .Append("void ")
            .Append(EntityInterface)
            .Append(".Initialize(")
            .Append(SessionType)
            .Append(" session)");

        if (mandatoryRefs.Count == 0)
        {
            builder.AppendLine(" { }");
            return;
        }

        builder
            .AppendLine()
            .Append(indent)
            .AppendLine("{");
        foreach (var p in mandatoryRefs)
        {
            var typeArg = StripNullable(p.Type.FullyQualifiedName);
            var fieldLit = Quote(SurrealNaming.ToFieldName(p.Name));
            var local = $"__{ToCamel(p.Name)}";

            builder.Append(indent)
                .Append("    var ")
                .Append(local)
                .Append(" = new ")
                .Append(typeArg)
                .AppendLine("();")
                .Append(indent)
                .Append("    OnCreate")
                .Append(p.Name)
                .Append('(')
                .Append(local)
                .AppendLine(");")
                .Append(indent)
                .Append("    session.SetField(this.Id, ")
                .Append(fieldLit)
                .Append(", ")
                .Append(local)
                .AppendLine(", global::Surface.Runtime.FieldKind.Reference);");
        }

        builder
            .Append(indent)
            .AppendLine("}");
    }

    // ──────────────────────────── OnDeleting emission ───────────────────────

    /// <summary>
    /// Emits a simple-form <c>partial void OnDeleting()</c> hook the user may optionally
    /// implement to queue dependent-delete / reference-clear commands, plus the explicit
    /// <see>
    ///     <cref>IEntity.OnDeleting</cref>
    /// </see>
    /// impl that the workspace dispatches to. If the
    /// user doesn't implement the partial, the call inside the dispatch is elided at
    /// compile time and Delete just queues the entity's own DELETE command.
    /// </summary>
    private static void EmitOnDeleting(StringBuilder builder, string indent)
    {
        builder
            .Append(indent)
            .AppendLine("partial void OnDeleting();")
            .AppendLine()
            .Append(indent)
            .Append("void ")
            .Append(EntityInterface)
            .AppendLine(".OnDeleting() => OnDeleting();");
    }

    // ──────────────────────────── Hydrate emission ──────────────────────────

    /// <summary>
    /// Emits <c>IEntity.Hydrate(JsonElement, SurrealSession)</c> for the table. Reads each
    /// declared property from the JSON row:
    /// <list type="bullet">
    ///   <item>[Id] → parses the record id string and sets the typed <c>_id</c> field.</item>
    ///   <item>scalar [Property] → reads the field value and sets the backing field.</item>
    ///   <item>[Reference] → reads the record id, calls <c>session.HydrateReference</c>.</item>
    ///   <item>[Parent] → reads the record id, calls <c>session.HydrateParent</c>.</item>
    /// </list>
    /// <c>SurrealArray</c> properties hydrate inline via <see cref="EmitHydrateSurrealArray"/>.
    /// Forward/inverse relation edges are loaded separately by the per-aggregate loader's
    /// edge queries.
    /// </summary>
    private static void EmitHydrate(StringBuilder builder, string indent, TableModel table, ModelGraph graph)
    {
        builder
            .Append(indent)
            .Append("void ")
            .Append(EntityInterface)
            .AppendLine($".Hydrate(global::System.Text.Json.JsonElement json, {SessionType} session)")
            .Append(indent)
            .AppendLine("{");

        var idProp = table.Properties.FirstOrDefault(p => p.Kinds.HasFlag(PropertyKind.Id));
        if (idProp is not null)
        {
            // Match IdEmitter's LiteralExpr/NewValueExpr surface: built-in factories for
            // Ulid (default), Guid, and string. Anything else — extend IdEmitter and add
            // a matching reader to HydrationJson.
            var reader = graph.IdValueTypeFullName switch
            {
                "global::System.Ulid"   => "ReadUlidIdValue",
                "global::System.Guid"   => "ReadGuidIdValue",
                "global::System.String" => "ReadStringIdValue",
                _ => null,
            };
            var idType = StripNullable(idProp.Type.FullyQualifiedName);
            builder
                .Append(indent)
                .AppendLine("    if (json.TryGetProperty(\"id\", out var __idElem))");

            if (reader is null)
            {
                builder
                    .Append(indent)
                    .Append("        throw new global::System.NotSupportedException(\"No built-in id-value reader for ")
                    .Append(graph.IdValueTypeFullName)
                    .AppendLine(". Built-in support: Ulid, Guid, string.\");");
            }
            else
            {
                builder
                    .Append(indent)
                    .Append("        _id = new ")
                    .Append(idType)
                    .Append("(global::Surface.Runtime.HydrationJson.")
                    .Append(reader)
                    .AppendLine("(__idElem));");
            }
        }

        builder
            .Append(indent)
            .AppendLine("    session.HydrateTrack(this);");

        foreach (var p in table.Properties)
        {
            if (p.Kinds.HasFlag(PropertyKind.Property))
            {
                if (p.Type.MetadataName == SurrealArrayMetadata)
                {
                    EmitHydrateSurrealArray(builder, indent, p);
                }
                else
                {
                    EmitHydrateValueProperty(builder, indent, p);
                }
            }
            else if (p.Kinds.HasFlag(PropertyKind.Reference))
            {
                EmitHydrateReference(builder, indent, p);
            }
            else if (p.Kinds.HasFlag(PropertyKind.Parent))
            {
                EmitHydrateParent(builder, indent, p);
            }
            // [Children] is computed via parentByChild reverse lookup — nothing to read here.
            // Forward/inverse relation properties are populated by the per-aggregate loader's
            // edge query, not by per-row Hydrate.
        }

        builder
            .Append(indent)
            .AppendLine("}");
    }

    /// <summary>
    /// Hydrates any non-<c>SurrealArray</c> [Property] — scalar (int, bool, DateTime, …),
    /// array (<c>int[]</c>, <c>List&lt;T&gt;</c>), record, dictionary, anything
    /// <see cref="System.Text.Json.JsonSerializer"/> understands. String stays special-cased
    /// so its empty-string fallback matches the schema's <c>DEFAULT ""</c> clause without
    /// a round-trip through the serializer.
    /// </summary>
    private static void EmitHydrateValueProperty(StringBuilder builder, string indent, PropertyModel p)
    {
        var backing = $"_{ToCamel(p.Name)}";
        var fieldLit = Quote(SurrealNaming.ToFieldName(p.Name));
        var typeFqn = p.Type.FullyQualifiedName;

        if (typeFqn is "string" or "global::System.String" or "string?" or "global::System.String?")
        {
            builder
                .Append(indent)
                .Append("    ")
                .Append(backing)
                .Append(" = global::Surface.Runtime.HydrationJson.ReadString(json, ")
                .Append(fieldLit)
                .AppendLine(");");
            return;
        }

        // ReadOrDefault<T> always returns T? — `?? default!` lands in the non-nullable
        // backing field for both value types (int, bool, …) and reference types (where
        // null! matches the existing `_field = default!` initialisation).
        var deserialiseAs = StripNullable(typeFqn);
        builder
            .Append(indent)
            .Append("    ")
            .Append(backing)
            .Append(" = global::Surface.Runtime.HydrationJson.ReadOrDefault<")
            .Append(deserialiseAs)
            .Append(">(json, ")
            .Append(fieldLit)
            .AppendLine(") ?? default!;");
    }

    /// <summary>
    /// Hydrates a <c>SurrealArray&lt;T&gt;</c>-typed property: reads the JSON array, deserialises
    /// each element into <c>T</c> via <see>
    ///     <cref>System.Text.Json.JsonSerializer</cref>
    /// </see>
    /// using
    /// <c>SurrealJson.SerializerOptions</c> (so the schema's snake_case field names match
    /// the C# record properties), and pre-populates the backing field with a tracked list
    /// initialised from the loaded items. Skips silently when the field is missing or the
    /// value isn't an array — first read will then return an empty wrapper.
    /// </summary>
    private static void EmitHydrateSurrealArray(StringBuilder builder, string indent, PropertyModel p)
    {
        var backing = $"_{ToCamel(p.Name)}";
        var fieldLit = Quote(SurrealNaming.ToFieldName(p.Name));
        var declaredType = p.Type.FullyQualifiedName;
        if (p.Type.TypeArguments.Count == 0)
        {
            // Should be unreachable — `partial SurrealArray Foo { get; }` without a type
            // argument doesn't compile. Escalate at runtime if it ever fires so we hear
            // about it rather than silently leaving the wrapper null.
            builder
                .Append(indent)
                .Append("    throw new global::System.NotSupportedException(\"Hydrate: SurrealArray element type for property '")
                .Append(p.Name)
                .AppendLine("' could not be resolved at codegen time.\");");
            return;
        }

        var elementType = p.Type.TypeArguments[0].FullyQualifiedName;

        var localItems = $"__{ToCamel(p.Name)}Items";
        var localElem = $"__{ToCamel(p.Name)}Elem";

        builder.Append(indent)
            .Append("    if (json.TryGetProperty(")
            .Append(fieldLit)
            .Append(", out var ")
            .Append(localElem)
            .Append(") && ")
            .Append(localElem)
            .AppendLine(".ValueKind == global::System.Text.Json.JsonValueKind.Array)")
            .Append(indent)
            .AppendLine("    {")
            .Append(indent)
            .Append("        var ")
            .Append(localItems)
            .Append(" = new global::System.Collections.Generic.List<")
            .Append(elementType)
            .Append(">(")
            .Append(localElem)
            .AppendLine(".GetArrayLength());")
            .Append(indent)
            .Append("        foreach (var __row in ")
            .Append(localElem)
            .AppendLine(".EnumerateArray())")
            .Append(indent)
            .AppendLine("        {")
            .Append(indent)
            .Append("            var __decoded = global::System.Text.Json.JsonSerializer.Deserialize<")
            .Append(elementType)
            .AppendLine(">(__row, global::Surface.Runtime.SurrealJson.SerializerOptions);")
            .Append(indent)
            .Append("            if (__decoded is not null) ")
            .Append(localItems)
            .AppendLine(".Add(__decoded);")
            .Append(indent)
            .AppendLine("        }")
            .Append(indent)
            .Append("        ")
            .Append(backing)
            .Append(" = new ")
            .Append(declaredType)
            .Append("(this, ")
            .Append(fieldLit)
            .Append(", ")
            .Append(localItems)
            .AppendLine(");")
            .Append(indent)
            .AppendLine("    }");
    }

    private static void EmitHydrateReference(StringBuilder builder, string indent, PropertyModel p)
    {
        var fieldLit = Quote(SurrealNaming.ToFieldName(p.Name));
        var typeArg = StripNullable(p.Type.FullyQualifiedName);
        // HydrationJson.HydrateReference<T> handles both the id-only and inline-record
        // shapes — for the inline form (`field.*` projection) it constructs and hydrates
        // the referenced entity from the same payload so reads can resolve it.
        builder
            .Append(indent)
            .Append("    global::Surface.Runtime.HydrationJson.HydrateReference<")
            .Append(typeArg)
            .Append(">(json, ")
            .Append(fieldLit)
            .AppendLine(", this.Id, session);");
    }

    private static void EmitHydrateParent(StringBuilder builder, string indent, PropertyModel p)
    {
        var fieldLit = Quote(SurrealNaming.ToFieldName(p.Name));
        builder
            .Append(indent)
            .Append("    if (global::Surface.Runtime.HydrationJson.TryReadRecordId(json, ")
            .Append(fieldLit)
            .Append(", out var __parent_")
            .Append(ToCamel(p.Name))
            .AppendLine("))")
            .Append(indent)
            .Append("        session.HydrateParent(this.Id, __parent_")
            .Append(ToCamel(p.Name))
            .AppendLine(");");
    }

    // ──────────────────────────── helpers ────────────────────────────────────

    private static string FirstParamName(MethodModel m) =>
        m.Parameters.Count > 0 ? m.Parameters[0].Name : "default!";

    private static string Quote(string s) => $"\"{s.Replace("\"", "\\\"")}\"";

    private static void WriteMethodSignature(StringBuilder builder, string indent, MethodModel m)
    {
        builder
            .Append(indent)
            .Append(FormatAccessibility(m.DeclaredAccessibility))
            .Append(' ');
        if (m.IsStatic)
        {
            builder.Append("static ");
        }

        builder
            .Append("partial ")
            .Append(m.ReturnsVoid ? "void" : m.ReturnType.FullyQualifiedName)
            .Append(' ')
            .Append(m.Name);

        if (m.TypeParameters.Count > 0)
        {
            builder
                .Append('<')
                .Append(string.Join(", ", m.TypeParameters))
                .Append('>');
        }

        builder.Append('(');
        for (var i = 0; i < m.Parameters.Count; i++)
        {
            if (i > 0)
            {
                builder.Append(", ");
            }

            var param = m.Parameters[i];
            var modifier = FormatRefKind(param.RefKind);
            if (modifier.Length > 0)
            {
                builder
                    .Append(modifier)
                    .Append(' ');
            }

            builder
                .Append(param.Type.FullyQualifiedName)
                .Append(' ')
                .Append(param.Name);
        }
        builder.Append(')');
    }

    private static string StripNullable(string typeName)
        => typeName.EndsWith("?") ? typeName[..^1] : typeName;

    private static string FormatAccessibility(string raw) => raw switch
    {
        "Public" => "public",
        "Internal" => "internal",
        "Private" => "private",
        "Protected" => "protected",
        "ProtectedOrInternal" => "protected internal",
        "ProtectedAndInternal" => "private protected",
        "NotApplicable" => string.Empty,
        _ => raw.ToLowerInvariant(),
    };

    private static string FormatRefKind(string raw) => raw switch
    {
        "Ref" => "ref",
        "Out" => "out",
        "In" => "in",
        "RefReadOnlyParameter" => "ref readonly",
        _ => string.Empty,
    };
}
