using System.Text;
using Surface.Generator.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Surface.Generator.Emit;

/// <summary>
/// Emits a sealed <c>IReferenceRegistry</c> implementation for the consumer assembly,
/// mapping every <c>[Reference]</c> field across every <c>[Table]</c> by referenced-table
/// name. A <c>[ModuleInitializer]</c> on the generated class registers it with the
/// runtime's static <c>ReferenceRegistry</c> facade on assembly load — so the commit
/// planner can answer "this record is being deleted; what points at it and what's the
/// configured delete behavior?" without the runtime knowing about the consumer's tables.
/// </summary>
internal static class ReferenceRegistryEmitter
{
    private const string Namespace        = "Surface.Runtime";
    private const string GeneratedClass   = "GeneratedReferenceRegistry";

    public static void Emit(SourceProductionContext spc, ModelGraph graph)
    {
        // Walk every [Reference] property on every table; collect into buckets keyed by
        // the referenced table name (snake_case + pluralised — the same table-name
        // string the runtime's RecordId.Table uses).
        var byReferenced = new SortedDictionary<string, List<(string Referencer, string Field, ReferenceDeletePolicy Behavior, bool Nullable)>>(StringComparer.Ordinal);

        foreach (var table in graph.Tables)
        {
            var referencerTable = SurrealNaming.ToTableName(table.Name);
            foreach (var p in table.Properties)
            {
                if (!p.Kinds.HasFlag(PropertyKind.Reference))
                {
                    continue;
                }

                if (!p.Type.IsTableType && p.Type.ElementType is null)
                {
                    continue;
                }

                var targetTypeFqn = StripNullableMarker(UnwrapTask(p.Type.FullyQualifiedName));
                var simpleTargetName = SurrealNaming.SimpleName(targetTypeFqn);
                var referencedTable = SurrealNaming.ToTableName(simpleTargetName);
                var fieldName = SurrealNaming.ToFieldName(p.Name);

                if (!byReferenced.TryGetValue(referencedTable, out var list))
                {
                    list = [];
                    byReferenced[referencedTable] = list;
                }
                list.Add((referencerTable, fieldName, p.ReferenceDelete, p.Type.IsNullable));
            }
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").Append(Namespace).AppendLine(";");
        sb.AppendLine();
        sb.Append("internal sealed class ").Append(GeneratedClass).AppendLine(" : global::Surface.Runtime.IReferenceRegistry");
        sb.AppendLine("{");
        sb.Append("    public static readonly ").Append(GeneratedClass).Append(" Instance = new ").Append(GeneratedClass).AppendLine("();");
        sb.AppendLine();
        sb.AppendLine("    private static readonly System.Collections.Generic.Dictionary<string, System.Collections.Generic.IReadOnlyList<global::Surface.Runtime.ReferenceFieldInfo>> _byReferencedTable = new(System.StringComparer.Ordinal)");
        sb.AppendLine("    {");
        foreach (var kv in byReferenced)
        {
            sb.Append("        [\"").Append(kv.Key).AppendLine("\"] = new global::Surface.Runtime.ReferenceFieldInfo[]");
            sb.AppendLine("        {");
            foreach (var entry in kv.Value)
            {
                sb.Append("            new(\"").Append(entry.Referencer).Append("\", \"").Append(entry.Field).Append("\", \"").Append(kv.Key).Append("\", ")
                  .Append("global::Surface.Runtime.ReferenceDeleteBehavior.").Append(entry.Behavior.ToString()).Append(", ")
                  .Append(entry.Nullable ? "true" : "false").AppendLine("),");
            }
            sb.AppendLine("        },");
        }
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public System.Collections.Generic.IReadOnlyList<global::Surface.Runtime.ReferenceFieldInfo> IncomingReferencesTo(string referencedTable) =>");
        sb.AppendLine("        _byReferencedTable.TryGetValue(referencedTable, out var refs) ? refs : System.Array.Empty<global::Surface.Runtime.ReferenceFieldInfo>();");
        sb.AppendLine();
        sb.AppendLine("    [System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Register() => global::Surface.Runtime.ReferenceRegistry.Register(Instance);");
        sb.AppendLine("}");

        spc.AddSource($"{Namespace}.{GeneratedClass}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string UnwrapTask(string typeName)
    {
        const string prefix = "global::System.Threading.Tasks.Task<";
        if (typeName.StartsWith(prefix) && typeName.EndsWith(">"))
        {
            return typeName.Substring(prefix.Length, typeName.Length - prefix.Length - 1);
        }

        return typeName;
    }

    private static string StripNullableMarker(string typeName)
        => typeName.EndsWith("?") ? typeName[..^1] : typeName;
}
