using System.Text;
using Surface.Generator.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Surface.Generator.Emit;

/// <summary>
/// Emits the per-consumer <see cref="ReferenceFieldInfo"/> registry. Two parts:
/// <list type="number">
///   <item>An <c>internal sealed class GeneratedReferenceRegistry : IReferenceRegistry</c>
///         in the user's <c>[CompositionRoot]</c> namespace, populated with every
///         <c>[Reference]</c> field bucketed by referenced-table name.</item>
///   <item>A partial fragment of the <c>[CompositionRoot]</c> class adding a
///         <c>public static IReferenceRegistry ReferenceRegistry</c> property that
///         returns the singleton instance.</item>
/// </list>
/// Skipped when no <c>[CompositionRoot]</c> is declared — without one there's nowhere
/// to hang the static surface, and the caller can construct sessions with the
/// registry by hand.
/// <para>
/// No more <c>[ModuleInitializer]</c> + static facade. The registry is per-model,
/// passed into <see cref="SurrealSession"/>'s constructor by the user's emitted
/// <c>Load*Async</c>, so multiple Surface-generated models can coexist in the same
/// process.
/// </para>
/// </summary>
internal static class ReferenceRegistryEmitter
{
    private const string GeneratedClass = "GeneratedReferenceRegistry";

    public static void Emit(SourceProductionContext spc, ModelGraph graph)
    {
        if (graph.CompositionRoots.Count != 1) return;
        var root = graph.CompositionRoots[0];
        if (!root.IsPartial) return;

        var byReferenced = new SortedDictionary<string, List<(string Referencer, string Field, ReferenceDeletePolicy Behavior, bool Nullable)>>(StringComparer.Ordinal);

        foreach (var table in graph.Tables)
        {
            var referencerTable = SurrealNaming.ToTableName(table.Name);
            foreach (var p in table.Properties)
            {
                if (!p.Kinds.HasFlag(PropertyKind.Reference)) continue;
                if (!p.Type.IsTableType && p.Type.ElementType is null) continue;

                var targetTypeFqn = StripNullableMarker(UnwrapTask(p.Type.FullyQualifiedName));
                var simpleTargetName = SurrealNaming.SimpleName(targetTypeFqn);
                var referencedTable = SurrealNaming.ToTableName(simpleTargetName);
                var fieldName = SurrealNaming.ToFieldName(p.Name);

                if (!byReferenced.TryGetValue(referencedTable, out var list))
                {
                    list = [];
                    byReferenced[referencedTable] = list;
                }
                list.Add((referencerTable, fieldName, p.ReferenceDelete, p.Type.IsNullable));
            }
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(root.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(root.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        var indent = hasNamespace ? "    " : string.Empty;
        var memberIndent = $"{indent}    ";

        // Partial fragment of the user's [CompositionRoot] — adds the static accessor.
        sb.Append(indent).Append(FormatAccessibility(root.DeclaredAccessibility))
          .Append(" partial class ").AppendLine(root.Name);
        sb.Append(indent).AppendLine("{");
        sb.Append(memberIndent).AppendLine("/// <summary>The model's reference-field registry. Pass into <see cref=\"global::Surface.Runtime.SurrealSession\"/> to drive [Reject] / [Unset] / [Cascade] resolution at commit time.</summary>");
        sb.Append(memberIndent).Append("public static global::Surface.Runtime.IReferenceRegistry ReferenceRegistry => ").Append(GeneratedClass).AppendLine(".Instance;");
        sb.Append(indent).AppendLine("}");
        sb.AppendLine();

        // Impl class — internal to the consumer assembly.
        sb.Append(indent).Append("internal sealed class ").Append(GeneratedClass).AppendLine(" : global::Surface.Runtime.IReferenceRegistry");
        sb.Append(indent).AppendLine("{");
        sb.Append(memberIndent).Append("public static readonly ").Append(GeneratedClass).Append(" Instance = new ").Append(GeneratedClass).AppendLine("();");
        sb.AppendLine();
        sb.Append(memberIndent).AppendLine("private static readonly System.Collections.Generic.Dictionary<string, System.Collections.Generic.IReadOnlyList<global::Surface.Runtime.ReferenceFieldInfo>> _byReferencedTable = new(System.StringComparer.Ordinal)");
        sb.Append(memberIndent).AppendLine("{");
        foreach (var kv in byReferenced)
        {
            sb.Append(memberIndent).Append("    [\"").Append(kv.Key).AppendLine("\"] = new global::Surface.Runtime.ReferenceFieldInfo[]");
            sb.Append(memberIndent).AppendLine("    {");
            foreach (var entry in kv.Value)
            {
                sb.Append(memberIndent).Append("        new(\"").Append(entry.Referencer).Append("\", \"").Append(entry.Field).Append("\", \"").Append(kv.Key).Append("\", ")
                  .Append("global::Surface.Runtime.ReferenceDeleteBehavior.").Append(entry.Behavior.ToString()).Append(", ")
                  .Append(entry.Nullable ? "true" : "false").AppendLine("),");
            }
            sb.Append(memberIndent).AppendLine("    },");
        }
        sb.Append(memberIndent).AppendLine("};");
        sb.AppendLine();
        sb.Append(memberIndent).AppendLine("public System.Collections.Generic.IReadOnlyList<global::Surface.Runtime.ReferenceFieldInfo> IncomingReferencesTo(string referencedTable) =>");
        sb.Append(memberIndent).AppendLine("    _byReferencedTable.TryGetValue(referencedTable, out var refs) ? refs : System.Array.Empty<global::Surface.Runtime.ReferenceFieldInfo>();");
        sb.Append(indent).AppendLine("}");

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        spc.AddSource($"{root.FullName}.ReferenceRegistry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string UnwrapTask(string typeName)
    {
        const string prefix = "global::System.Threading.Tasks.Task<";
        if (typeName.StartsWith(prefix) && typeName.EndsWith(">"))
        {
            return typeName.Substring(prefix.Length, typeName.Length - prefix.Length - 1);
        }

        return typeName;
    }

    private static string StripNullableMarker(string typeName)
        => typeName.EndsWith("?") ? typeName[..^1] : typeName;

    private static string FormatAccessibility(string raw) => raw switch
    {
        "Public" => "public",
        "Internal" => "internal",
        "Private" => "private",
        "Protected" => "protected",
        "ProtectedOrInternal" => "protected internal",
        "ProtectedAndInternal" => "private protected",
        "NotApplicable" => string.Empty,
        _ => raw.ToLowerInvariant(),
    };
}
