using System.Text;
using Surface.Generator.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Surface.Generator.Emit;

/// <summary>
/// For each forward relation attribute (e.g. <c>RestrictsAttribute : ForwardRelation</c>),
/// emits a sibling marker class without the <c>Attribute</c> suffix
/// (<c>Restricts : IRelationKind</c>) carrying the SurrealDB edge-table name as a static
/// abstract override. The class is the type witness used by
/// <c>SurrealSession.Relate&lt;Restricts&gt;(src, tgt)</c> and friends — it gives the
/// generic call a compile-time anchor without having to thread a string literal through.
/// <para>
/// Inverse kinds get no marker — the edge is named after the forward, so
/// <c>Session.Relate&lt;Restricts&gt;</c> covers both directions; querying decides the
/// side based on whether the owner is the source or target.
/// </para>
/// <para>
/// The marker class deliberately has a private constructor today — there's no
/// instance-side API yet. When edge payload arrives the same class grows a public
/// constructor and content fields, so existing call sites keep compiling unchanged.
/// </para>
/// </summary>
internal static class RelationKindEmitter
{
    private const string IRelationKindFqn = "global::Surface.Runtime.IRelationKind";

    public static void Emit(SourceProductionContext spc, ModelGraph graph)
    {
        foreach (var kind in graph.RelationKinds)
        {
            if (kind.Direction != RelationDirection.Forward)
            {
                continue;
            }

            EmitForKind(spc, kind);
        }
    }

    private static void EmitForKind(SourceProductionContext spc, RelationKindModel kind)
    {
        var markerName = SurrealNaming.StripAttributeSuffix(kind.Name);
        var edgeName = SurrealNaming.ToEdgeName(kind.Name);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(kind.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(kind.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        var indent = hasNamespace ? "    " : string.Empty;
        var memberIndent = $"{indent}    ";

        sb.Append(indent).Append("public sealed class ").Append(markerName).Append(" : ").AppendLine(IRelationKindFqn);
        sb.Append(indent).AppendLine("{");
        sb.Append(memberIndent).Append("public static string EdgeName => \"").Append(edgeName).AppendLine("\";");
        sb.Append(memberIndent).Append("private ").Append(markerName).AppendLine("() { }");
        sb.Append(indent).AppendLine("}");

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        var hint = string.IsNullOrEmpty(kind.Namespace)
            ? $"{markerName}.RelationKind.g.cs"
            : $"{kind.Namespace}.{markerName}.RelationKind.g.cs";
        spc.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
