using System.Text;
using Surface.Generator.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Surface.Generator.Emit;

/// <summary>
/// Emits the per-relation-kind marker interface — one per multi-member union side. The
/// interface inherits from <see cref="IEntity"/> so session methods that already
/// accept <c>IEntity</c> still take any union member.
/// <para>
/// File names follow the same hint convention as everything else in the generator
/// (<c>{FullName}.g.cs</c>) so the consumer can find them in the generated output
/// folder alongside the entity partials.
/// </para>
/// </summary>
internal static class UnionInterfaceEmitter
{
    private const string EntityInterface = "global::Surface.Runtime.IEntity";
    private const string RecordIdInterface = "global::Surface.Runtime.IRecordId";

    public static void Emit(SourceProductionContext spc, RelationUnion union)
    {
        EmitInterface(spc, union, union.InterfaceName, union.InterfaceFullName, EntityInterface, isIdSide: false);
        EmitInterface(spc, union, union.IdInterfaceName, union.IdInterfaceFullName, RecordIdInterface, isIdSide: true);
    }

    private static void EmitInterface(
        SourceProductionContext spc,
        RelationUnion union,
        string interfaceName,
        string interfaceFullName,
        string baseInterface,
        bool isIdSide)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(union.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(union.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        var indent = hasNamespace ? "    " : string.Empty;
        var sideLabel = union.Direction == UnionDirection.Target ? "target" : "source";
        var kindLabel = isIdSide ? "id-side" : "entity-side";

        sb.Append(indent).Append("/// <summary>Generated ").Append(kindLabel).Append(" marker for the ")
          .Append(sideLabel).Append(" union of the relation kind <c>").Append(union.ForwardKindFullName).AppendLine("</c>.</summary>");

        sb.Append(indent).Append("public interface ").Append(interfaceName)
          .Append(" : ").Append(baseInterface).AppendLine(" { }");

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        spc.AddSource($"{interfaceFullName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
