using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace Disruptor.Surface.Generator.Emit;

/// <summary>
/// Small source-generation writer that owns indentation, braces, and common file
/// preamble shape. It intentionally stays text-based; emitters still decide what code
/// to write, while this type keeps layout mechanics consistent.
/// </summary>
internal sealed class CodeWriter
{
    private const int IndentSize = 4;

    private readonly StringBuilder builder = new();
    private int indentLevel;

    public CodeWriter Header()
    {
        Line("// <auto-generated />");
        Line("#nullable enable");
        Line("");
        return this;
    }

    public CodeWriter Line(string text)
    {
        if (text.Length > 0)
        {
            builder.Append(' ', indentLevel * IndentSize);
            builder.Append(text);
        }

        builder.AppendLine();
        return this;
    }

    public IDisposable Indent()
    {
        indentLevel++;
        return new Scope(this, closeLine: null);
    }

    public IDisposable Block(string header)
    {
        if (string.IsNullOrWhiteSpace(header))
        {
            throw new ArgumentException("Block header cannot be empty.", nameof(header));
        }

        Line(header);
        return BracedBlock();
    }

    public IDisposable BracedBlock()
    {
        Line("{");
        indentLevel++;
        return new Scope(this, closeLine: "}");
    }

    public IDisposable Namespace(string? namespaceName)
        => string.IsNullOrEmpty(namespaceName)
            ? NoopScope.Instance
            : Block($"namespace {namespaceName}");

    /// <summary>
    /// Open a <c>switch (<paramref name="scrutineeExpr"/>)</c> block. Body uses
    /// <see cref="Case"/> to write case arms; the <c>break;</c> / <c>return;</c> /
    /// <c>throw …</c> terminator stays the caller's responsibility so fall-through and
    /// return-style arms remain expressible.
    /// </summary>
    public IDisposable Switch(string scrutineeExpr)
    {
        if (string.IsNullOrWhiteSpace(scrutineeExpr))
        {
            throw new ArgumentException("Switch scrutinee cannot be empty.", nameof(scrutineeExpr));
        }

        return Block($"switch ({scrutineeExpr})");
    }

    /// <summary>
    /// Emit a <c>case <paramref name="caseLabel"/>:</c> header and open an indent scope
    /// for the arm body. <paramref name="caseLabel"/> is the raw label expression — the
    /// caller is responsible for quoting string literals (typically via <c>Quote</c>) so
    /// constant patterns / enum members / pattern matches all flow through the same API.
    /// The caller writes the terminator (<c>break;</c>, <c>return;</c>, <c>throw …</c>).
    /// </summary>
    public IDisposable Case(string caseLabel)
    {
        if (string.IsNullOrWhiteSpace(caseLabel))
        {
            throw new ArgumentException("Case label cannot be empty.", nameof(caseLabel));
        }

        Line($"case {caseLabel}:");
        indentLevel++;
        return new Scope(this, closeLine: null);
    }

    public CodeWriter Delimited<T>(IEnumerable<T> items, Action<T, bool> writeItem)
    {
        if (items is null)
        {
            throw new ArgumentNullException(nameof(items));
        }

        if (writeItem is null)
        {
            throw new ArgumentNullException(nameof(writeItem));
        }

        using var enumerator = items.GetEnumerator();
        if (!enumerator.MoveNext())
        {
            return this;
        }

        var current = enumerator.Current;
        while (true)
        {
            var hasNext = enumerator.MoveNext();
            writeItem(current, !hasNext);
            if (!hasNext)
            {
                return this;
            }

            current = enumerator.Current;
        }
    }

    public SourceText ToSourceText() => SourceText.From(ToString(), Encoding.UTF8);

    public override string ToString() => builder.ToString();

    private void Close(string? closeLine)
    {
        if (indentLevel == 0)
        {
            throw new InvalidOperationException("Cannot close a CodeWriter scope when indentation is already zero.");
        }

        indentLevel--;
        if (closeLine is not null)
        {
            Line(closeLine);
        }
    }

    private sealed class Scope(CodeWriter writer, string? closeLine) : IDisposable
    {
        private bool disposed;

        public void Dispose()
        {
            if (disposed)
            {
                return;
            }

            disposed = true;
            writer.Close(closeLine);
        }
    }

    private sealed class NoopScope : IDisposable
    {
        public static readonly NoopScope Instance = new();

        private NoopScope()
        {
        }

        public void Dispose()
        {
        }
    }
}
