using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace Disruptor.Surface.Generator.Emit;

/// <summary>
/// Small source-generation writer that owns indentation, braces, and common file
/// preamble shape. It intentionally stays text-based; emitters still decide what code
/// to write, while this type keeps layout mechanics consistent.
/// </summary>
internal sealed class CodeWriter
{
    private const int IndentSize = 4;

    private readonly StringBuilder builder = new();
    private int indentLevel;

    public CodeWriter Header()
    {
        Line("// <auto-generated />");
        Line("#nullable enable");
        Line();
        return this;
    }

    public CodeWriter Line() => Line(string.Empty);

    public CodeWriter Line(string text)
    {
        if (text.Length > 0)
        {
            builder.Append(' ', indentLevel * IndentSize);
            builder.Append(text);
        }

        builder.AppendLine();
        return this;
    }

    public CodeWriter AppendLine(string text = "") => Line(text);

    public IDisposable Indent()
    {
        indentLevel++;
        return new Scope(this, closeLine: null);
    }

    public IDisposable Block(string header)
    {
        if (string.IsNullOrWhiteSpace(header))
        {
            throw new ArgumentException("Block header cannot be empty.", nameof(header));
        }

        Line(header);
        return BracedBlock();
    }

    public IDisposable BracedBlock()
    {
        Line("{");
        indentLevel++;
        return new Scope(this, closeLine: "}");
    }

    public IDisposable Namespace(string? namespaceName)
        => string.IsNullOrEmpty(namespaceName)
            ? NoopScope.Instance
            : Block($"namespace {namespaceName}");

    public CodeWriter Delimited<T>(IEnumerable<T> items, Action<T, bool> writeItem)
    {
        if (items is null)
        {
            throw new ArgumentNullException(nameof(items));
        }

        if (writeItem is null)
        {
            throw new ArgumentNullException(nameof(writeItem));
        }

        using var enumerator = items.GetEnumerator();
        if (!enumerator.MoveNext())
        {
            return this;
        }

        var current = enumerator.Current;
        while (true)
        {
            var hasNext = enumerator.MoveNext();
            writeItem(current, !hasNext);
            if (!hasNext)
            {
                return this;
            }

            current = enumerator.Current;
        }
    }

    public SourceText ToSourceText() => SourceText.From(ToString(), Encoding.UTF8);

    public override string ToString() => builder.ToString();

    private void Close(string? closeLine)
    {
        if (indentLevel == 0)
        {
            throw new InvalidOperationException("Cannot close a CodeWriter scope when indentation is already zero.");
        }

        indentLevel--;
        if (closeLine is not null)
        {
            Line(closeLine);
        }
    }

    private sealed class Scope : IDisposable
    {
        private readonly CodeWriter writer;
        private readonly string? closeLine;
        private bool disposed;

        public Scope(CodeWriter writer, string? closeLine)
        {
            this.writer = writer;
            this.closeLine = closeLine;
        }

        public void Dispose()
        {
            if (disposed)
            {
                return;
            }

            disposed = true;
            writer.Close(closeLine);
        }
    }

    private sealed class NoopScope : IDisposable
    {
        public static readonly NoopScope Instance = new();

        private NoopScope()
        {
        }

        public void Dispose()
        {
        }
    }
}
