using System.Text;
using Disruptor.Surface.Generator.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Disruptor.Surface.Generator.Emit;

/// <summary>
/// Emits a per-forward-relation <c>{Kind}EdgeQ</c> static class carrying one
/// <c>PropertyExpr&lt;T&gt;</c> field per payload property, mirroring how
/// <see cref="PredicateFactoryEmitter"/> emits <c>{Table}Q</c> for entity tables.
/// Only forward kinds derived from <c>ForwardRelation&lt;TPayload&gt;</c> get a
/// factory — bare <c>ForwardRelation</c> has no payload fields and so no
/// predicates to compose against.
/// <para>
/// Example shape consumed at the call site:
/// <code>
/// var edges = await Workspace.Query.Edges.Uses
///     .OutgoingFrom([symbol.Id])
///     .Where(UsesEdgeQ.Kind.Eq("call"))
///     .OrderBy(UsesEdgeQ.Line)
///     .Limit(20)
///     .ExecuteAsync(transport);
/// </code>
/// </para>
/// </summary>
internal static class EdgePredicateFactoryEmitter
{
    private const string PropertyExprFqn = "global::Disruptor.Surface.Runtime.Query.PropertyExpr";

    public static void Emit(SourceProductionContext spc, RelationKindModel kind)
    {
        if (kind.Direction != RelationDirection.Forward)
        {
            return;
        }

        if (kind.PayloadFields.Count == 0)
        {
            return;
        }

        // Mirror RelationKindEmitter's naming so the EdgeQ class lives next to the
        // marker class and uses the same suffix-stripped form (e.g. UsesAttribute →
        // UsesEdgeQ, sitting next to the Uses : IRelationKind marker).
        var markerName = SurrealNaming.StripAttributeSuffix(kind.Name);
        var qTypeName = $"{markerName}EdgeQ";

        var sb = new StringBuilder()
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(kind.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(kind.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        var indent = hasNamespace ? "    " : string.Empty;
        var memberIndent = $"{indent}    ";

        sb.Append(indent)
          .AppendLine($"/// <summary>Predicate factory for the <c>{markerName}</c> edge's payload — one <c>PropertyExpr&lt;T&gt;</c> per public scalar property of the relation's payload type. Compose with <c>EdgeQuery&lt;TIn, TOut&gt;.Where(...)</c> / <c>.OrderBy(...)</c>.</summary>");
        sb.Append(indent).Append("public static class ").AppendLine(qTypeName);
        sb.Append(indent).AppendLine("{");

        foreach (var field in kind.PayloadFields)
        {
            // Skip un-mappable types — schema emission already drops them, so a
            // PropertyExpr<Uri> would refer to a non-existent column. Same gate
            // PredicateFactoryEmitter applies to entity properties.
            if (!SchemaEmitter.IsMappableScalar(field.Type))
            {
                continue;
            }

            sb.Append(memberIndent)
              .Append("public static readonly ")
              .Append(PropertyExprFqn).Append('<').Append(field.Type.FullyQualifiedName).Append("> ")
              .Append(field.Name)
              .Append(" = new(\"").Append(field.FieldName).AppendLine("\");");
        }

        sb.Append(indent).AppendLine("}");

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        var hint = string.IsNullOrEmpty(kind.Namespace)
            ? $"{qTypeName}.g.cs"
            : $"{kind.Namespace}.{qTypeName}.g.cs";
        spc.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
