using System.Text;
using Disruptor.Surface.Generator.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Disruptor.Surface.Generator.Emit;

/// <summary>
/// Emits a partial fragment of the user's <c>[CompositionRoot]</c> exposing
/// <c>Workspace.Hydrate.{Table}(ids)</c> entry points — one
/// <see cref="HydrationQuery{T}"/> factory per <c>[Table]</c>. The shape mirrors
/// <see cref="QueryRootEmitter"/>: the public accessor lives on the user's partial,
/// the actual table catalogue lives on an internal companion class.
/// <para>
/// Each per-table accessor is a method (not a property) because hydration takes a
/// concrete id list — typed <c>{Table}Id</c> overload + raw <c>RecordId</c> overload
/// for callers working in the canonical id space (e.g. cross-aggregate edge ids).
/// </para>
/// <para>
/// Skipped when no <c>[CompositionRoot]</c> is declared (or it isn't partial) — the
/// emitted body needs <c>Workspace.ReferenceRegistry</c> for session construction.
/// </para>
/// </summary>
internal static class HydrateRootEmitter
{
    private const string HydrationQueryFqn = "global::Disruptor.Surface.Runtime.Query.HydrationQuery";
    private const string RecordIdFqn = "global::Disruptor.Surface.Runtime.RecordId";
    private const string IRecordIdFqn = "global::Disruptor.Surface.Runtime.IRecordId";
    private const string IEnumerableFqn = "global::System.Collections.Generic.IEnumerable";
    private const string IReadOnlyListFqn = "global::System.Collections.Generic.IReadOnlyList";
    private const string GeneratedClass = "GeneratedHydrationRoot";

    public static void Emit(SourceProductionContext spc, ModelGraph graph)
    {
        if (graph.CompositionRoots.Count != 1) return;
        var root = graph.CompositionRoots[0];
        if (!root.IsPartial) return;
        if (graph.Tables.Count == 0) return;

        var ordered = graph.Tables.OrderBy(t => t.Name, StringComparer.Ordinal).ToList();
        var refRegistryFqn = string.IsNullOrEmpty(root.Namespace)
            ? $"global::{root.Name}.ReferenceRegistry"
            : $"global::{root.Namespace}.{root.Name}.ReferenceRegistry";

        var sb = new StringBuilder()
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(root.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(root.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        var indent = hasNamespace ? "    " : string.Empty;
        var memberIndent = $"{indent}    ";
        var nestedIndent = $"{memberIndent}    ";

        // Partial fragment of [CompositionRoot] — adds the static Hydrate accessor.
        sb.Append(indent).Append(FormatAccessibility(root.DeclaredAccessibility))
          .Append(" partial class ").AppendLine(root.Name);
        sb.Append(indent).AppendLine("{");
        sb.Append(memberIndent).AppendLine("/// <summary>Hydration entry points — one per <c>[Table]</c>. Pass a list of ids; chain <c>.WithInclude(...)</c> to widen the slice; terminate with <c>.ExecuteAsync(transport, [lease])</c> to materialise into a tracked session.</summary>");
        sb.Append(memberIndent).Append("public static ").Append(GeneratedClass).Append(" Hydrate => ")
          .Append(GeneratedClass).AppendLine(".Instance;");
        sb.Append(indent).AppendLine("}");
        sb.AppendLine();

        sb.Append(indent).Append("public sealed class ").AppendLine(GeneratedClass);
        sb.Append(indent).AppendLine("{");
        sb.Append(memberIndent).Append("public static readonly ").Append(GeneratedClass).Append(" Instance = new ").Append(GeneratedClass).AppendLine("();");
        sb.AppendLine();
        sb.Append(memberIndent).Append("private ").Append(GeneratedClass).AppendLine("() { }");

        foreach (var table in ordered)
        {
            var tableName = SurrealNaming.ToTableName(table.Name);
            var methodName = PascalPluralize(table.Name);
            var entityFqn = string.IsNullOrEmpty(table.Namespace)
                ? $"global::{table.Name}"
                : $"global::{table.Namespace}.{table.Name}";
            var idFqn = $"{entityFqn}Id";

            sb.AppendLine();
            sb.Append(memberIndent)
              .Append("/// <summary>Hydrate the matching <see cref=\"").Append(entityFqn.Substring("global::".Length))
              .AppendLine("\"/> rows into a fresh tracked session. Typed-id overload — preferred call site shape.</summary>");
            sb.Append(memberIndent)
              .Append("public ").Append(HydrationQueryFqn).Append('<').Append(entityFqn).Append("> ")
              .Append(methodName).Append('(').Append(IEnumerableFqn).Append('<').Append(idFqn).AppendLine("> ids)");
            sb.Append(memberIndent).AppendLine("{");
            sb.Append(nestedIndent).AppendLine("global::System.ArgumentNullException.ThrowIfNull(ids);");
            sb.Append(nestedIndent).Append("var snap = SnapshotIds(ids);");
            sb.AppendLine();
            sb.Append(nestedIndent).Append("return new ").Append(HydrationQueryFqn).Append('<').Append(entityFqn)
              .Append(">(\"").Append(tableName).Append("\", snap, ").Append(refRegistryFqn).AppendLine(");");
            sb.Append(memberIndent).AppendLine("}");

            sb.AppendLine();
            sb.Append(memberIndent)
              .AppendLine("/// <summary>Raw-id overload — accepts any <see cref=\"global::Disruptor.Surface.Runtime.IRecordId\"/>; useful for cross-aggregate edge endpoints already collapsed to canonical record ids.</summary>");
            sb.Append(memberIndent)
              .Append("public ").Append(HydrationQueryFqn).Append('<').Append(entityFqn).Append("> ")
              .Append(methodName).Append('(').Append(IEnumerableFqn).Append('<').Append(IRecordIdFqn).AppendLine("> ids)");
            sb.Append(memberIndent).AppendLine("{");
            sb.Append(nestedIndent).AppendLine("global::System.ArgumentNullException.ThrowIfNull(ids);");
            sb.Append(nestedIndent).Append("var snap = SnapshotIds(ids);");
            sb.AppendLine();
            sb.Append(nestedIndent).Append("return new ").Append(HydrationQueryFqn).Append('<').Append(entityFqn)
              .Append(">(\"").Append(tableName).Append("\", snap, ").Append(refRegistryFqn).AppendLine(");");
            sb.Append(memberIndent).AppendLine("}");
        }

        // Shared helper — collapses any id-typed enumerable into an IReadOnlyList<RecordId>.
        // Each typed {Table}Id implicitly converts to RecordId; raw IRecordId converts via
        // RecordId.From. Snapshotting up front means the HydrationQuery sees a stable list
        // even if the caller mutates the source enumerable mid-flight.
        sb.AppendLine();
        sb.Append(memberIndent)
          .Append("private static ").Append(IReadOnlyListFqn).Append('<').Append(RecordIdFqn)
          .Append("> SnapshotIds<TId>(").Append(IEnumerableFqn).AppendLine("<TId> ids) where TId : ").Append(IRecordIdFqn);
        sb.Append(memberIndent).AppendLine("{");
        sb.Append(nestedIndent).Append("if (ids is global::System.Collections.Generic.ICollection<TId> col)");
        sb.AppendLine();
        sb.Append(nestedIndent).AppendLine("{");
        sb.Append(nestedIndent).Append("    var arr = new ").Append(RecordIdFqn).AppendLine("[col.Count];");
        sb.Append(nestedIndent).AppendLine("    var i = 0;");
        sb.Append(nestedIndent).AppendLine("    foreach (var id in col)");
        sb.Append(nestedIndent).AppendLine("    {");
        sb.Append(nestedIndent).Append("        arr[i++] = ").Append(RecordIdFqn).AppendLine(".From(id);");
        sb.Append(nestedIndent).AppendLine("    }");
        sb.Append(nestedIndent).AppendLine("    return arr;");
        sb.Append(nestedIndent).AppendLine("}");
        sb.AppendLine();
        sb.Append(nestedIndent).Append("var list = new global::System.Collections.Generic.List<").Append(RecordIdFqn).AppendLine(">();");
        sb.Append(nestedIndent).AppendLine("foreach (var id in ids)");
        sb.Append(nestedIndent).AppendLine("{");
        sb.Append(nestedIndent).Append("    list.Add(").Append(RecordIdFqn).AppendLine(".From(id));");
        sb.Append(nestedIndent).AppendLine("}");
        sb.Append(nestedIndent).AppendLine("return list;");
        sb.Append(memberIndent).AppendLine("}");

        sb.Append(indent).AppendLine("}");

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        spc.AddSource($"{root.FullName}.Hydrate.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string PascalPluralize(string typeName)
        => Humanizer.InflectorExtensions.Pluralize(typeName, inputIsKnownToBeSingular: false);

    private static string FormatAccessibility(string raw) => raw switch
    {
        "Public" => "public",
        "Internal" => "internal",
        "Private" => "private",
        "Protected" => "protected",
        "ProtectedOrInternal" => "protected internal",
        "ProtectedAndInternal" => "private protected",
        "NotApplicable" => string.Empty,
        _ => raw.ToLowerInvariant(),
    };
}
