using System.Text;
using Disruptor.Surface.Generator.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Disruptor.Surface.Generator.Emit;

/// <summary>
/// Emits the per-table <c>{Name}Id</c> — a <c>readonly record struct</c> wrapping a
/// <c>Ulid</c> and implementing <c>IRecordId</c>. Kept zero-alloc so id values can flow
/// through SurrealSession primitives without hydrating an entity. Ulid is the only
/// supported id value type — quoted-string ids are not supported, and Guid / int / cuid2
/// can be added later if a real need surfaces.
/// </summary>
internal static class IdEmitter
{
    private const string IRecordIdType = "global::Disruptor.Surface.Runtime.IRecordId";
    private const string RecordIdType = "global::Disruptor.Surface.Runtime.RecordId";
    private const string UlidType = "global::System.Ulid";

    public static void Emit(SourceProductionContext spc, TableModel table, ModelGraph graph)
    {
        var idTypeName = $"{table.Name}Id";
        var builder = new StringBuilder()
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine();
        var hasNamespace = !string.IsNullOrEmpty(table.Namespace);
        if (hasNamespace)
        {
            builder
                .Append("namespace ")
                .Append(table.Namespace)
                .AppendLine()
                .AppendLine("{");
        }
        var indent = hasNamespace ? "    " : string.Empty;
        var memberIndent = $"{indent}    ";
        builder
            .Append(indent)
            .Append("public readonly record struct ")
            .Append(idTypeName)
            .Append('(')
            .Append(UlidType)
            .Append(" Value) : ")
            .Append(IRecordIdType);
        // Add id-side union interfaces (one per multi-member union this table is in).
        // Mirrors PartialEmitter's entity-side base list — IRestrictedById alongside IRestrictedBy.
        foreach (var union in graph.UnionsForTable(table.FullName))
        {
            builder
                .Append(", global::")
                .Append(union.IdInterfaceFullName);
        }
        builder
            .AppendLine()
            .Append(indent)
            .AppendLine("{")
            // Table name — Surreal convention is lower_snake_case + pluralised. Stays in lockstep
            // with the strings PartialEmitter bakes for child/reference/relation calls so that
            // SurrealSession.IsForTable comparisons line up.
            .Append(memberIndent)
            .Append("public string Table => \"")
            .Append(SurrealNaming.ToTableName(table.Name))
            .AppendLine("\";")
            .AppendLine()
            // Ulid stringifies idempotently; that's the literal half of the record id.
            .Append(memberIndent)
            .AppendLine("public string ToLiteral() => Value.ToString();")
            .AppendLine()
            // Fresh-id factory — Ulid.NewUlid() is the only mint path.
            .Append(memberIndent)
            .Append("public static ")
            .Append(idTypeName)
            .Append(" New() => new(")
            .Append(UlidType)
            .AppendLine(".NewUlid());")
            .AppendLine()
            .Append(memberIndent)
            .AppendLine("public override string ToString() => Table + \":\" + ToLiteral();")
            .AppendLine()
            // Implicit conversion to the canonical RecordId — SurrealSession internals key off (Table, Value)
            // tuples, so every generated id should be able to flow into that shape transparently.
            .Append(memberIndent)
            .Append("public static implicit operator ")
            .Append(RecordIdType)
            .Append('(')
            .Append(idTypeName)
            .Append(" id) => new(id.Table, id.ToLiteral());")
            .AppendLine()
            .Append(indent)
            .AppendLine("}");
        if (hasNamespace)
        {
            builder.AppendLine("}");
        }
        var hint = string.IsNullOrEmpty(table.Namespace)
            ? $"{idTypeName}.g.cs"
            : $"{table.Namespace}.{idTypeName}.g.cs";
        spc.AddSource(hint, SourceText.From(builder.ToString(), Encoding.UTF8));
    }
}
