using System.Text;
using Disruptor.Surface.Generator.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Disruptor.Surface.Generator.Emit;

/// <summary>
/// Emits the per-table <c>{Name}Id</c> — a <c>readonly record struct</c> wrapping a
/// validated <c>string</c> and implementing <c>IRecordId</c>. Kept zero-alloc so id values
/// can flow through SurrealSession primitives without hydrating an entity. Two and only
/// two value forms are accepted (validated in the ctor via
/// <c>Disruptor.Surface.Runtime.RecordIdFormat.Validate</c>):
/// <list type="bullet">
///   <item>Ulid stringifications — what <c>{Name}Id.New()</c> mints (the default).</item>
///   <item>Short lower_snake_case slugs (max 32 chars) — opt-in for stable-named records.</item>
/// </list>
/// </summary>
internal static class IdEmitter
{
    private const string IRecordIdType = "global::Disruptor.Surface.Runtime.IRecordId";
    private const string RecordIdType = "global::Disruptor.Surface.Runtime.RecordId";
    private const string FormatType = "global::Disruptor.Surface.Runtime.RecordIdFormat";

    public static void Emit(SourceProductionContext spc, TableModel table, ModelGraph graph)
    {
        var idTypeName = $"{table.Name}Id";
        var builder = new StringBuilder()
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine();
        var hasNamespace = !string.IsNullOrEmpty(table.Namespace);
        if (hasNamespace)
        {
            builder
                .Append("namespace ")
                .Append(table.Namespace)
                .AppendLine()
                .AppendLine("{");
        }
        var indent = hasNamespace ? "    " : string.Empty;

        // Id-side union interfaces (one per multi-member union this table is in).
        // Mirrors PartialEmitter's entity-side base list — IRestrictedById alongside IRestrictedBy.
        var idUnions = graph.UnionsForTable(table.FullName)
            .Select(u => $"global::{u.IdInterfaceFullName}");
        WriteIdType(builder, indent, idTypeName, SurrealNaming.ToTableName(table.Name), idUnions);

        if (hasNamespace)
        {
            builder.AppendLine("}");
        }
        var hint = string.IsNullOrEmpty(table.Namespace)
            ? $"{idTypeName}.g.cs"
            : $"{table.Namespace}.{idTypeName}.g.cs";
        spc.AddSource(hint, SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    /// <summary>
    /// Emits a <c>readonly record struct {idTypeName}(string Value) : IRecordId, …</c>
    /// at <paramref name="indent"/>, with <paramref name="tableName"/> baked into the
    /// <c>Table</c> property. Shared with <see cref="RelationKindEmitter"/> so per-kind
    /// id types (<c>RestrictsId</c>) get the same validation + factory shape as per-table
    /// ids (<c>ConstraintId</c>). <paramref name="extraBaseInterfaces"/> are appended to
    /// the base list — empty for per-kind ids, the id-side union markers for per-table ids.
    /// </summary>
    internal static void WriteIdType(
        StringBuilder builder,
        string indent,
        string idTypeName,
        string tableName,
        IEnumerable<string> extraBaseInterfaces)
    {
        var memberIndent = $"{indent}    ";
        builder
            .Append(indent)
            .Append("public readonly record struct ")
            .Append(idTypeName)
            .Append("(string Value) : ")
            .Append(IRecordIdType);
        foreach (var iface in extraBaseInterfaces)
        {
            builder.Append(", ").Append(iface);
        }
        builder
            .AppendLine()
            .Append(indent)
            .AppendLine("{")
            // Re-declare Value with a validating initializer — the primary-ctor parameter
            // flows through RecordIdFormat.Validate, which rejects anything that isn't a
            // Ulid stringification or a short lower_snake_case slug.
            .Append(memberIndent)
            .Append("public string Value { get; } = ")
            .Append(FormatType)
            .AppendLine(".Validate(Value);")
            .AppendLine()
            // Table name — Surreal convention is lower_snake_case + pluralised. Stays in lockstep
            // with the strings PartialEmitter bakes for child/reference/relation calls so that
            // SurrealSession.IsForTable comparisons line up.
            .Append(memberIndent)
            .Append("public string Table => \"")
            .Append(tableName)
            .AppendLine("\";")
            .AppendLine()
            .Append(memberIndent)
            .AppendLine("public string ToLiteral() => Value;")
            .AppendLine()
            // Fresh-id factory — Ulid.NewUlid().ToString() is the only mint path.
            .Append(memberIndent)
            .Append("public static ")
            .Append(idTypeName)
            .AppendLine(" New() => new(global::System.Ulid.NewUlid().ToString());")
            .AppendLine()
            .Append(memberIndent)
            .AppendLine("public override string ToString() => Table + \":\" + Value;")
            .AppendLine()
            // Implicit conversion to the canonical RecordId — SurrealSession internals key off (Table, Value)
            // tuples, so every generated id should be able to flow into that shape transparently.
            .Append(memberIndent)
            .Append("public static implicit operator ")
            .Append(RecordIdType)
            .Append('(')
            .Append(idTypeName)
            .Append(" id) => new(id.Table, id.Value);")
            .AppendLine()
            .Append(indent)
            .AppendLine("}");
    }
}
