using System.Text;
using Disruptor.Surface.Generator.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Disruptor.Surface.Generator.Emit;

/// <summary>
/// Emits a per-<c>[Table]</c> <c>{Name}QueryIds</c> static class carrying the
/// <c>IdsAsync</c> extension on <see cref="Query{T}"/>:
/// <code>
/// IReadOnlyList&lt;CodeSymbolId&gt; ids = await workspace.Query.CodeSymbols
///     .Where(CodeSymbolQ.Name.Contains("Parser"))
///     .OrderBy(CodeSymbolQ.QualifiedName)
///     .Limit(50)
///     .IdsAsync(transport, ct);
/// </code>
/// <para>
/// The terminal verb for "give me the ids that match — nothing else." Compiles to
/// <c>SELECT id FROM table WHERE … ORDER BY … LIMIT … START …</c> via
/// <c>QueryCompiler.CompileIdsOnly</c> and projects each returned <see cref="RecordId"/>
/// into the typed <c>{Table}Id</c>. Includes are not supported on this path: id-only
/// selection is flat by definition; callers wanting traversal use <c>ExecuteAsync</c>.
/// </para>
/// <para>
/// Sits alongside <see cref="LoadEntryEmitter"/> (which handles the write-mode aggregate
/// load) and the per-table <see cref="PredicateFactoryEmitter"/> output. The body inlines
/// the compile + transport + materialise steps so the runtime doesn't need a same-named
/// instance method on <see cref="Query{T}"/> that would shadow this extension.
/// </para>
/// </summary>
internal static class IdsAsyncEmitter
{
    private const string QueryFqn = "global::Disruptor.Surface.Runtime.Query.Query";
    private const string TransportFqn = "global::Disruptor.Surface.Runtime.ISurrealTransport";
    private const string CtFqn = "global::System.Threading.CancellationToken";
    private const string TaskFqn = "global::System.Threading.Tasks.Task";
    private const string ListFqn = "global::System.Collections.Generic.List";
    private const string ReadOnlyListFqn = "global::System.Collections.Generic.IReadOnlyList";
    private const string ResultSetFqn = "global::Disruptor.Surface.Runtime.SurrealResultSet";
    private const string HydrationJsonFqn = "global::Disruptor.Surface.Runtime.HydrationJson";
    private const string JsonValueKindFqn = "global::System.Text.Json.JsonValueKind";

    public static void Emit(SourceProductionContext spc, TableModel table)
    {
        var entityFqn = string.IsNullOrEmpty(table.Namespace)
            ? $"global::{table.Name}"
            : $"global::{table.Namespace}.{table.Name}";
        var idFqn = $"{entityFqn}Id";
        var className = $"{table.Name}QueryIds";

        var sb = new StringBuilder()
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(table.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(table.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        var indent = hasNamespace ? "    " : string.Empty;
        var memberIndent = $"{indent}    ";
        var bodyIndent = $"{memberIndent}    ";

        sb.Append(indent)
          .AppendLine($"/// <summary>Id-only selection terminal for <see cref=\"{table.Name}\"/>. Compiles to <c>SELECT id FROM …</c> and returns a typed list of <c>{table.Name}Id</c>; no entity hydration, no session.</summary>");
        sb.Append(indent).Append("public static class ").AppendLine(className);
        sb.Append(indent).AppendLine("{");

        sb.Append(memberIndent)
          .AppendLine($"/// <summary>Compile and execute the query as <c>SELECT id FROM {SurrealNaming.ToTableName(table.Name)} …</c> and project each returned id into <c>{table.Name}Id</c>. Throws <see cref=\"global::System.InvalidOperationException\"/> if the query carries any <c>Include*</c> nodes — id-only selection is flat by definition.</summary>");
        sb.Append(memberIndent)
          .Append("public static async ").Append(TaskFqn).Append('<').Append(ReadOnlyListFqn).Append('<').Append(idFqn).Append(">> IdsAsync(this ")
          .Append(QueryFqn).Append('<').Append(entityFqn).Append("> query, ")
          .Append(TransportFqn).Append(" transport, ")
          .Append(CtFqn).AppendLine(" ct = default)");
        sb.Append(memberIndent).AppendLine("{");

        // Include* calls are rejected by Query<T>.CompileIdsOnly itself; the throw
        // surfaces from the runtime so the message stays in one place.
        sb.Append(bodyIndent).AppendLine("var sql = query.CompileIdsOnly();");
        sb.Append(bodyIndent).AppendLine("using var doc = await transport.ExecuteAsync(sql, ct);");
        sb.Append(bodyIndent).Append("var rs = new ").Append(ResultSetFqn).AppendLine("(doc.RootElement);");
        sb.Append(bodyIndent).AppendLine("var rows = rs.ResultAt();");
        sb.AppendLine();

        sb.Append(bodyIndent).Append("var list = new ").Append(ListFqn).Append('<').Append(idFqn).AppendLine(">();");
        sb.Append(bodyIndent).AppendLine("switch (rows.ValueKind)");
        sb.Append(bodyIndent).AppendLine("{");
        sb.Append(bodyIndent).Append("    case ").Append(JsonValueKindFqn).AppendLine(".Array:");
        sb.Append(bodyIndent).AppendLine("        foreach (var row in rows.EnumerateArray())");
        sb.Append(bodyIndent).AppendLine("        {");
        sb.Append(bodyIndent).Append("            if (").Append(HydrationJsonFqn).AppendLine(".TryReadRecordId(row, \"id\", out var rid))");
        sb.Append(bodyIndent).AppendLine("            {");
        sb.Append(bodyIndent).Append("                list.Add(new ").Append(idFqn).AppendLine("(rid.Value));");
        sb.Append(bodyIndent).AppendLine("            }");
        sb.Append(bodyIndent).AppendLine("        }");
        sb.Append(bodyIndent).AppendLine("        break;");
        sb.Append(bodyIndent).Append("    case ").Append(JsonValueKindFqn).AppendLine(".Object:");
        sb.Append(bodyIndent).Append("        if (").Append(HydrationJsonFqn).AppendLine(".TryReadRecordId(rows, \"id\", out var single))");
        sb.Append(bodyIndent).AppendLine("        {");
        sb.Append(bodyIndent).Append("            list.Add(new ").Append(idFqn).AppendLine("(single.Value));");
        sb.Append(bodyIndent).AppendLine("        }");
        sb.Append(bodyIndent).AppendLine("        break;");
        sb.Append(bodyIndent).AppendLine("}");
        sb.Append(bodyIndent).AppendLine("return list;");
        sb.Append(memberIndent).AppendLine("}");

        sb.Append(indent).AppendLine("}");

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        var hint = string.IsNullOrEmpty(table.Namespace)
            ? $"{className}.g.cs"
            : $"{table.Namespace}.{className}.g.cs";
        spc.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
