using System.Text;
using Disruptor.Surface.Generator.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Disruptor.Surface.Generator.Emit;

/// <summary>
/// Emits a <c>LoadAsync</c> extension on <see cref="Query{T}"/> for each
/// <c>[AggregateRoot]</c> table — the unified entry point for write-mode loads. Lives
/// alongside the existing <c>Workspace.Load{Root}Async</c> path
/// (<see cref="CompositionRootEmitter"/>) during the migration period; v1 just delegates
/// to the same <c>{Root}AggregateLoader.PopulateAsync</c> the legacy path uses, so a
/// caller can switch between the two without behavioural drift.
/// <para>
/// Filtered loads (queries with <c>Include*</c> calls present) throw
/// <see cref="NotImplementedException"/> — the compiler-driven traversal-into-session
/// pipeline lands in PR6. Until then, traversal results flow only through
/// <c>Query&lt;T&gt;.ExecuteAsync</c>.
/// </para>
/// <para>
/// Skipped when no <c>[CompositionRoot]</c> is declared (the emitted body needs
/// <c>Workspace.ReferenceRegistry</c>) or no <c>[AggregateRoot]</c> tables exist.
/// </para>
/// </summary>
internal static class LoadEntryEmitter
{
    private const string QueryFqn = "global::Disruptor.Surface.Runtime.Query.Query";
    private const string TransportFqn = "global::Disruptor.Surface.Runtime.ISurrealTransport";
    private const string SessionFqn = "global::Disruptor.Surface.Runtime.SurrealSession";
    private const string LeaseFqn = "global::Disruptor.Surface.Runtime.WriterLease";
    private const string CtFqn = "global::System.Threading.CancellationToken";
    private const string TaskFqn = "global::System.Threading.Tasks.Task";

    public static void Emit(SourceProductionContext spc, ModelGraph graph)
    {
        if (graph.CompositionRoots.Count != 1) return;
        var root = graph.CompositionRoots[0];
        if (!root.IsPartial) return;

        var aggregateRoots = graph.Tables.Where(t => t.IsAggregateRoot).ToList();
        if (aggregateRoots.Count == 0) return;

        foreach (var aggRoot in aggregateRoots)
        {
            EmitOne(spc, root, aggRoot);
        }
    }

    private static void EmitOne(SourceProductionContext spc, CompositionRootModel root, TableModel aggRoot)
    {
        var entityFqn = string.IsNullOrEmpty(aggRoot.Namespace)
            ? $"global::{aggRoot.Name}"
            : $"global::{aggRoot.Namespace}.{aggRoot.Name}";
        var idFqn = $"{entityFqn}Id";
        var loaderFqn = $"global::Disruptor.Surface.Runtime.{aggRoot.Name}AggregateLoader";
        var refRegistryFqn = string.IsNullOrEmpty(root.Namespace)
            ? $"global::{root.Name}.ReferenceRegistry"
            : $"global::{root.Namespace}.{root.Name}.ReferenceRegistry";

        var sb = new StringBuilder()
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(root.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(root.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        var indent = hasNamespace ? "    " : string.Empty;
        var memberIndent = $"{indent}    ";
        var bodyIndent = $"{memberIndent}    ";

        sb.Append(indent)
          .AppendLine($"/// <summary>Write-mode entry on <c>Query&lt;{aggRoot.Name}&gt;</c>. Two paths: with no <c>Include*</c> calls, delegates to the legacy <c>{aggRoot.Name}AggregateLoader.PopulateAsync</c> (matches <c>Workspace.Load{aggRoot.Name}Async</c>); with at least one <c>Include*</c>, the compiler-driven path emits a nested <c>SELECT</c> and hydrates only the user-chosen slice through <see cref=\"global::Disruptor.Surface.Runtime.IHydrationSink\"/>.</summary>");
        sb.Append(indent).Append("public static class ").Append(aggRoot.Name).AppendLine("QueryLoad");
        sb.Append(indent).AppendLine("{");

        sb.Append(memberIndent)
          .AppendLine($"/// <summary>Loads the <c>{aggRoot.Name}</c> aggregate identified by the query's <c>WithId</c> pin. Returns a populated <see cref=\"global::Disruptor.Surface.Runtime.SurrealSession\"/> the caller mutates and commits via <c>session.CommitAsync(transport, lease)</c>. The supplied <paramref name=\"lease\"/> is the same writer-lease handle the caller will pass into commit; LoadAsync stores no reference, so the caller stays responsible for its lifetime.</summary>");
        sb.Append(memberIndent)
          .Append("public static async ").Append(TaskFqn).Append('<').Append(SessionFqn)
          .Append("> LoadAsync(this ").Append(QueryFqn).Append('<').Append(entityFqn).Append("> query, ")
          .Append(TransportFqn).Append(" transport, ")
          .Append(LeaseFqn).Append(" lease, ")
          .Append(CtFqn).AppendLine(" ct = default)");
        sb.Append(memberIndent).AppendLine("{");

        // PinnedId is required regardless of which path we take — load mode is single-
        // aggregate-rooted, and both the legacy aggregate loader and the compiler-driven
        // path key the SurrealQL on the root id (`FROM {table}:{id}` and `WHERE id = $p0`
        // respectively). Multi-aggregate atomic load is out of scope.
        sb.Append(bodyIndent).AppendLine("if (query.PinnedId is null)");
        sb.Append(bodyIndent).AppendLine("{");
        sb.Append(bodyIndent).AppendLine("    throw new global::System.InvalidOperationException(");
        sb.Append(bodyIndent).Append("        \"LoadAsync requires a pinned root id. Call .WithId(").Append(aggRoot.Name).AppendLine("Id) before .LoadAsync(...).\");");
        sb.Append(bodyIndent).AppendLine("}");
        sb.AppendLine();

        sb.Append(bodyIndent).Append("var session = new ").Append(SessionFqn).Append('(').Append(refRegistryFqn).AppendLine(");");
        sb.AppendLine();

        // Two-path body: with Includes, the new compiler-driven path emits its own
        // nested SELECT and hydrates the user-chosen slice via IHydrationSink. Without
        // Includes, delegate to the legacy aggregate loader for the full-aggregate
        // load. Both produce the same SurrealSession shape; only the slice differs.
        sb.Append(bodyIndent).AppendLine("if (query.Includes.Count > 0)");
        sb.Append(bodyIndent).AppendLine("{");
        sb.Append(bodyIndent).AppendLine("    await query.ExecuteIntoSessionAsync(session, transport, ct);");
        sb.Append(bodyIndent).AppendLine("}");
        sb.Append(bodyIndent).AppendLine("else");
        sb.Append(bodyIndent).AppendLine("{");
        // Reconstruct the typed id from the canonical RecordId. RecordIdFormat.Validate
        // already accepted the value when the user constructed their {Root}Id; passing
        // the same string back through the typed ctor is a round-trip with no surprises.
        sb.Append(bodyIndent).Append("    var rootId = new ").Append(idFqn).AppendLine("(query.PinnedId.Value.Value);");
        sb.Append(bodyIndent).Append("    await ").Append(loaderFqn).AppendLine(".PopulateAsync(session, transport, rootId, ct);");
        sb.Append(bodyIndent).AppendLine("}");
        sb.AppendLine();

        // Lease is taken in the signature to enforce the "this is write-mode" contract.
        // v1 doesn't store it; the caller passes the same handle into CommitAsync. Touch
        // the lease object so the C# compiler doesn't warn about an unused parameter.
        sb.Append(bodyIndent).AppendLine("_ = lease;");
        sb.Append(bodyIndent).AppendLine("return session;");
        sb.Append(memberIndent).AppendLine("}");

        sb.Append(indent).AppendLine("}");

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        var hint = $"{root.FullName}.{aggRoot.Name}QueryLoad.g.cs";
        spc.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
