using System.Text;
using Disruptor.Surface.Generator.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Disruptor.Surface.Generator.Emit;

/// <summary>
/// Emits the implementing half of every partial property and method on a <c>[Table]</c>
/// class. Property setters are pure backing-field assignments — no Session interaction,
/// no per-field dirty tracking. Save reads the entity's current state at dispatch time.
/// <list type="bullet">
///   <item>[Id] — lazy-cached field; defaults to <c>{Name}Id.New()</c> on first access.</item>
///   <item>[Property] — getter-only or get/set partial property; setter writes the
///         backing field, nothing else.</item>
///   <item>[Reference] — sync property over <c>_{name}</c> entity ref + <c>_{name}Id</c>
///         record id backing fields. Getter falls back to <c>Session.Get&lt;T&gt;(_id)</c>
///         when the entity ref isn't locally cached (covers "loaded as id only" + "user
///         loaded other aggregate separately"). Mandatory get-only references emit an
///         <c>OnCreate{Name}</c> partial hook plus an entry in <c>IEntity.Initialize</c>
///         that mints + assigns directly.</item>
///   <item>[Parent] — sync property; same shape as Reference, plus the setter cascade-
///         tracks the child into the parent's session via
///         <c>parent.Session.AdoptIfUnbound(this)</c> so <c>parent.Children</c> sees the
///         new child at Save time.</item>
///   <item>[Children] — sync getter-only partial property over
///         <c>Session.QueryChildren</c>.</item>
///   <item>Forward/inverse relation property — sync collection from
///         <c>Session.QueryOutgoing</c> / <c>QueryIncoming</c> for same-aggregate edges,
///         or <c>QueryRelatedIds</c> / <c>QueryInverseRelatedIds</c> for cross-aggregate
///         edges. Relation writes go through <c>Session.Relate</c> (sync, in-memory) or
///         <c>Session.RelateAsync</c> (direct dispatch).</item>
/// </list>
/// </summary>
internal static class PartialEmitter
{
    private const string SessionType = "global::Disruptor.Surface.Runtime.SurrealSession";
    private const string EntityInterface = "global::Disruptor.Surface.Runtime.IEntity";
    private const string HydrationSinkType = "global::Disruptor.Surface.Runtime.IHydrationSink";

    /// <summary>
    /// True when <paramref name="t"/> is one of the recognised element-collection shapes
    /// for a <c>[Property]</c> column: <c>IReadOnlyList&lt;T&gt;</c>, <c>IList&lt;T&gt;</c>,
    /// or <c>List&lt;T&gt;</c>. Detection mirrors <c>TableExtractor.ResolveInlineMembers</c>.
    /// </summary>
    private static bool IsElementCollection(TypeRef t) =>
        t.MetadataName is "System.Collections.Generic.IReadOnlyList`1"
                       or "System.Collections.Generic.IList`1"
                       or "System.Collections.Generic.List`1";

    public static void Emit(SourceProductionContext spc, TableModel table, ModelGraph graph)
    {
        if (!table.IsPartial)
        {
            return;
        }

        // Empty annotated tables are legal — the id anchor is always emitted, so a
        // [Table] with no partial members still gets IEntity scaffolding (Bind, Initialize,
        // Hydrate, OnDeleting) and is fully Track-able / Load-able. Just an entity that
        // carries nothing but its identity.
        var partialProps = table.Properties.Where(p => p.IsPartial).ToArray();

        var builder = new StringBuilder()
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(table.Namespace);
        if (hasNamespace)
        {
            builder
                .Append("namespace ")
                .Append(table.Namespace)
                .AppendLine()
                .AppendLine("{");
        }

        var indent = hasNamespace ? "    " : string.Empty;

        builder
            .Append(indent)
            .Append(FormatAccessibility(table.DeclaredAccessibility))
            .Append(' ');
        if (table.IsAbstract)
        {
            builder.Append("abstract ");
        }

        if (table.IsSealed)
        {
            builder.Append("sealed ");
        }

        builder
            .Append("partial class ")
            .Append(table.Name);
        if (table.TypeParameters.Count > 0)
        {
            builder
                .Append('<')
                .Append(string.Join(", ", table.TypeParameters))
                .Append('>');
        }

        builder
            .Append(" : ")
            .Append(EntityInterface);
        foreach (var union in graph.UnionsForTable(table.FullName))
        {
            builder
                .Append(", global::")
                .Append(union.InterfaceFullName);
        }
        builder
            .AppendLine()
            .Append(indent)
            .AppendLine("{");

        var memberIndent = $"{indent}    ";

        WriteSessionPlumbing(builder, memberIndent);

        // The id anchor is emitted unconditionally — the runtime needs IEntity.Id to read
        // every entity's identity, and the typed {Name}Id struct is always emitted by
        // IdEmitter regardless of whether the user opted into a public-facing [Id] property.
        EmitIdAnchor(builder, memberIndent, table);

        var mandatoryRefs = new List<PropertyModel>();
        PropertyModel? parentProp = null;

        foreach (var t in partialProps)
        {
            builder.AppendLine();
            EmitProperty(builder, memberIndent, t, graph);

            if (IsMandatoryReference(t))
            {
                mandatoryRefs.Add(t);
            }
            if (t.Kinds.HasFlag(PropertyKind.Parent))
            {
                parentProp = t;
            }
        }

        // Initialize hook always emitted, even when empty — IEntity demands it and a
        // no-op for entities without mandatory refs is the cleanest path.
        builder.AppendLine();
        EmitInitialize(builder, memberIndent, mandatoryRefs);

        // Hydrate hook — invoked by the per-aggregate loader on each loaded row.
        builder.AppendLine();
        EmitHydrate(builder, memberIndent, table);

        // OnDeleting hook — invoked by Session.DeleteAsync(IEntity) before the entity's
        // own DELETE is dispatched. User can implement the simple-form partial method to
        // queue child deletes / clears.
        builder.AppendLine();
        EmitOnDeleting(builder, memberIndent);

        // MarkAllSlicesLoaded — used by the legacy aggregate loader (after Hydrate) and by
        // SurrealSession.Track<T> (fresh-entity path) to declare every slice on this entity
        // is "loaded". The compiler-driven path marks slices selectively via the include
        // AST instead.
        builder.AppendLine();
        EmitMarkAllSlicesLoaded(builder, memberIndent, table);

        // GetParentId — emitted iff the entity has a [Parent] property. Default-interface
        // returns null for tables without a parent. Used by SurrealSession.QueryChildren
        // to match a child against its parent owner.
        if (parentProp is not null)
        {
            builder.AppendLine();
            EmitGetParentId(builder, memberIndent, parentProp);
        }

        // SaveAsync — generator-emitted per-entity Save dispatch. Walks forward dependencies
        // (Reference / Parent) via backing fields, dispatches CREATE/UPDATE-with-CONTENT,
        // recurses into new children, dispatches new outgoing relations.
        builder.AppendLine();
        EmitSaveAsync(builder, memberIndent, table);

        builder
            .Append(indent)
            .AppendLine("}");

        if (hasNamespace)
        {
            builder.AppendLine("}");
        }

        spc.AddSource(table.FileHintName, SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    // ──────────────────────────── per-table preamble ─────────────────────────

    /// <summary>
    /// Emits per-entity session plumbing: a private <c>_session</c> field, the explicit
    /// <c>IEntity.Session</c> getter (nullable), <c>IEntity.Bind</c> (one-shot setter for
    /// <c>_session</c>), the protected <c>Session</c> property for entity-body reads
    /// (throws when unbound — reading from an unbound entity is a programmer error), and
    /// the <c>__EnsureSliceLoaded</c> guard the navigable read paths use to enforce
    /// strict-with-escape.
    /// </summary>
    private static void WriteSessionPlumbing(StringBuilder builder, string indent)
    {
        builder
            .Append(indent)
            .Append("private ")
            .Append(SessionType)
            .AppendLine("? _session;")
            .AppendLine();

        builder
            .Append(indent)
            .Append(SessionType)
            .Append("? ")
            .Append(EntityInterface)
            .AppendLine(".Session => _session;")
            .AppendLine()
            .Append(indent)
            .Append("void ")
            .Append(EntityInterface)
            .Append(".Bind(")
            .Append(SessionType)
            .AppendLine(" session)")
            .Append(indent).AppendLine("{")
            .Append(indent).AppendLine("    if (_session is not null && !global::System.Object.ReferenceEquals(_session, session))")
            .Append(indent).AppendLine("        throw new global::System.InvalidOperationException(\"Entity is already bound to a different session.\");")
            .Append(indent).AppendLine("    _session = session;")
            .Append(indent).AppendLine("}")
            .AppendLine();

        builder
            .Append(indent)
            .Append("protected ")
            .Append(SessionType)
            .AppendLine(" Session")
            .Append(indent)
            .AppendLine("    => _session ?? throw new global::System.InvalidOperationException(\"Entity is not bound to a session — call session.Track(...) or hydrate via Sessions.Load*Async first.\");")
            .AppendLine()
            // Slice guard — called by every navigable read path before walking the in-memory
            // cache. Reuses the protected Session accessor so unbound entities still get the
            // existing "not tracked" error; once bound, the slice check throws
            // LoadShapeViolationException with a hint at FetchAsync.
            .Append(indent)
            .AppendLine("private void __EnsureSliceLoaded(string sliceKey, string fetchHint)")
            .Append(indent).AppendLine("{")
            .Append(indent).Append("    var __id = ((").Append(EntityInterface).AppendLine(")this).Id;")
            .Append(indent).AppendLine("    if (!Session.IsSliceLoaded(__id, sliceKey))")
            .Append(indent).AppendLine("        throw new global::Disruptor.Surface.Runtime.LoadShapeViolationException(__id, sliceKey, fetchHint);")
            .Append(indent).AppendLine("}");
    }

    // ──────────────────────────── property emission ──────────────────────────

    private static void EmitProperty(StringBuilder builder, string indent, PropertyModel p, ModelGraph graph)
    {
        if (p.RelationRole is RelationRole.ForwardRelation or RelationRole.InverseRelation)
        {
            EmitRelationProperty(builder, indent, p, graph);
            return;
        }

        if (p.Kinds.HasFlag(PropertyKind.Id))
        {
            EmitIdProperty(builder, indent, p);
        }
        else if (p.Kinds.HasFlag(PropertyKind.Property))
        {
            EmitPropertyMember(builder, indent, p);
        }
        else if (p.Kinds.HasFlag(PropertyKind.Parent))
        {
            EmitParentProperty(builder, indent, p);
        }
        else if (p.Kinds.HasFlag(PropertyKind.Children))
        {
            EmitChildrenProperty(builder, indent, p);
        }
        else if (p.Kinds.HasFlag(PropertyKind.Reference))
        {
            EmitReferenceProperty(builder, indent, p);
        }
        else
        {
            EmitFallbackProperty(builder, indent, p);
        }
    }

    /// <summary>
    /// <c>[Property]</c> on a property declaration: element-collection columns
    /// (<c>IReadOnlyList&lt;T&gt;</c> / <c>IList&lt;T&gt;</c> / <c>List&lt;T&gt;</c>) go
    /// through <see cref="EmitElementCollectionProperty"/> (backing <c>List&lt;T&gt;</c>
    /// + Add/Remove/Clear helpers); plain scalars go through
    /// <see cref="EmitDataProperty"/> (pure backing field).
    /// </summary>
    private static void EmitPropertyMember(StringBuilder builder, string indent, PropertyModel p)
    {
        if (IsElementCollection(p.Type))
        {
            EmitElementCollectionProperty(builder, indent, p);
        }
        else
        {
            EmitDataProperty(builder, indent, p);
        }
    }

    /// <summary>
    /// Emits the backing <c>List&lt;T&gt;</c> field plus the partial property surface and
    /// generator-emitted Add/Remove/Clear helpers for an element-collection column.
    /// The user-facing property is exposed exactly as declared
    /// (<c>IReadOnlyList&lt;T&gt;</c>, <c>IList&lt;T&gt;</c>, or <c>List&lt;T&gt;</c>);
    /// the helpers mirror IList semantics regardless so the user has a uniform mutation
    /// surface even when the property is read-only.
    /// </summary>
    private static void EmitElementCollectionProperty(StringBuilder builder, string indent, PropertyModel p)
    {
        var declaredType = p.Type.FullyQualifiedName;
        var elementType = p.Type.TypeArguments.Count > 0
            ? p.Type.TypeArguments[0].FullyQualifiedName
            : "object";
        var listType = $"global::System.Collections.Generic.List<{elementType}>";
        var access = FormatAccessibility(p.DeclaredAccessibility);
        var backing = $"_{ToCamel(p.Name)}";
        var singular = SurrealNaming.Singularize(p.Name);

        builder
            .Append(indent)
            .Append("private readonly ").Append(listType).Append(' ').Append(backing).AppendLine(" = new();")
            .Append(indent)
            .Append(access).Append(" partial ").Append(declaredType).Append(' ').Append(p.Name)
            .Append(" => ").Append(backing).AppendLine(";")
            .Append(indent)
            .Append("/// <summary>Append a <typeparamref name=\"T\"/> to <see cref=\"").Append(p.Name).AppendLine("\"/>.</summary>")
            .Append(indent)
            .Append("public void Add").Append(singular).Append('(').Append(elementType).Append(" item) => ").Append(backing).AppendLine(".Add(item);")
            .Append(indent)
            .Append("/// <summary>Remove the first matching <typeparamref name=\"T\"/> from <see cref=\"").Append(p.Name).AppendLine("\"/>; returns true on a hit.</summary>")
            .Append(indent)
            .Append("public bool Remove").Append(singular).Append('(').Append(elementType).Append(" item) => ").Append(backing).AppendLine(".Remove(item);")
            .Append(indent)
            .Append("/// <summary>Empty <see cref=\"").Append(p.Name).AppendLine("\"/>.</summary>")
            .Append(indent)
            .Append("public void Clear").Append(p.Name).Append("() => ").Append(backing).AppendLine(".Clear();");
    }

    /// <summary>
    /// Emits the always-present id anchor: the private <c>_id</c> backing field plus the
    /// explicit <c>IEntity.Id</c> accessor. Both lazy-mint via <c>{Name}Id.New()</c> on
    /// first read; <c>Hydrate</c> writes the field directly when loading from the DB.
    /// The user's optional <c>[Id]</c>-tagged partial property (if declared) is emitted
    /// separately by <see cref="EmitIdProperty"/> as a delegate to this anchor.
    /// </summary>
    private static void EmitIdAnchor(StringBuilder builder, string indent, TableModel table)
    {
        var idType = $"global::{(string.IsNullOrEmpty(table.Namespace) ? table.Name : $"{table.Namespace}.{table.Name}")}Id";
        builder
            .AppendLine()
            .Append(indent)
            .Append("private ")
            .Append(idType)
            .AppendLine("? _id;")
            .Append(indent)
            .Append("global::Disruptor.Surface.Runtime.RecordId ")
            .Append(EntityInterface)
            .Append(".Id => _id ??= ")
            .Append(idType)
            .AppendLine(".New();");
    }

    /// <summary>
    /// Emits the user-facing <c>[Id]</c> partial property — a get/set delegate to the
    /// id anchor. Only called when the user has declared an <c>[Id]</c>-tagged partial
    /// property; without one, the entity simply has no public-facing Id surface (the
    /// anchor still exists internally).
    /// <para>
    /// The setter (when declared) refuses to mutate the anchor once the entity is bound
    /// to a session — by that point the entity lives in the session's identity map keyed
    /// on the current id, and silently overwriting it would corrupt every dict.
    /// </para>
    /// </summary>
    private static void EmitIdProperty(StringBuilder builder, string indent, PropertyModel p)
    {
        var idType = p.Type.FullyQualifiedName;
        var idArg = StripNullable(idType);
        var access = FormatAccessibility(p.DeclaredAccessibility);

        builder
            .Append(indent)
            .Append(access)
            .Append(" partial ")
            .Append(idType)
            .Append(' ')
            .AppendLine(p.Name)
            .Append(indent)
            .AppendLine("{")
            .Append(indent)
            .Append("    get => _id ??= ")
            .Append(idArg)
            .AppendLine(".New();");
        if (p.HasSetter)
        {
            builder
                .Append(indent)
                .AppendLine("    set")
                .Append(indent)
                .AppendLine("    {")
                .Append(indent)
                .AppendLine("        if (_session is not null)")
                .Append(indent)
                .AppendLine("            throw new global::System.InvalidOperationException(\"Cannot mutate Id after the entity is bound to a session.\");")
                .Append(indent)
                .AppendLine("        _id = value;")
                .Append(indent)
                .AppendLine("    }");
        }
        builder
            .Append(indent)
            .AppendLine("}");
    }

    /// <summary>
    /// Pure backing-field property: <c>get => _name; set => _name = value;</c>. No
    /// Session call, no buffer, no command log entry. Save reads the backing field at
    /// dispatch time.
    /// </summary>
    private static void EmitDataProperty(StringBuilder builder, string indent, PropertyModel p)
    {
        var type = p.Type.FullyQualifiedName;
        var access = FormatAccessibility(p.DeclaredAccessibility);
        var backing = $"_{ToCamel(p.Name)}";

        // = default! silences CS8618 for non-nullable types; CS0649 covers the case where
        // the user declares no setter (read-only [Property] is legal). Reading before any
        // setter runs returns the type's default — the schema's DEFAULT clause is the
        // contract for what the database hands back, not something we synthesise.
        builder
            .Append(indent)
            .AppendLine("#pragma warning disable CS0649")
            .Append(indent)
            .Append("private ")
            .Append(type)
            .Append(' ')
            .Append(backing)
            .AppendLine(" = default!;")
            .Append(indent)
            .AppendLine("#pragma warning restore CS0649");

        if (!p.HasSetter && !p.HasInitOnlySetter)
        {
            builder.Append(indent)
                .Append(access)
                .Append(" partial ")
                .Append(type)
                .Append(' ')
                .Append(p.Name)
                .Append(" => ")
                .Append(backing)
                .AppendLine(";");
            return;
        }

        builder
            .Append(indent)
            .Append(access)
            .Append(" partial ")
            .Append(type)
            .Append(' ')
            .AppendLine(p.Name)
            .Append(indent)
            .AppendLine("{")
            .Append(indent).Append("    get => ").Append(backing).AppendLine(";")
            .Append(indent).Append("    ").Append(p.HasInitOnlySetter ? "init" : "set").Append(" => ").Append(backing).AppendLine(" = value;")
            .Append(indent)
            .AppendLine("}");
    }

    /// <summary>
    /// Sync property body for <c>[Parent]</c>:
    /// <list type="bullet">
    ///   <item>Two backing fields: <c>_{name}</c> caches the parent entity ref;
    ///         <c>_{name}Id</c> caches the parent's record id.</item>
    ///   <item>Getter: returns <c>_{name}</c> if cached; otherwise falls back to
    ///         <c>Session?.Get&lt;TParent&gt;(_{name}Id)</c> when an id is known.</item>
    ///   <item>Setter: stores both backing fields; if the assigned parent has a session
    ///         and <c>this</c> is unbound, calls
    ///         <c>parent.Session.AdoptIfUnbound(this)</c> so this entity joins the
    ///         parent's session — that's how a freshly constructed
    ///         <c>new Constraint { Design = design }</c> shows up in
    ///         <c>design.Constraints</c> when Save walks children.</item>
    /// </list>
    /// </summary>
    private static void EmitParentProperty(StringBuilder builder, string indent, PropertyModel p)
    {
        var declared = p.Type.FullyQualifiedName;
        var typeArg = StripNullable(declared);
        var access = FormatAccessibility(p.DeclaredAccessibility);
        var nullable = p.Type.IsNullable;
        var sliceKey = SurrealNaming.ToFieldName(p.Name);
        var sliceKeyLit = Quote(sliceKey);
        var fetchHintLit = Quote($".Include{p.Name}() on the parent query");
        var backing = $"_{ToCamel(p.Name)}";
        var idBacking = $"_{ToCamel(p.Name)}Id";

        builder
            .Append(indent).Append("private ").Append(typeArg).Append("? ").Append(backing).AppendLine(";")
            .Append(indent).Append("private global::Disruptor.Surface.Runtime.RecordId? ").Append(idBacking).AppendLine(";")
            .Append(indent)
            .Append(access)
            .Append(" partial ")
            .Append(declared)
            .Append(' ')
            .AppendLine(p.Name)
            .Append(indent)
            .AppendLine("{");

        if (nullable)
        {
            builder
                .Append(indent).AppendLine("    get")
                .Append(indent).AppendLine("    {")
                .Append(indent).Append("        __EnsureSliceLoaded(").Append(sliceKeyLit).Append(", ").Append(fetchHintLit).AppendLine(");")
                .Append(indent).Append("        return ").Append(backing).Append(" ?? (").Append(idBacking)
                    .Append(" is { } __id ? _session?.Get<").Append(typeArg).AppendLine(">(__id) : null);")
                .Append(indent).AppendLine("    }");
        }
        else
        {
            // Non-nullable [Parent]: a parent should always exist for a tracked child.
            // Throw if neither the entity ref nor the id is set, mirroring the mandatory
            // [Reference] shape.
            builder
                .Append(indent).AppendLine("    get")
                .Append(indent).AppendLine("    {")
                .Append(indent).Append("        __EnsureSliceLoaded(").Append(sliceKeyLit).Append(", ").Append(fetchHintLit).AppendLine(");")
                .Append(indent).Append("        var __resolved = ").Append(backing).Append(" ?? (").Append(idBacking)
                    .Append(" is { } __id ? _session?.Get<").Append(typeArg).AppendLine(">(__id) : null);")
                .Append(indent).Append("        return __resolved ?? throw new global::System.InvalidOperationException(\"Parent '")
                    .Append(p.Name).AppendLine("' is not set.\");")
                .Append(indent).AppendLine("    }");
        }

        if (p.HasSetter || p.HasInitOnlySetter)
        {
            builder
                .Append(indent).Append("    ").AppendLine(p.HasInitOnlySetter ? "init" : "set")
                .Append(indent).AppendLine("    {")
                .Append(indent).Append("        ").Append(backing).AppendLine(" = value;")
                .Append(indent).Append("        ").Append(idBacking).AppendLine(nullable
                    ? $" = value is null ? null : (({EntityInterface})value).Id;"
                    : $" = (({EntityInterface})value).Id;")
                // Cascade-track: assigning a parent that's bound to a session should pull
                // this child into that session, so the parent's [Children] sees it at Save
                // time. AdoptIfUnbound is a no-op when this entity already has a session.
                // IEntity.Session is the explicit-impl public accessor; the parent's own
                // `protected Session` would be inaccessible from this site.
                .Append(indent).AppendLine($"        if (value is not null && (({EntityInterface})value).Session is {{ }} __ps) __ps.AdoptIfUnbound(this);")
                .Append(indent).AppendLine("    }");
        }

        builder.Append(indent).AppendLine("}");
    }

    private static void EmitChildrenProperty(StringBuilder builder, string indent, PropertyModel p)
    {
        var declared = p.Type.FullyQualifiedName;
        var element = p.Type.ElementType ?? p.Type;
        var (elementTypeArg, elementNameExpr) = ResolveElement(element);
        var access = FormatAccessibility(p.DeclaredAccessibility);
        var sliceKey = SurrealNaming.ToFieldName(p.Name);
        var sliceKeyLit = Quote(sliceKey);
        var fetchHintLit = Quote($".Include{p.Name}(...) on the parent query");

        builder
            .Append(indent)
            .Append(access)
            .Append(" partial ")
            .Append(declared)
            .Append(' ')
            .AppendLine(p.Name)
            .Append(indent).AppendLine("{")
            .Append(indent).AppendLine("    get")
            .Append(indent).AppendLine("    {")
            .Append(indent).Append("        __EnsureSliceLoaded(").Append(sliceKeyLit).Append(", ").Append(fetchHintLit).AppendLine(");")
            .Append(indent).Append("        return Session.QueryChildren<")
            .Append(elementTypeArg).Append(">(this, ").Append(elementNameExpr).AppendLine(");")
            .Append(indent).AppendLine("    }")
            .Append(indent).AppendLine("}");
    }

    /// <summary>
    /// Sync property body for <c>[Reference]</c>:
    /// <list type="bullet">
    ///   <item>Two backing fields: <c>_{name}</c> caches the reference target entity;
    ///         <c>_{name}Id</c> caches its record id.</item>
    ///   <item>Mandatory get-only (non-nullable): getter returns <c>_{name}</c> directly,
    ///         throwing if it isn't set. <c>Initialize</c> mints the target via the
    ///         <c>OnCreate{Name}</c> hook for fresh-construct entities; loaders set it
    ///         via inline expansion (<c>field.*</c>).</item>
    ///   <item>Optional with set/init: setter stores both backing fields. Getter falls
    ///         back to <c>Session?.Get&lt;T&gt;(_{name}Id)</c> when the entity ref isn't
    ///         locally cached (covers "loaded as id only" + "user later loaded other
    ///         aggregate separately and the entity is now in the identity map").</item>
    /// </list>
    /// </summary>
    private static void EmitReferenceProperty(StringBuilder builder, string indent, PropertyModel p)
    {
        var declared = p.Type.FullyQualifiedName;
        var typeArg = StripNullable(declared);
        var access = FormatAccessibility(p.DeclaredAccessibility);
        var sliceKey = SurrealNaming.ToFieldName(p.Name);
        var sliceKeyLit = Quote(sliceKey);
        var fetchHintLit = Quote($".Include{p.Name}() on the parent query");
        var nullable = p.Type.IsNullable;
        var backing = $"_{ToCamel(p.Name)}";
        var idBacking = $"_{ToCamel(p.Name)}Id";

        builder
            .Append(indent).Append("private ").Append(typeArg).Append("? ").Append(backing).AppendLine(";")
            .Append(indent).Append("private global::Disruptor.Surface.Runtime.RecordId? ").Append(idBacking).AppendLine(";")
            .Append(indent)
            .Append(access)
            .Append(" partial ")
            .Append(declared)
            .Append(' ')
            .AppendLine(p.Name)
            .Append(indent)
            .AppendLine("{");

        // Getter
        if (!nullable)
        {
            // Mandatory: throw if neither the entity ref nor the id is set; otherwise
            // resolve. Initialize mints + sets _{name}; inline loaders set both fields.
            builder
                .Append(indent).AppendLine("    get")
                .Append(indent).AppendLine("    {")
                .Append(indent).Append("        __EnsureSliceLoaded(").Append(sliceKeyLit).Append(", ").Append(fetchHintLit).AppendLine(");")
                .Append(indent).Append("        var __resolved = ").Append(backing).Append(" ?? (").Append(idBacking)
                    .Append(" is { } __id ? _session?.Get<").Append(typeArg).AppendLine(">(__id) : null);")
                .Append(indent).Append("        return __resolved ?? throw new global::System.InvalidOperationException(\"Mandatory reference '")
                    .Append(p.Name).AppendLine("' is not set.\");")
                .Append(indent).AppendLine("    }");
        }
        else
        {
            builder
                .Append(indent).AppendLine("    get")
                .Append(indent).AppendLine("    {")
                .Append(indent).Append("        __EnsureSliceLoaded(").Append(sliceKeyLit).Append(", ").Append(fetchHintLit).AppendLine(");")
                .Append(indent).Append("        return ").Append(backing).Append(" ?? (").Append(idBacking)
                    .Append(" is { } __id ? _session?.Get<").Append(typeArg).AppendLine(">(__id) : null);")
                .Append(indent).AppendLine("    }");
        }

        if (p.HasSetter || p.HasInitOnlySetter)
        {
            builder
                .Append(indent).Append("    ").AppendLine(p.HasInitOnlySetter ? "init" : "set")
                .Append(indent).AppendLine("    {")
                .Append(indent).Append("        ").Append(backing).AppendLine(" = value;")
                .Append(indent).Append("        ").Append(idBacking).AppendLine(nullable
                    ? $" = value is null ? null : (({EntityInterface})value).Id;"
                    : $" = (({EntityInterface})value).Id;")
                .Append(indent).AppendLine("    }");
        }

        builder.Append(indent).AppendLine("}");
    }

    /// <summary>
    /// A getter-only collection property carrying a forward/inverse relation attribute
    /// maps to either:
    /// <list type="bullet">
    ///   <item>Within-aggregate → <c>Session.QueryOutgoing&lt;TKind, TElement&gt;(this)</c>
    ///         on the forward side, <c>Session.QueryIncoming&lt;TKind, TElement&gt;(this)</c>
    ///         on the inverse side. Direction is explicit so same-table relations and
    ///         overlapping role types don't accidentally read both endpoints.</item>
    ///   <item>Cross-aggregate → <c>Session.QueryRelatedIds&lt;TKind&gt;(this)</c> on the
    ///         forward side / <c>Session.QueryInverseRelatedIds&lt;TKind&gt;(this)</c> on
    ///         the inverse side (id-typed, since target/source entities live in a
    ///         different aggregate snapshot).</item>
    /// </list>
    /// </summary>
    private static void EmitRelationProperty(StringBuilder builder, string indent, PropertyModel p, ModelGraph graph)
    {
        var declared = p.Type.FullyQualifiedName;
        var access = FormatAccessibility(p.DeclaredAccessibility);
        var kindMarker = ResolveKindMarkerFqn(p.RelationKindFullName, graph);

        var forwardKindFullName = ForwardKindFullNameFor(p.RelationKindFullName, p.RelationRole, graph);
        var crossAggregate = forwardKindFullName is not null && graph.IsCrossAggregate(forwardKindFullName);
        var sliceKey = SurrealNaming.ToFieldName(p.Name);
        var sliceKeyLit = Quote(sliceKey);
        var fetchHintLit = Quote($"a Workspace.Query.Edges.* query covering {p.Name}");

        if (crossAggregate)
        {
            var method = p.RelationRole == RelationRole.ForwardRelation ? "QueryRelatedIds" : "QueryInverseRelatedIds";
            builder
                .Append(indent)
                .Append(access)
                .Append(" partial ")
                .Append(declared)
                .Append(' ')
                .AppendLine(p.Name)
                .Append(indent).AppendLine("{")
                .Append(indent).AppendLine("    get")
                .Append(indent).AppendLine("    {")
                .Append(indent).Append("        __EnsureSliceLoaded(").Append(sliceKeyLit).Append(", ").Append(fetchHintLit).AppendLine(");")
                .Append(indent).Append("        return Session.").Append(method).Append('<').Append(kindMarker).AppendLine(">(this);")
                .Append(indent).AppendLine("    }")
                .Append(indent).AppendLine("}");
            return;
        }

        var elementType = p.Type.ElementType ?? p.Type;
        var elementArg = elementType.IsTypeParameter
            ? elementType.DisplayName
            : StripNullable(elementType.FullyQualifiedName);

        var directionalMethod = p.RelationRole == RelationRole.ForwardRelation
            ? "QueryOutgoing"
            : "QueryIncoming";

        builder
            .Append(indent)
            .Append(access)
            .Append(" partial ")
            .Append(declared)
            .Append(' ')
            .AppendLine(p.Name)
            .Append(indent).AppendLine("{")
            .Append(indent).AppendLine("    get")
            .Append(indent).AppendLine("    {")
            .Append(indent).Append("        __EnsureSliceLoaded(").Append(sliceKeyLit).Append(", ").Append(fetchHintLit).AppendLine(");")
            .Append(indent).Append("        return Session.").Append(directionalMethod).Append('<')
            .Append(kindMarker).Append(", ").Append(elementArg).AppendLine(">(this);")
            .Append(indent).AppendLine("    }")
            .Append(indent).AppendLine("}");
    }

    /// <summary>
    /// Resolves the FQN of the typed-kind marker class emitted alongside a forward
    /// relation attribute. <paramref name="memberKindFullName"/> may be either side —
    /// inverse kinds resolve to their paired forward's marker.
    /// </summary>
    private static string ResolveKindMarkerFqn(string? memberKindFullName, ModelGraph graph)
    {
        var kind = graph.FindKind(memberKindFullName);
        if (kind is null)
        {
            return "global::Disruptor.Surface.Runtime.IRelationKind";
        }

        var forward = kind.Direction == RelationDirection.Forward
            ? kind
            : graph.FindKind(kind.PairedForwardFullName);
        if (forward is null)
        {
            return "global::Disruptor.Surface.Runtime.IRelationKind";
        }

        var markerName = SurrealNaming.StripAttributeSuffix(forward.Name);
        return string.IsNullOrEmpty(forward.Namespace)
            ? $"global::{markerName}"
            : $"global::{forward.Namespace}.{markerName}";
    }

    /// <summary>
    /// Resolves the forward kind FQN whether the member sits on the forward or inverse
    /// side. Forward-side members carry the forward kind directly; inverse-side members
    /// carry the inverse kind and we walk to the paired forward.
    /// </summary>
    private static string? ForwardKindFullNameFor(string? memberKindFullName, RelationRole role, ModelGraph graph)
    {
        if (memberKindFullName is null)
        {
            return null;
        }

        if (role == RelationRole.ForwardRelation)
        {
            return memberKindFullName;
        }

        var kind = graph.FindKind(memberKindFullName);
        return kind?.PairedForwardFullName;
    }

    private static void EmitFallbackProperty(StringBuilder builder, string indent, PropertyModel p)
    {
        var type = p.Type.FullyQualifiedName;
        var access = FormatAccessibility(p.DeclaredAccessibility);
        builder
            .Append(indent)
            .Append(access)
            .Append(" partial ")
            .Append(type)
            .Append(' ')
            .Append(p.Name)
            .AppendLine(" => throw new global::System.NotImplementedException();");
    }

    private static string ToCamel(string s) =>
        s.Length == 0 ? s : char.ToLowerInvariant(s[0]) + s[1..];

    /// <summary>
    /// Resolves element info for a TypeRef. The <c>NameExpr</c> is the Surreal table-name
    /// string the runtime keys off (lower_snake_case + pluralised). For concrete types we
    /// bake the literal at codegen time; for type parameters we fall back to
    /// <c>typeof(T).Name</c> — only ever hit by generic <c>[Children]</c>, which CG009
    /// rejects, so the unresolved-name path is effectively dead.
    /// </summary>
    private static (string TypeArg, string NameExpr) ResolveElement(TypeRef t)
    {
        if (t.IsTypeParameter)
        {
            return (t.DisplayName, $"typeof({t.DisplayName}).Name");
        }

        var stripped = StripNullable(t.FullyQualifiedName);
        return (stripped, Quote(SurrealNaming.ToTableName(SurrealNaming.SimpleName(stripped))));
    }

    // ──────────────────────────── Initialize emission ────────────────────────

    private static bool IsMandatoryReference(PropertyModel p)
        => p.Kinds.HasFlag(PropertyKind.Reference)
           && !p.Type.IsNullable
           && p.HasGetter
           && !p.HasSetter
           && !p.HasInitOnlySetter;

    /// <summary>
    /// Emits the <c>void IEntity.Initialize(SurrealSession)</c> impl that
    /// <c>Session.Track</c> (and <c>EnsureBoundForSave</c>) invokes. For each mandatory
    /// <c>[Reference]</c> we emit the <c>OnCreate{Name}</c> partial declaration so the
    /// user supplies the seed logic; the body then mints the target, runs the hook, and
    /// assigns it directly into the backing fields. Idempotent — guards each mint with
    /// <c>if (_{name} is null)</c> so re-invocation (Track followed by SaveAsync's
    /// auto-bind) doesn't re-mint already-set references. Entities without mandatory
    /// refs get an empty body.
    /// </summary>
    private static void EmitInitialize(StringBuilder builder, string indent, List<PropertyModel> mandatoryRefs)
    {
        foreach (var p in mandatoryRefs)
        {
            var typeArg = StripNullable(p.Type.FullyQualifiedName);
            // Simple-form partial — no accessibility, no body required. If the user
            // doesn't implement it, the call below is elided at compile time.
            builder
                .Append(indent)
                .Append("partial void OnCreate")
                .Append(p.Name)
                .Append('(')
                .Append(typeArg)
                .AppendLine(" entity);");
        }

        if (mandatoryRefs.Count > 0)
        {
            builder.AppendLine();
        }

        builder
            .Append(indent)
            .Append("void ")
            .Append(EntityInterface)
            .Append(".Initialize(")
            .Append(SessionType)
            .Append(" session)");

        if (mandatoryRefs.Count == 0)
        {
            builder.AppendLine(" { }");
            return;
        }

        builder
            .AppendLine()
            .Append(indent)
            .AppendLine("{");
        foreach (var p in mandatoryRefs)
        {
            var typeArg = StripNullable(p.Type.FullyQualifiedName);
            var backing = $"_{ToCamel(p.Name)}";
            var idBacking = $"_{ToCamel(p.Name)}Id";

            builder
                .Append(indent).Append("    if (").Append(backing).AppendLine(" is null)")
                .Append(indent).AppendLine("    {")
                .Append(indent).Append("        ").Append(backing).Append(" = new ").Append(typeArg).AppendLine("();")
                .Append(indent).Append("        OnCreate").Append(p.Name).Append('(').Append(backing).AppendLine(");")
                .Append(indent).Append("        ").Append(idBacking).Append(" = ((").Append(EntityInterface).Append(')').Append(backing).AppendLine(").Id;")
                .Append(indent).AppendLine("    }");
        }

        builder
            .Append(indent)
            .AppendLine("}");
    }

    // ──────────────────────────── OnDeleting emission ───────────────────────

    /// <summary>
    /// Emits a simple-form <c>partial void OnDeleting()</c> hook the user may optionally
    /// implement to queue dependent-delete / reference-clear commands, plus the explicit
    /// <see>
    ///     <cref>IEntity.OnDeleting</cref>
    /// </see>
    /// impl that the workspace dispatches to. If the
    /// user doesn't implement the partial, the call inside the dispatch is elided at
    /// compile time and Delete just queues the entity's own DELETE command.
    /// </summary>
    private static void EmitOnDeleting(StringBuilder builder, string indent)
    {
        builder
            .Append(indent)
            .AppendLine("partial void OnDeleting();")
            .AppendLine()
            .Append(indent)
            .Append("void ")
            .Append(EntityInterface)
            .AppendLine(".OnDeleting() => OnDeleting();");
    }

    /// <summary>
    /// Emits <c>IEntity.MarkAllSlicesLoaded</c> — one <see cref="IHydrationSink.MarkSliceLoaded"/>
    /// call per navigable slice on this entity. Slice keys are snake-cased C# property names
    /// (matches the keys the read paths look up via <see cref="SurrealSession.IsSliceLoaded"/>).
    /// Skipped: <c>[Id]</c> (the entity itself) and scalar <c>[Property]</c> (always loaded
    /// with the row's <c>*</c> projection — no slice check on the read path).
    /// </summary>
    private static void EmitMarkAllSlicesLoaded(StringBuilder builder, string indent, TableModel table)
    {
        builder
            .Append(indent)
            .Append("void ")
            .Append(EntityInterface)
            .Append(".MarkAllSlicesLoaded(").Append(HydrationSinkType).AppendLine(" sink)")
            .Append(indent).AppendLine("{")
            .Append(indent).AppendLine($"    var __id = (({EntityInterface})this).Id;");

        foreach (var p in table.Properties)
        {
            // Skip [Id] (the entity itself) and scalar [Property] (no slice check).
            if (p.Kinds.HasFlag(PropertyKind.Id)) continue;
            if (p.Kinds.HasFlag(PropertyKind.Property) && p.RelationRole == RelationRole.None) continue;
            // [Parent] / [Reference] / [Children] / forward+inverse relation kinds — all
            // get a slice mark keyed on the snake-cased property name.
            var sliceKey = SurrealNaming.ToFieldName(p.Name);
            builder
                .Append(indent)
                .Append("    sink.MarkSliceLoaded(__id, \"")
                .Append(sliceKey)
                .AppendLine("\");");
        }

        builder.Append(indent).AppendLine("}");
    }

    /// <summary>
    /// Emits <c>RecordId? IEntity.GetParentId()</c> for entities with a <c>[Parent]</c>
    /// property. Returns the parent's record id (if set) or <c>null</c>. Used by
    /// <see cref="SurrealSession.QueryChildren{T}"/> to match a candidate child against
    /// its parent owner. Tables without a <c>[Parent]</c> get the default-interface
    /// no-op return null defined on <c>IEntity</c>.
    /// </summary>
    private static void EmitGetParentId(StringBuilder builder, string indent, PropertyModel parentProp)
    {
        var idBacking = $"_{ToCamel(parentProp.Name)}Id";
        builder
            .Append(indent)
            .Append("global::Disruptor.Surface.Runtime.RecordId? ")
            .Append(EntityInterface)
            .Append(".GetParentId() => ")
            .Append(idBacking)
            .AppendLine(";");
    }

    // ──────────────────────────── SaveAsync emission ────────────────────────

    /// <summary>
    /// Emits <c>IEntity.SaveAsync(ISaveContext, CancellationToken)</c> per <c>[Table]</c>.
    /// Walks forward dependencies (<c>[Reference]</c> / <c>[Parent]</c> targets that
    /// aren't tracked yet → recurse via <c>ctx.SaveAsync</c>); builds a content dict
    /// from <c>[Property]</c> + <c>[Reference]</c> + <c>[Parent]</c> backing fields;
    /// dispatches <c>CREATE</c> or <c>UPDATE</c> via the SDK's typed methods (CBOR, no SurrealQL); recurses
    /// into new children via the <c>[Children]</c> property accessor; dispatches new
    /// outgoing relations via <see cref="SurrealSession.GetNewOutgoingEdges{TKind}"/>.
    /// </summary>
    private static void EmitSaveAsync(StringBuilder builder, string indent, TableModel table)
    {
        builder
            .Append(indent)
            .Append("async global::System.Threading.Tasks.Task ")
            .Append(EntityInterface)
            .AppendLine(".SaveAsync(global::Disruptor.Surface.Runtime.ISaveContext ctx, global::System.Threading.CancellationToken ct)")
            .Append(indent).AppendLine("{");

        builder
            .Append(indent).Append("    var __id = ((").Append(EntityInterface).AppendLine(")this).Id;")
            .Append(indent).AppendLine("    var __isNew = !ctx.IsTracked(__id);")
            .AppendLine();

        // Forward dependency walk: [Reference] + [Parent], skip relation-role properties.
        // Backing fields hold the entity ref directly under the new pure-setter model, so
        // the walk reads `_{name}` (the entity ref) rather than going through Session.
        var hasForwardDeps = false;
        foreach (var p in table.Properties)
        {
            var isFwdDep = (p.Kinds.HasFlag(PropertyKind.Reference) || p.Kinds.HasFlag(PropertyKind.Parent))
                && p.RelationRole == RelationRole.None;
            if (!isFwdDep) continue;
            hasForwardDeps = true;
            var backing = $"_{ToCamel(p.Name)}";
            builder
                .Append(indent).Append("    if (").Append(backing).Append(" is not null && !ctx.IsTracked(((")
                .Append(EntityInterface).Append(')').Append(backing).AppendLine(").Id))")
                .Append(indent).Append("        await ctx.SaveAsync(").Append(backing).AppendLine(", ct);");
        }
        if (hasForwardDeps) builder.AppendLine();

        // Typed CBOR content — SurrealObject built via ContentValue.Set helpers (the
        // mirror of HydrationValue's read side). Each scalar wraps into the right
        // SurrealValue variant; nullable values that are null get omitted so the
        // schema's DEFAULT applies. No SurrealQL string formatting, no JSON, no
        // reflection — pure typed CBOR.
        builder.Append(indent).AppendLine("    var __content = new global::Disruptor.Surreal.Values.SurrealObject();");
        foreach (var p in table.Properties)
        {
            if (p.Kinds.HasFlag(PropertyKind.Id)) continue;
            if (p.Kinds.HasFlag(PropertyKind.Children)) continue;
            if (p.RelationRole != RelationRole.None) continue;

            var fieldLit = Quote(SurrealNaming.ToFieldName(p.Name));

            if (p.Kinds.HasFlag(PropertyKind.Property))
            {
                var backing = $"_{ToCamel(p.Name)}";
                if (IsElementCollection(p.Type) && p.InlineMembers.Count > 0)
                {
                    // Element collection of records — typed per-element SurrealObject
                    // construction; the outer SurrealList wraps as SurrealListValue.
                    var elemLocal = $"__elem_{ToCamel(p.Name)}";
                    var objLocal = $"__obj_{ToCamel(p.Name)}";
                    builder
                        .Append(indent).AppendLine("    {")
                        .Append(indent).Append("        var __list = new global::Disruptor.Surreal.Values.SurrealList(")
                        .Append(backing).AppendLine(".Count);")
                        .Append(indent).Append("        foreach (var ").Append(elemLocal).Append(" in ").Append(backing).AppendLine(")")
                        .Append(indent).AppendLine("        {")
                        .Append(indent).Append("            var ").Append(objLocal).AppendLine(" = new global::Disruptor.Surreal.Values.SurrealObject();");
                    foreach (var im in p.InlineMembers)
                    {
                        var subLit = Quote(SurrealNaming.ToFieldName(im.Name));
                        builder.Append(indent).Append("            global::Disruptor.Surface.Runtime.ContentValue.Set(").Append(objLocal).Append(", ").Append(subLit)
                               .Append(", ").Append(elemLocal).Append('.').Append(im.Name).AppendLine(");");
                    }
                    builder.Append(indent).Append("            __list.Add(new global::Disruptor.Surreal.Values.SurrealObjectValue(").Append(objLocal).AppendLine("));");
                    builder.Append(indent).AppendLine("        }");
                    builder.Append(indent).Append("        __content[").Append(fieldLit).AppendLine("] = new global::Disruptor.Surreal.Values.SurrealListValue(__list);");
                    builder.Append(indent).AppendLine("    }");
                }
                else
                {
                    // Scalar [Property] — typed Set picks the right SurrealValue variant
                    // based on the C# type. Nullable scalars omit null values (schema
                    // DEFAULT applies).
                    builder.Append(indent).Append("    global::Disruptor.Surface.Runtime.ContentValue.Set(__content, ").Append(fieldLit).Append(", ").Append(backing).AppendLine(");");
                }
            }
            else if (p.Kinds.HasFlag(PropertyKind.Reference) || p.Kinds.HasFlag(PropertyKind.Parent))
            {
                // FK rendered from the cached id (or the entity's id if only the entity
                // ref is set — user assigned but Save hasn't yet rebuilt the id). Emits
                // as a typed SurrealRecordIdValue, preserving Thing typing through CBOR.
                var backing = $"_{ToCamel(p.Name)}";
                var idBacking = $"_{ToCamel(p.Name)}Id";
                builder
                    .Append(indent).Append("    global::Disruptor.Surface.Runtime.ContentValue.SetRef(__content, ").Append(fieldLit).Append(", ").Append(idBacking)
                    .Append(" ?? (").Append(backing).Append(" is null ? (global::Disruptor.Surface.Runtime.RecordId?)null : ((")
                    .Append(EntityInterface).Append(')').Append(backing).AppendLine(").Id));");
            }
        }
        builder.AppendLine();

        // Typed CBOR dispatch — SDK methods accept ISurrealRecordId + SurrealObject and
        // CBOR-encode end-to-end. No SurrealQL string, no escape rules.
        builder
            .Append(indent).AppendLine("    if (__isNew)")
            .Append(indent).AppendLine("        await ctx.Transaction.CreateAsync(global::Disruptor.Surface.Runtime.RecordIdSdkBridge.ToSdk(__id), __content, ct);")
            .Append(indent).AppendLine("    else")
            .Append(indent).AppendLine("        await ctx.Transaction.UpsertAsync(global::Disruptor.Surface.Runtime.RecordIdSdkBridge.ToSdk(__id), __content, ct);")
            .AppendLine()
            .Append(indent).AppendLine("    ctx.MarkSaved(this);");

        // Children walk: AFTER self-dispatch (children's [Parent] FK needs this row to
        // exist in the txn before their CREATE lands). For each [Children] collection,
        // iterate via the property accessor; recurse into any not-yet-saved entries.
        foreach (var p in table.Properties)
        {
            if (!p.Kinds.HasFlag(PropertyKind.Children)) continue;
            var elemLocal = $"__child_{ToCamel(p.Name)}";
            builder
                .AppendLine()
                .Append(indent).Append("    foreach (var ").Append(elemLocal).Append(" in this.").Append(p.Name).AppendLine(")")
                .Append(indent).AppendLine("    {")
                .Append(indent).Append("        if (!ctx.IsTracked(((").Append(EntityInterface).Append(')').Append(elemLocal).AppendLine(").Id))")
                .Append(indent).Append("            await ctx.SaveAsync(").Append(elemLocal).AppendLine(", ct);")
                .Append(indent).AppendLine("    }");
        }

        // Outgoing relations dispatch: for each [ForwardRelation]-bearing property, ask
        // the session for new (post-load) outgoing edges of that kind and dispatch a
        // RELATE per new edge — reuses Session.RelateAsync<TKind>'s typed-CBOR path
        // (Idempotent edge id with CBOR-bound endpoints, no string formatting).
        foreach (var p in table.Properties)
        {
            if (p.RelationRole != RelationRole.ForwardRelation) continue;
            if (string.IsNullOrEmpty(p.RelationKindFullName)) continue;
            var attrFqn = p.RelationKindFullName!;
            var lastDot = attrFqn.LastIndexOf('.');
            var attrNs = lastDot >= 0 ? attrFqn[..lastDot] : "";
            var attrName = lastDot >= 0 ? attrFqn[(lastDot + 1)..] : attrFqn;
            var markerName = SurrealNaming.StripAttributeSuffix(attrName);
            var markerFqn = string.IsNullOrEmpty(attrNs) ? $"global::{markerName}" : $"global::{attrNs}.{markerName}";
            var targetLocal = $"__rel_{ToCamel(p.Name)}";
            builder
                .AppendLine()
                .Append(indent).Append("    foreach (var ").Append(targetLocal)
                .Append(" in Session.GetNewOutgoingEdges<").Append(markerFqn).AppendLine(">(this))")
                .Append(indent).Append("        await Session.RelateAsync<").Append(markerFqn).Append(">(__id, ")
                .Append(targetLocal).AppendLine(", ctx.Transaction, ct);");
        }

        builder.Append(indent).AppendLine("}");
    }

    // ──────────────────────────── Hydrate emission ──────────────────────────

    /// <summary>
    /// Emits <c>IEntity.Hydrate(SurrealValue, IHydrationSink)</c> for the table. Each
    /// declared property writes directly into the entity's backing field — no
    /// <c>sink.Parent</c> / <c>sink.Reference</c> calls; the entity owns its own state.
    /// <list type="bullet">
    ///   <item>[Id] → parses the record id and sets the typed <c>_id</c> field.</item>
    ///   <item>scalar [Property] → reads the value and sets <c>_{name}</c>.</item>
    ///   <item>[Reference] non-Inline → reads the id, sets <c>_{name}Id</c>.</item>
    ///   <item>[Reference, Inline] → constructs the target via
    ///         <see cref="HydrationValue.HydrateInlineReference{T}"/>, sets both
    ///         <c>_{name}</c> and <c>_{name}Id</c>; falls back to id-only when the
    ///         target was already tracked (multi-owner inline expansion).</item>
    ///   <item>[Parent] → reads the id, sets <c>_{name}Id</c>.</item>
    /// </list>
    /// Element-collection properties hydrate inline via <see cref="EmitHydrateElementCollection"/>.
    /// Forward/inverse relation edges are loaded separately by the per-aggregate loader.
    /// </summary>
    private static void EmitHydrate(StringBuilder builder, string indent, TableModel table)
    {
        builder
            .Append(indent)
            .Append("void ")
            .Append(EntityInterface)
            .AppendLine($".Hydrate(global::Disruptor.Surreal.Values.SurrealValue row, {HydrationSinkType} sink)")
            .Append(indent)
            .AppendLine("{");

        builder
            .Append(indent)
            .AppendLine("    if (row is not global::Disruptor.Surreal.Values.SurrealObjectValue __obj) return;");

        var idType = $"global::{(string.IsNullOrEmpty(table.Namespace) ? table.Name : $"{table.Namespace}.{table.Name}")}Id";
        builder
            .Append(indent)
            .AppendLine("    if (__obj.Object.TryGetValue(\"id\", out var __idVal))")
            .Append(indent)
            .Append("        _id = new ")
            .Append(idType)
            .AppendLine("(global::Disruptor.Surface.Runtime.HydrationValue.ReadRecordId(__idVal).Value);");

        builder
            .Append(indent)
            .AppendLine("    sink.Track(this);");

        foreach (var p in table.Properties)
        {
            if (p.Kinds.HasFlag(PropertyKind.Property))
            {
                if (IsElementCollection(p.Type) && p.InlineMembers.Count > 0)
                {
                    EmitHydrateElementCollection(builder, indent, p);
                }
                else
                {
                    EmitHydrateValueProperty(builder, indent, p);
                }
            }
            else if (p.Kinds.HasFlag(PropertyKind.Reference))
            {
                EmitHydrateReference(builder, indent, p);
            }
            else if (p.Kinds.HasFlag(PropertyKind.Parent))
            {
                EmitHydrateParent(builder, indent, p);
            }
            // [Children] is computed via parentByChild reverse lookup — nothing to read here.
            // Forward/inverse relation properties are populated by the per-aggregate loader's
            // edge query, not by per-row Hydrate.
        }

        builder
            .Append(indent)
            .AppendLine("}");
    }

    /// <summary>
    /// Hydrates any non-element-collection [Property] — scalar (int, bool, DateTime, …),
    /// array (<c>int[]</c>, <c>List&lt;T&gt;</c>), record. String stays special-cased
    /// so its empty-string fallback matches the schema's <c>DEFAULT ""</c> clause without
    /// a round-trip through the converter.
    /// </summary>
    private static void EmitHydrateValueProperty(StringBuilder builder, string indent, PropertyModel p)
    {
        var backing = $"_{ToCamel(p.Name)}";
        var fieldLit = Quote(SurrealNaming.ToFieldName(p.Name));
        var typeFqn = p.Type.FullyQualifiedName;

        if (typeFqn is "string" or "global::System.String" or "string?" or "global::System.String?")
        {
            builder
                .Append(indent)
                .Append("    ")
                .Append(backing)
                .Append(" = global::Disruptor.Surface.Runtime.HydrationValue.ReadString(__obj, ")
                .Append(fieldLit)
                .AppendLine(");");
        }
        else
        {
            var deserialiseAs = StripNullable(typeFqn);
            builder
                .Append(indent)
                .Append("    ")
                .Append(backing)
                .Append(" = global::Disruptor.Surface.Runtime.HydrationValue.ReadOrDefault<")
                .Append(deserialiseAs)
                .Append(">(__obj, ")
                .Append(fieldLit)
                .AppendLine(");");
        }
    }

    /// <summary>
    /// Hydrates an element-collection [Property] of records (the
    /// <c>IReadOnlyList&lt;Scenario&gt;</c> shape): clears the backing list, walks the
    /// SurrealListValue elements, constructs each <c>T</c> via its primary constructor
    /// using the public scalar properties discovered at codegen time. Pure typed code,
    /// no reflection. Primitive-element collections take the
    /// <see cref="EmitHydrateValueProperty"/> path instead (HydrationValue's typed
    /// converter handles primitive element types).
    /// </summary>
    private static void EmitHydrateElementCollection(StringBuilder builder, string indent, PropertyModel p)
    {
        var backing = $"_{ToCamel(p.Name)}";
        var fieldLit = Quote(SurrealNaming.ToFieldName(p.Name));
        if (p.Type.TypeArguments.Count == 0)
        {
            builder
                .Append(indent)
                .Append("    throw new global::System.NotSupportedException(\"Hydrate: collection element type for property '")
                .Append(p.Name)
                .AppendLine("' could not be resolved at codegen time.\");");
            return;
        }

        var elementType = p.Type.TypeArguments[0].FullyQualifiedName;
        var arrLocal = $"__sl_{ToCamel(p.Name)}";
        var elemLocal = $"__el_{ToCamel(p.Name)}";
        var elemObjLocal = $"__eo_{ToCamel(p.Name)}";

        builder
            .Append(indent).Append("    if (__obj.Object.TryGetValue(").Append(fieldLit).Append(", out var ").Append(arrLocal)
            .Append(") && ").Append(arrLocal).Append(" is global::Disruptor.Surreal.Values.SurrealListValue ").Append(arrLocal).AppendLine("Cast)")
            .Append(indent).AppendLine("    {")
            .Append(indent).Append("        ").Append(backing).AppendLine(".Clear();")
            .Append(indent).Append("        foreach (var ").Append(elemLocal).Append(" in ").Append(arrLocal).AppendLine("Cast.List)")
            .Append(indent).AppendLine("        {")
            .Append(indent).Append("            if (").Append(elemLocal).Append(" is not global::Disruptor.Surreal.Values.SurrealObjectValue ").Append(elemObjLocal).AppendLine(") continue;")
            .Append(indent).Append("            ").Append(backing).Append(".Add(new ").Append(elementType).AppendLine("(");
        for (var i = 0; i < p.InlineMembers.Count; i++)
        {
            var im = p.InlineMembers[i];
            var subLit = Quote(SurrealNaming.ToFieldName(im.Name));
            var typeFqn = im.Type.FullyQualifiedName;
            // String fast-path mirrors EmitHydrateValueProperty's optimisation.
            var trailing = i == p.InlineMembers.Count - 1 ? "" : ",";
            if (typeFqn is "string" or "global::System.String" or "string?" or "global::System.String?")
            {
                builder.Append(indent).Append("                ").Append(im.Name).Append(": global::Disruptor.Surface.Runtime.HydrationValue.ReadString(")
                    .Append(elemObjLocal).Append(", ").Append(subLit).Append(')').AppendLine(trailing);
            }
            else
            {
                var deserialiseAs = StripNullable(typeFqn);
                builder.Append(indent).Append("                ").Append(im.Name).Append(": global::Disruptor.Surface.Runtime.HydrationValue.ReadOrDefault<")
                    .Append(deserialiseAs).Append(">(").Append(elemObjLocal).Append(", ").Append(subLit).Append(')').AppendLine(trailing);
            }
        }
        builder
            .Append(indent).AppendLine("            ));")
            .Append(indent).AppendLine("        }")
            .Append(indent).AppendLine("    }");
    }

    /// <summary>
    /// Hydrates a <c>[Reference]</c> field. Inline form populates both the entity ref
    /// and id backing fields; non-inline (id-only) populates just the id backing field.
    /// The runtime's reference resolution falls back to <c>Session.Get&lt;T&gt;(id)</c>
    /// on read when only the id is set.
    /// </summary>
    private static void EmitHydrateReference(StringBuilder builder, string indent, PropertyModel p)
    {
        var backing = $"_{ToCamel(p.Name)}";
        var idBacking = $"_{ToCamel(p.Name)}Id";
        var fieldLit = Quote(SurrealNaming.ToFieldName(p.Name));
        var typeArg = StripNullable(p.Type.FullyQualifiedName);

        // Try inline first (returns the hydrated entity if the field is an inline object);
        // fall back to id-only if it isn't inline. The if-let-then-else avoids two
        // dictionary lookups for the common case where neither path matches.
        var inlineLocal = $"__inline_{ToCamel(p.Name)}";
        builder
            .Append(indent).Append("    var ").Append(inlineLocal)
            .Append(" = global::Disruptor.Surface.Runtime.HydrationValue.HydrateInlineReference<")
            .Append(typeArg).Append(">(__obj, ").Append(fieldLit).AppendLine(", sink);")
            .Append(indent).Append("    if (").Append(inlineLocal).AppendLine(" is not null)")
            .Append(indent).AppendLine("    {")
            .Append(indent).Append("        ").Append(backing).Append(" = ").Append(inlineLocal).AppendLine(";")
            .Append(indent).Append("        ").Append(idBacking).Append(" = ((").Append(EntityInterface).Append(')').Append(inlineLocal).AppendLine(").Id;")
            .Append(indent).AppendLine("    }")
            .Append(indent).AppendLine("    else")
            .Append(indent).AppendLine("    {")
            .Append(indent).Append("        ").Append(idBacking).Append(" = global::Disruptor.Surface.Runtime.HydrationValue.TryReadReferenceId(__obj, ")
            .Append(fieldLit).AppendLine(");")
            .Append(indent).AppendLine("    }");
    }

    private static void EmitHydrateParent(StringBuilder builder, string indent, PropertyModel p)
    {
        var idBacking = $"_{ToCamel(p.Name)}Id";
        var fieldLit = Quote(SurrealNaming.ToFieldName(p.Name));
        builder
            .Append(indent).Append("    ").Append(idBacking)
            .Append(" = global::Disruptor.Surface.Runtime.HydrationValue.TryReadReferenceId(__obj, ")
            .Append(fieldLit).AppendLine(");");
    }

    // ──────────────────────────── helpers ────────────────────────────────────

    private static string Quote(string s) => $"\"{s.Replace("\"", "\\\"")}\"";

    private static string StripNullable(string typeName)
        => typeName.EndsWith("?") ? typeName[..^1] : typeName;

    private static string FormatAccessibility(string raw) => raw switch
    {
        "Public" => "public",
        "Internal" => "internal",
        "Private" => "private",
        "Protected" => "protected",
        "ProtectedOrInternal" => "protected internal",
        "ProtectedAndInternal" => "private protected",
        "NotApplicable" => string.Empty,
        _ => raw.ToLowerInvariant(),
    };
}
