using System.Text;
using Disruptor.Surface.Generator.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Disruptor.Surface.Generator.Emit;

/// <summary>
/// Emits the implementing half of every partial property and method on a <c>[Table]</c>
/// class. Reads are sync property bodies that hit the in-memory <c>SurrealSession</c>
/// snapshot; writes are sync <c>void</c> methods that record into the session's dirty
/// batch. Async only happens at the session boundary (load + commit) — nothing the
/// generator emits returns <see cref="System.Threading.Tasks.Task"/>.
/// <list type="bullet">
///   <item>[Id] — lazy-cached field; defaults to <c>{Name}Id.New()</c> on first access.</item>
///   <item>[Property] — getter-only or get/set partial property; setters write the backing
///         field then call <c>Session.SetField(this.Id, field, value)</c>.</item>
///   <item>[Reference] — sync getter-only partial property; non-nullable maps to
///         <c>Session.GetReference</c> (throws on miss), nullable to
///         <c>GetReferenceOrDefault</c>. Mandatory references emit an <c>OnCreate{Name}</c>
///         partial hook plus an entry in <c>IEntity.Initialize</c>. Settable references
///         route through <c>SetField/UnsetField</c> with <c>FieldKind.Reference</c>.</item>
///   <item>[Parent] — sync property; setter calls <c>SetField</c> with
///         <c>FieldKind.Parent</c>.</item>
///   <item>[Children] — sync getter-only partial property over <c>QueryChildren</c>.</item>
///   <item>Forward/inverse relation property — sync collection from directional
///         <c>QueryOutgoing</c> / <c>QueryIncoming</c> for same-aggregate edges, or
///         <c>QueryRelatedIds</c> / <c>QueryInverseRelatedIds</c> for cross-aggregate
///         edges. Relation writes go through <c>Session.Relate</c>,
///         <c>Unrelate</c>, <c>UnrelateAllFrom</c>, and <c>UnrelateAllTo</c>.</item>
/// </list>
/// </summary>
internal static class PartialEmitter
{
    private const string SessionType = "global::Disruptor.Surface.Runtime.SurrealSession";
    private const string EntityInterface = "global::Disruptor.Surface.Runtime.IEntity";
    private const string HydrationSinkType = "global::Disruptor.Surface.Runtime.IHydrationSink";
    private const string SurrealArrayMetadata = "Disruptor.Surface.Runtime.SurrealArray`1";

    public static void Emit(SourceProductionContext spc, TableModel table, ModelGraph graph)
    {
        if (!table.IsPartial)
        {
            return;
        }

        // Empty annotated tables are legal — the id anchor is always emitted, so a
        // [Table] with no partial members still gets IEntity scaffolding (Bind, Initialize,
        // Hydrate, Flush, OnDeleting) and is fully Track-able / Load-able. Just an entity
        // that carries nothing but its identity.
        var partialProps = table.Properties.Where(p => p.IsPartial).ToArray();

        var builder = new StringBuilder()
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(table.Namespace);
        if (hasNamespace)
        {
            builder
                .Append("namespace ")
                .Append(table.Namespace)
                .AppendLine()
                .AppendLine("{");
        }

        var indent = hasNamespace ? "    " : string.Empty;

        builder
            .Append(indent)
            .Append(FormatAccessibility(table.DeclaredAccessibility))
            .Append(' ');
        if (table.IsAbstract)
        {
            builder.Append("abstract ");
        }

        if (table.IsSealed)
        {
            builder.Append("sealed ");
        }

        builder
            .Append("partial class ")
            .Append(table.Name);
        if (table.TypeParameters.Count > 0)
        {
            builder
                .Append('<')
                .Append(string.Join(", ", table.TypeParameters))
                .Append('>');
        }

        builder
            .Append(" : ")
            .Append(EntityInterface);
        foreach (var union in graph.UnionsForTable(table.FullName))
        {
            builder
                .Append(", global::")
                .Append(union.InterfaceFullName);
        }
        builder
            .AppendLine()
            .Append(indent)
            .AppendLine("{");

        var memberIndent = $"{indent}    ";

        WriteSessionPlumbing(builder, memberIndent);

        // The id anchor is emitted unconditionally — the runtime needs IEntity.Id to read
        // every entity's identity, and the typed {Name}Id struct is always emitted by
        // IdEmitter regardless of whether the user opted into a public-facing [Id] property.
        EmitIdAnchor(builder, memberIndent, table);

        var mandatoryRefs = new List<PropertyModel>();

        foreach (var t in partialProps)
        {
            builder.AppendLine();
            EmitProperty(builder, memberIndent, t, graph);

            if (IsMandatoryReference(t))
            {
                mandatoryRefs.Add(t);
            }
        }

        // Initialize hook always emitted, even when empty — IEntity demands it and a
        // no-op for entities without mandatory refs is the cleanest path.
        builder.AppendLine();
        EmitInitialize(builder, memberIndent, mandatoryRefs);

        // Hydrate hook — invoked by the per-aggregate loader on each loaded row.
        builder.AppendLine();
        EmitHydrate(builder, memberIndent, table);

        // OnDeleting hook — invoked by Session.Delete(IEntity) before the entity's own
        // delete command is queued. User can implement the simple-form partial method to
        // queue child deletes / clears.
        builder.AppendLine();
        EmitOnDeleting(builder, memberIndent);

        // MarkAllSlicesLoaded — used by the legacy aggregate loader (after Hydrate) and by
        // SurrealSession.Track<T> (fresh-entity path) to declare every slice on this entity
        // is "loaded". The compiler-driven path marks slices selectively via the include
        // AST instead.
        builder.AppendLine();
        EmitMarkAllSlicesLoaded(builder, memberIndent, table);

        builder
            .Append(indent)
            .AppendLine("}");

        if (hasNamespace)
        {
            builder.AppendLine("}");
        }

        spc.AddSource(table.FileHintName, SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    // ──────────────────────────── per-table preamble ─────────────────────────

    /// <summary>
    /// Emits per-entity session plumbing: a private <c>_session</c> field, a private
    /// <c>_pendingWrites</c> buffer for object-initializer values that arrive before the
    /// entity is tracked, the explicit <c>IEntity.Session</c> getter (nullable),
    /// <c>IEntity.Bind</c> (one-shot setter for <c>_session</c>), <c>IEntity.Flush</c>
    /// (drains the buffer into the bound session), the protected <c>Session</c> property
    /// for entity-body reads (throws when unbound — reading from an unbound entity is a
    /// programmer error), and the <c>__WriteField</c> / <c>__ClearField</c> setter
    /// helpers that buffer when unbound or route through the session when bound.
    /// </summary>
    private static void WriteSessionPlumbing(StringBuilder builder, string indent)
    {
        builder
            .Append(indent)
            .Append("private ")
            .Append(SessionType)
            .AppendLine("? _session;")
            .Append(indent)
            .Append("private global::System.Collections.Generic.List<(string Field, object? Value, global::Disruptor.Surface.Runtime.FieldKind Kind)>? _pendingWrites;")
            .AppendLine()
            .AppendLine();

        builder
            .Append(indent)
            .Append(SessionType)
            .Append("? ")
            .Append(EntityInterface)
            .AppendLine(".Session => _session;")
            .AppendLine()
            .Append(indent)
            .Append("void ")
            .Append(EntityInterface)
            .Append(".Bind(")
            .Append(SessionType)
            .AppendLine(" session)")
            .Append(indent).AppendLine("{")
            .Append(indent).AppendLine("    if (_session is not null && !global::System.Object.ReferenceEquals(_session, session))")
            .Append(indent).AppendLine("        throw new global::System.InvalidOperationException(\"Entity is already bound to a different session.\");")
            .Append(indent).AppendLine("    _session = session;")
            .Append(indent).AppendLine("}")
            .AppendLine()
            .Append(indent)
            .Append("void ")
            .Append(EntityInterface)
            .Append(".Flush(")
            .Append(SessionType)
            .AppendLine(" session)")
            .Append(indent).AppendLine("{")
            .Append(indent).AppendLine("    if (_pendingWrites is null) return;")
            .Append(indent).AppendLine($"    foreach (var (f, v, k) in _pendingWrites) session.SetField((({EntityInterface})this).Id, f, v, k);")
            .Append(indent).AppendLine("    _pendingWrites = null;")
            .Append(indent).AppendLine("}")
            .AppendLine();

        builder
            .Append(indent)
            .Append("protected ")
            .Append(SessionType)
            .AppendLine(" Session")
            .Append(indent)
            .AppendLine("    => _session ?? throw new global::System.InvalidOperationException(\"Entity is not bound to a session — call session.Track(...) or hydrate via Sessions.Load*Async first.\");")
            .AppendLine();

        builder
            .Append(indent)
            .Append("private void __WriteField(string field, object? value, global::Disruptor.Surface.Runtime.FieldKind kind = global::Disruptor.Surface.Runtime.FieldKind.Property)")
            .AppendLine()
            .Append(indent).AppendLine("{")
            .Append(indent).AppendLine("    if (_session is null) (_pendingWrites ??= new()).Add((field, value, kind));")
            .Append(indent).AppendLine($"    else _session.SetField((({EntityInterface})this).Id, field, value, kind);")
            .Append(indent).AppendLine("}")
            .AppendLine()
            .Append(indent)
            .Append("private void __ClearField(string field, global::Disruptor.Surface.Runtime.FieldKind kind = global::Disruptor.Surface.Runtime.FieldKind.Property)")
            .AppendLine()
            .Append(indent).AppendLine("{")
            .Append(indent).AppendLine("    if (_session is null) _pendingWrites?.RemoveAll(p => p.Field == field);")
            .Append(indent).AppendLine($"    else _session.UnsetField((({EntityInterface})this).Id, field, kind);")
            .Append(indent).AppendLine("}")
            .AppendLine()
            // Slice guard — called by every navigable read path before walking the in-memory
            // cache. Reuses the protected Session accessor so unbound entities still get the
            // existing "not tracked" error; once bound, the slice check throws
            // LoadShapeViolationException with a hint at FetchAsync.
            .Append(indent)
            .AppendLine("private void __EnsureSliceLoaded(string sliceKey, string fetchHint)")
            .Append(indent).AppendLine("{")
            .Append(indent).Append("    var __id = ((").Append(EntityInterface).AppendLine(")this).Id;")
            .Append(indent).AppendLine("    if (!Session.IsSliceLoaded(__id, sliceKey))")
            .Append(indent).AppendLine("        throw new global::Disruptor.Surface.Runtime.LoadShapeViolationException(__id, sliceKey, fetchHint);")
            .Append(indent).AppendLine("}");
    }

    // ──────────────────────────── property emission ──────────────────────────

    private static void EmitProperty(StringBuilder builder, string indent, PropertyModel p, ModelGraph graph)
    {
        if (p.RelationRole is RelationRole.ForwardRelation or RelationRole.InverseRelation)
        {
            EmitRelationProperty(builder, indent, p, graph);
            return;
        }

        if (p.Kinds.HasFlag(PropertyKind.Id))
        {
            EmitIdProperty(builder, indent, p);
        }
        else if (p.Kinds.HasFlag(PropertyKind.Property))
        {
            EmitPropertyMember(builder, indent, p);
        }
        else if (p.Kinds.HasFlag(PropertyKind.Parent))
        {
            EmitParentProperty(builder, indent, p);
        }
        else if (p.Kinds.HasFlag(PropertyKind.Children))
        {
            EmitChildrenProperty(builder, indent, p);
        }
        else if (p.Kinds.HasFlag(PropertyKind.Reference))
        {
            EmitReferenceProperty(builder, indent, p);
        }
        else
        {
            EmitFallbackProperty(builder, indent, p);
        }
    }

    /// <summary>
    /// <c>[Property]</c> on a property declaration: scalar columns go through
    /// <see cref="EmitDataProperty"/> (backing field + setter routing through
    /// <c>SetField</c>); inline ordered collections typed as <c>SurrealArray&lt;T&gt;</c>
    /// go through <see cref="EmitSurrealArrayProperty"/> (lazy-cached wrapper that
    /// notifies the workspace on every mutation).
    /// </summary>
    private static void EmitPropertyMember(StringBuilder builder, string indent, PropertyModel p)
    {
        if (p.Type.MetadataName == SurrealArrayMetadata)
        {
            EmitSurrealArrayProperty(builder, indent, p);
        }
        else
        {
            EmitDataProperty(builder, indent, p);
        }
    }

    /// <summary>
    /// Emits the lazy-cached wrapper for an inline <c>array&lt;object&gt;</c> column.
    /// The wrapper is created once per entity instance (never replaced), so any reference
    /// the user holds stays valid as the list mutates. Mutations route through
    /// <see>
    ///     <cref>SurrealArray{T}</cref>
    /// </see>
    /// 's own notify path — the generator doesn't emit a
    /// setter or any per-verb method.
    /// </summary>
    private static void EmitSurrealArrayProperty(StringBuilder builder, string indent, PropertyModel p)
    {
        var declaredType = p.Type.FullyQualifiedName;
        var access = FormatAccessibility(p.DeclaredAccessibility);
        var backing = $"_{ToCamel(p.Name)}";
        var fieldLit = Quote(SurrealNaming.ToFieldName(p.Name));

        // The writer lambda routes through __WriteField — same path as scalar setters —
        // so pre-bind mutations buffer in _pendingWrites and replay through Flush when
        // Track binds the entity. Nothing reaches Session.SetField directly.
        builder
            .Append(indent)
            .Append("private ")
            .Append(declaredType)
            .Append("? ")
            .Append(backing)
            .AppendLine(";")
            .Append(indent)
            .Append(access)
            .Append(" partial ")
            .Append(declaredType)
            .Append(' ')
            .Append(p.Name)
            .Append(" => ")
            .Append(backing)
            .Append(" ??= new ")
            .Append(declaredType)
            .Append("(null, __items => __WriteField(")
            .Append(fieldLit)
            .AppendLine(", __items));");
    }

    /// <summary>
    /// Emits the always-present id anchor: the private <c>_id</c> backing field plus the
    /// explicit <c>IEntity.Id</c> accessor. Both lazy-mint via <c>{Name}Id.New()</c> on
    /// first read; <c>Hydrate</c> writes the field directly when loading from the DB.
    /// The user's optional <c>[Id]</c>-tagged partial property (if declared) is emitted
    /// separately by <see cref="EmitIdProperty"/> as a delegate to this anchor.
    /// </summary>
    private static void EmitIdAnchor(StringBuilder builder, string indent, TableModel table)
    {
        var idType = $"global::{(string.IsNullOrEmpty(table.Namespace) ? table.Name : $"{table.Namespace}.{table.Name}")}Id";
        builder
            .AppendLine()
            .Append(indent)
            .Append("private ")
            .Append(idType)
            .AppendLine("? _id;")
            .Append(indent)
            .Append("global::Disruptor.Surface.Runtime.RecordId ")
            .Append(EntityInterface)
            .Append(".Id => _id ??= ")
            .Append(idType)
            .AppendLine(".New();");
    }

    /// <summary>
    /// Emits the user-facing <c>[Id]</c> partial property — a get/set delegate to the
    /// id anchor. Only called when the user has declared an <c>[Id]</c>-tagged partial
    /// property; without one, the entity simply has no public-facing Id surface (the
    /// anchor still exists internally).
    /// <para>
    /// The setter (when declared) refuses to mutate the anchor once the entity is bound
    /// to a session — by that point the entity lives in the session's identity map keyed
    /// on the current id, and silently overwriting it would corrupt every dict. Pre-bind
    /// sets are fine: the session hasn't adopted the entity yet, and the
    /// <c>new Design { Id = knownId }</c> object-initializer pattern (handy for
    /// constructing handles to look up in a freshly loaded workspace) keeps working.
    /// </para>
    /// </summary>
    private static void EmitIdProperty(StringBuilder builder, string indent, PropertyModel p)
    {
        var idType = p.Type.FullyQualifiedName;
        var idArg = StripNullable(idType);
        var access = FormatAccessibility(p.DeclaredAccessibility);

        builder
            .Append(indent)
            .Append(access)
            .Append(" partial ")
            .Append(idType)
            .Append(' ')
            .AppendLine(p.Name)
            .Append(indent)
            .AppendLine("{")
            .Append(indent)
            .Append("    get => _id ??= ")
            .Append(idArg)
            .AppendLine(".New();");
        if (p.HasSetter)
        {
            builder
                .Append(indent)
                .AppendLine("    set")
                .Append(indent)
                .AppendLine("    {")
                .Append(indent)
                .AppendLine("        if (_session is not null)")
                .Append(indent)
                .AppendLine("            throw new global::System.InvalidOperationException(\"Cannot mutate Id after the entity is bound to a session.\");")
                .Append(indent)
                .AppendLine("        _id = value;")
                .Append(indent)
                .AppendLine("    }");
        }
        builder
            .Append(indent)
            .AppendLine("}");
    }

    private static void EmitDataProperty(StringBuilder builder, string indent, PropertyModel p)
    {
        var type = p.Type.FullyQualifiedName;
        var access = FormatAccessibility(p.DeclaredAccessibility);
        var backing = $"_{ToCamel(p.Name)}";

        // = default! silences CS8618 for non-nullable types; CS0649 covers the case where
        // the user declares no setter (read-only [Property] is legal). Reading before any
        // setter runs returns the type's default — the schema's DEFAULT clause is the
        // contract for what the database hands back, not something we synthesise.
        builder
            .Append(indent)
            .AppendLine("#pragma warning disable CS0649")
            .Append(indent)
            .Append("private ")
            .Append(type)
            .Append(' ')
            .Append(backing)
            .AppendLine(" = default!;")
            .Append(indent)
            .AppendLine("#pragma warning restore CS0649");

        if (!p.HasSetter && !p.HasInitOnlySetter)
        {
            builder.Append(indent)
                .Append(access)
                .Append(" partial ")
                .Append(type)
                .Append(' ')
                .Append(p.Name)
                .Append(" => ")
                .Append(backing)
                .AppendLine(";");
            return;
        }

        var fieldLit = Quote(SurrealNaming.ToFieldName(p.Name));
        builder
            .Append(indent)
            .Append(access)
            .Append(" partial ")
            .Append(type)
            .Append(' ')
            .AppendLine(p.Name)
            .Append(indent)
            .AppendLine("{")
            .Append(indent)
            .Append("    get => ")
            .Append(backing)
            .AppendLine(";")
            .Append(indent)
            .Append("    ")
            .AppendLine(p.HasInitOnlySetter ? "init" : "set")
            .Append(indent)
            .AppendLine("    {")
            .Append(indent)
            .Append("        ")
            .Append(backing)
            .AppendLine(" = value;")
            .Append(indent)
            .Append("        __WriteField(")
            .Append(fieldLit)
            .AppendLine(", value);")
            .Append(indent)
            .AppendLine("    }")
            .Append(indent)
            .AppendLine("}");
    }

    private static void EmitParentProperty(StringBuilder builder, string indent, PropertyModel p)
    {
        var declared = p.Type.FullyQualifiedName;
        var typeArg = StripNullable(declared);
        var access = FormatAccessibility(p.DeclaredAccessibility);
        var sliceKey = SurrealNaming.ToFieldName(p.Name);
        var sliceKeyLit = Quote(sliceKey);
        var fetchHintLit = Quote($".Include{p.Name}() on the parent query");

        builder
            .Append(indent)
            .Append(access)
            .Append(" partial ")
            .Append(declared)
            .Append(' ')
            .AppendLine(p.Name)
            .Append(indent)
            .AppendLine("{")
            .Append(indent)
            .AppendLine("    get")
            .Append(indent).AppendLine("    {")
            .Append(indent).Append("        __EnsureSliceLoaded(").Append(sliceKeyLit).Append(", ").Append(fetchHintLit).AppendLine(");")
            .Append(indent).Append("        return Session.GetParent<").Append(typeArg).AppendLine(">(this);")
            .Append(indent).AppendLine("    }");

        if (p.HasSetter || p.HasInitOnlySetter)
        {
            builder
                .Append(indent)
                .Append("    ")
                .AppendLine(p.HasInitOnlySetter ? "init" : "set")
                .Append(indent)
                .Append("        => __WriteField(")
                .Append(sliceKeyLit)
                .AppendLine(", value, global::Disruptor.Surface.Runtime.FieldKind.Parent);");
        }

        builder.Append(indent).AppendLine("}");
    }

    private static void EmitChildrenProperty(StringBuilder builder, string indent, PropertyModel p)
    {
        var declared = p.Type.FullyQualifiedName;
        var element = p.Type.ElementType ?? p.Type;
        var (elementTypeArg, elementNameExpr) = ResolveElement(element);
        var access = FormatAccessibility(p.DeclaredAccessibility);
        var sliceKey = SurrealNaming.ToFieldName(p.Name);
        var sliceKeyLit = Quote(sliceKey);
        var fetchHintLit = Quote($".Include{p.Name}(...) on the parent query");

        builder
            .Append(indent)
            .Append(access)
            .Append(" partial ")
            .Append(declared)
            .Append(' ')
            .AppendLine(p.Name)
            .Append(indent).AppendLine("{")
            .Append(indent).AppendLine("    get")
            .Append(indent).AppendLine("    {")
            .Append(indent).Append("        __EnsureSliceLoaded(").Append(sliceKeyLit).Append(", ").Append(fetchHintLit).AppendLine(");")
            .Append(indent).Append("        return Session.QueryChildren<")
            .Append(elementTypeArg).Append(">(this, ").Append(elementNameExpr).AppendLine(");")
            .Append(indent).AppendLine("    }")
            .Append(indent).AppendLine("}");
    }

    /// <summary>
    /// Sync property body for <c>[Reference]</c>:
    /// <list type="bullet">
    ///   <item>Get-only non-nullable → mandatory; <c>GetReference</c> (throws on miss).
    ///         Pairs with the <c>OnCreate{Name}</c> hook the workspace runs from
    ///         <see cref="EmitInitialize"/> when <c>Create&lt;T&gt;()</c> mints a fresh
    ///         entity.</item>
    ///   <item>Get-only nullable → optional; <c>GetReferenceOrDefault</c>.</item>
    ///   <item>Get + set non-nullable → user controls init themselves; setter calls
    ///         <c>SetField(..., FieldKind.Reference)</c>.</item>
    ///   <item>Get + set nullable → setter branches: null calls <c>UnsetField</c>,
    ///         non-null calls <c>SetField</c> — both with <c>FieldKind.Reference</c>.</item>
    /// </list>
    /// </summary>
    private static void EmitReferenceProperty(StringBuilder builder, string indent, PropertyModel p)
    {
        var declared = p.Type.FullyQualifiedName;
        var typeArg = StripNullable(declared);
        var access = FormatAccessibility(p.DeclaredAccessibility);
        var fieldLit = Quote(SurrealNaming.ToFieldName(p.Name));
        var fetchHintLit = Quote($".Include{p.Name}() on the parent query");
        var nullable = p.Type.IsNullable;
        var getMethod = nullable ? "GetReferenceOrDefault" : "GetReference";

        builder
            .Append(indent)
            .Append(access)
            .Append(" partial ")
            .Append(declared)
            .Append(' ')
            .AppendLine(p.Name)
            .Append(indent).AppendLine("{")
            .Append(indent).AppendLine("    get")
            .Append(indent).AppendLine("    {")
            .Append(indent).Append("        __EnsureSliceLoaded(").Append(fieldLit).Append(", ").Append(fetchHintLit).AppendLine(");")
            .Append(indent).Append("        return Session.").Append(getMethod).Append('<').Append(typeArg)
            .Append(">(this, ").Append(fieldLit).AppendLine(");")
            .Append(indent).AppendLine("    }");

        if (p.HasSetter || p.HasInitOnlySetter)
        {
            builder
                .Append(indent)
                .Append("    ")
                .AppendLine(p.HasInitOnlySetter ? "init" : "set");

            if (nullable)
            {
                builder
                    .Append(indent).AppendLine("    {")
                    .Append(indent).Append("        if (value is null) __ClearField(")
                    .Append(fieldLit).AppendLine(", global::Disruptor.Surface.Runtime.FieldKind.Reference);")
                    .Append(indent).Append("        else __WriteField(")
                    .Append(fieldLit).AppendLine(", value, global::Disruptor.Surface.Runtime.FieldKind.Reference);")
                    .Append(indent).AppendLine("    }");
            }
            else
            {
                builder
                    .Append(indent).Append("        => __WriteField(")
                    .Append(fieldLit).AppendLine(", value, global::Disruptor.Surface.Runtime.FieldKind.Reference);");
            }
        }

        builder.Append(indent).AppendLine("}");
    }

    /// <summary>
    /// A getter-only collection property carrying a forward/inverse relation attribute
    /// maps to either:
    /// <list type="bullet">
    ///   <item>Within-aggregate → <c>Session.QueryOutgoing&lt;TKind, TElement&gt;(this)</c>
    ///         on the forward side, <c>Session.QueryIncoming&lt;TKind, TElement&gt;(this)</c>
    ///         on the inverse side. Direction is explicit so same-table relations and
    ///         overlapping role types don't accidentally read both endpoints.</item>
    ///   <item>Cross-aggregate → <c>Session.QueryRelatedIds&lt;TKind&gt;(this)</c> on the
    ///         forward side / <c>Session.QueryInverseRelatedIds&lt;TKind&gt;(this)</c> on
    ///         the inverse side (id-typed, since target/source entities live in a
    ///         different aggregate snapshot).</item>
    /// </list>
    /// </summary>
    private static void EmitRelationProperty(StringBuilder builder, string indent, PropertyModel p, ModelGraph graph)
    {
        var declared = p.Type.FullyQualifiedName;
        var access = FormatAccessibility(p.DeclaredAccessibility);
        var kindMarker = ResolveKindMarkerFqn(p.RelationKindFullName, graph);

        var forwardKindFullName = ForwardKindFullNameFor(p.RelationKindFullName, p.RelationRole, graph);
        var crossAggregate = forwardKindFullName is not null && graph.IsCrossAggregate(forwardKindFullName);
        var sliceKey = SurrealNaming.ToFieldName(p.Name);
        var sliceKeyLit = Quote(sliceKey);
        var fetchHintLit = Quote($"a Workspace.Query.Edges.* query covering {p.Name}");

        if (crossAggregate)
        {
            var method = p.RelationRole == RelationRole.ForwardRelation ? "QueryRelatedIds" : "QueryInverseRelatedIds";
            builder
                .Append(indent)
                .Append(access)
                .Append(" partial ")
                .Append(declared)
                .Append(' ')
                .AppendLine(p.Name)
                .Append(indent).AppendLine("{")
                .Append(indent).AppendLine("    get")
                .Append(indent).AppendLine("    {")
                .Append(indent).Append("        __EnsureSliceLoaded(").Append(sliceKeyLit).Append(", ").Append(fetchHintLit).AppendLine(");")
                .Append(indent).Append("        return Session.").Append(method).Append('<').Append(kindMarker).AppendLine(">(this);")
                .Append(indent).AppendLine("    }")
                .Append(indent).AppendLine("}");
            return;
        }

        var elementType = p.Type.ElementType ?? p.Type;
        var elementArg = elementType.IsTypeParameter
            ? elementType.DisplayName
            : StripNullable(elementType.FullyQualifiedName);

        var directionalMethod = p.RelationRole == RelationRole.ForwardRelation
            ? "QueryOutgoing"
            : "QueryIncoming";

        builder
            .Append(indent)
            .Append(access)
            .Append(" partial ")
            .Append(declared)
            .Append(' ')
            .AppendLine(p.Name)
            .Append(indent).AppendLine("{")
            .Append(indent).AppendLine("    get")
            .Append(indent).AppendLine("    {")
            .Append(indent).Append("        __EnsureSliceLoaded(").Append(sliceKeyLit).Append(", ").Append(fetchHintLit).AppendLine(");")
            .Append(indent).Append("        return Session.").Append(directionalMethod).Append('<')
            .Append(kindMarker).Append(", ").Append(elementArg).AppendLine(">(this);")
            .Append(indent).AppendLine("    }")
            .Append(indent).AppendLine("}");
    }

    /// <summary>
    /// Resolves the FQN of the typed-kind marker class emitted alongside a forward
    /// relation attribute. <paramref name="memberKindFullName"/> may be either side —
    /// inverse kinds resolve to their paired forward's marker.
    /// </summary>
    private static string ResolveKindMarkerFqn(string? memberKindFullName, ModelGraph graph)
    {
        var kind = graph.FindKind(memberKindFullName);
        if (kind is null)
        {
            return "global::Disruptor.Surface.Runtime.IRelationKind";
        }

        var forward = kind.Direction == RelationDirection.Forward
            ? kind
            : graph.FindKind(kind.PairedForwardFullName);
        if (forward is null)
        {
            return "global::Disruptor.Surface.Runtime.IRelationKind";
        }

        var markerName = SurrealNaming.StripAttributeSuffix(forward.Name);
        return string.IsNullOrEmpty(forward.Namespace)
            ? $"global::{markerName}"
            : $"global::{forward.Namespace}.{markerName}";
    }

    /// <summary>
    /// Resolves the forward kind FQN whether the member sits on the forward or inverse
    /// side. Forward-side members carry the forward kind directly; inverse-side members
    /// carry the inverse kind and we walk to the paired forward.
    /// </summary>
    private static string? ForwardKindFullNameFor(string? memberKindFullName, RelationRole role, ModelGraph graph)
    {
        if (memberKindFullName is null)
        {
            return null;
        }

        if (role == RelationRole.ForwardRelation)
        {
            return memberKindFullName;
        }

        var kind = graph.FindKind(memberKindFullName);
        return kind?.PairedForwardFullName;
    }

    private static void EmitFallbackProperty(StringBuilder builder, string indent, PropertyModel p)
    {
        var type = p.Type.FullyQualifiedName;
        var access = FormatAccessibility(p.DeclaredAccessibility);
        builder
            .Append(indent)
            .Append(access)
            .Append(" partial ")
            .Append(type)
            .Append(' ')
            .Append(p.Name)
            .AppendLine(" => throw new global::System.NotImplementedException();");
    }

    private static string ToCamel(string s) =>
        s.Length == 0 ? s : char.ToLowerInvariant(s[0]) + s[1..];

    /// <summary>
    /// Resolves element info for a TypeRef. The <c>NameExpr</c> is the Surreal table-name
    /// string the runtime keys off (lower_snake_case + pluralised). For concrete types we
    /// bake the literal at codegen time; for type parameters we fall back to
    /// <c>typeof(T).Name</c> — only ever hit by generic <c>[Children]</c>, which CG009
    /// rejects, so the unresolved-name path is effectively dead.
    /// </summary>
    private static (string TypeArg, string NameExpr) ResolveElement(TypeRef t)
    {
        if (t.IsTypeParameter)
        {
            return (t.DisplayName, $"typeof({t.DisplayName}).Name");
        }

        var stripped = StripNullable(t.FullyQualifiedName);
        return (stripped, Quote(SurrealNaming.ToTableName(SurrealNaming.SimpleName(stripped))));
    }

    // ──────────────────────────── relation default mutators ─────────────────
    // Empty section — no default Add/Remove/Clear methods are emitted any more. The
    // typed `Session.Relate<TKind>(...)` etc. is the canonical surface; users who want a
    // domain-named verb write a one-line passthrough in their own partial:
    //
    //     public void Restricts(IRestrictedBy x) => Session.Relate<Restricts>(this, x);

    // ──────────────────────────── Initialize emission ────────────────────────

    private static bool IsMandatoryReference(PropertyModel p)
        => p.Kinds.HasFlag(PropertyKind.Reference)
           && !p.Type.IsNullable
           && p.HasGetter
           && !p.HasSetter
           && !p.HasInitOnlySetter;

    /// <summary>
    /// Emits the <c>void IEntity.Initialize(SurrealSession)</c> impl that <c>Session.Track</c>
    /// invokes immediately after a fresh entity is tracked. For each mandatory
    /// <c>[Reference]</c> we also emit the <c>OnCreate{Name}</c> partial declaration so
    /// the user supplies the seed logic, then mint the target, run the hook, and write
    /// the reference. Entities without mandatory refs get an empty body.
    /// </summary>
    private static void EmitInitialize(StringBuilder builder, string indent, List<PropertyModel> mandatoryRefs)
    {
        foreach (var p in mandatoryRefs)
        {
            var typeArg = StripNullable(p.Type.FullyQualifiedName);
            // Simple-form partial — no accessibility, no body required. If the user
            // doesn't implement it, the call below is elided at compile time and
            // the new entity just keeps its DEFAULT-clause field values.
            builder
                .Append(indent)
                .Append("partial void OnCreate")
                .Append(p.Name)
                .Append('(')
                .Append(typeArg)
                .AppendLine(" entity);");
        }

        if (mandatoryRefs.Count > 0)
        {
            builder.AppendLine();
        }

        builder
            .Append(indent)
            .Append("void ")
            .Append(EntityInterface)
            .Append(".Initialize(")
            .Append(SessionType)
            .Append(" session)");

        if (mandatoryRefs.Count == 0)
        {
            builder.AppendLine(" { }");
            return;
        }

        builder
            .AppendLine()
            .Append(indent)
            .AppendLine("{");
        foreach (var p in mandatoryRefs)
        {
            var typeArg = StripNullable(p.Type.FullyQualifiedName);
            var fieldLit = Quote(SurrealNaming.ToFieldName(p.Name));
            var local = $"__{ToCamel(p.Name)}";

            builder.Append(indent)
                .Append("    var ")
                .Append(local)
                .Append(" = new ")
                .Append(typeArg)
                .AppendLine("();")
                .Append(indent)
                .Append("    OnCreate")
                .Append(p.Name)
                .Append('(')
                .Append(local)
                .AppendLine(");")
                .Append(indent)
                .Append($"    session.SetField((({EntityInterface})this).Id, ")
                .Append(fieldLit)
                .Append(", ")
                .Append(local)
                .AppendLine(", global::Disruptor.Surface.Runtime.FieldKind.Reference);");
        }

        builder
            .Append(indent)
            .AppendLine("}");
    }

    // ──────────────────────────── OnDeleting emission ───────────────────────

    /// <summary>
    /// Emits a simple-form <c>partial void OnDeleting()</c> hook the user may optionally
    /// implement to queue dependent-delete / reference-clear commands, plus the explicit
    /// <see>
    ///     <cref>IEntity.OnDeleting</cref>
    /// </see>
    /// impl that the workspace dispatches to. If the
    /// user doesn't implement the partial, the call inside the dispatch is elided at
    /// compile time and Delete just queues the entity's own DELETE command.
    /// </summary>
    private static void EmitOnDeleting(StringBuilder builder, string indent)
    {
        builder
            .Append(indent)
            .AppendLine("partial void OnDeleting();")
            .AppendLine()
            .Append(indent)
            .Append("void ")
            .Append(EntityInterface)
            .AppendLine(".OnDeleting() => OnDeleting();");
    }

    /// <summary>
    /// Emits <c>IEntity.MarkAllSlicesLoaded</c> — one <see cref="IHydrationSink.MarkSliceLoaded"/>
    /// call per navigable slice on this entity. Slice keys are snake-cased C# property names
    /// (matches the keys the read paths look up via <see cref="SurrealSession.IsSliceLoaded"/>).
    /// Skipped: <c>[Id]</c> (the entity itself) and scalar <c>[Property]</c> (always loaded
    /// with the row's <c>*</c> projection — no slice check on the read path).
    /// </summary>
    private static void EmitMarkAllSlicesLoaded(StringBuilder builder, string indent, TableModel table)
    {
        builder
            .Append(indent)
            .Append("void ")
            .Append(EntityInterface)
            .Append(".MarkAllSlicesLoaded(").Append(HydrationSinkType).AppendLine(" sink)")
            .Append(indent).AppendLine("{")
            .Append(indent).AppendLine($"    var __id = (({EntityInterface})this).Id;");

        foreach (var p in table.Properties)
        {
            // Skip [Id] (the entity itself) and scalar [Property] (no slice check).
            if (p.Kinds.HasFlag(PropertyKind.Id)) continue;
            if (p.Kinds.HasFlag(PropertyKind.Property) && p.RelationRole == RelationRole.None) continue;
            // [Parent] / [Reference] / [Children] / forward+inverse relation kinds — all
            // get a slice mark keyed on the snake-cased property name.
            var sliceKey = SurrealNaming.ToFieldName(p.Name);
            builder
                .Append(indent)
                .Append("    sink.MarkSliceLoaded(__id, \"")
                .Append(sliceKey)
                .AppendLine("\");");
        }

        builder.Append(indent).AppendLine("}");
    }

    // ──────────────────────────── Hydrate emission ──────────────────────────

    /// <summary>
    /// Emits <c>IEntity.Hydrate(JsonElement, SurrealSession)</c> for the table. Reads each
    /// declared property from the JSON row:
    /// <list type="bullet">
    ///   <item>[Id] → parses the record id string and sets the typed <c>_id</c> field.</item>
    ///   <item>scalar [Property] → reads the field value and sets the backing field.</item>
    ///   <item>[Reference] → reads the record id, calls <c>sink.Reference</c>.</item>
    ///   <item>[Parent] → reads the record id, calls <c>sink.Parent</c>.</item>
    /// </list>
    /// <c>SurrealArray</c> properties hydrate inline via <see cref="EmitHydrateSurrealArray"/>.
    /// Forward/inverse relation edges are loaded separately by the per-aggregate loader's
    /// edge queries. The sink parameter routes through <see cref="IHydrationSink"/> instead
    /// of taking the bare session — keeps the four hydration ops out of the user-facing
    /// session surface.
    /// </summary>
    private static void EmitHydrate(StringBuilder builder, string indent, TableModel table)
    {
        builder
            .Append(indent)
            .Append("void ")
            .Append(EntityInterface)
            .AppendLine($".Hydrate(global::System.Text.Json.JsonElement json, {HydrationSinkType} sink)")
            .Append(indent)
            .AppendLine("{");

        // The id anchor is always emitted by EmitIdAnchor, so Hydrate always writes _id
        // when the row carries an `id` field. {Name}Id wraps a validated string; we pass
        // the parsed RecordId.Value through directly — DB rows are trusted (we've written
        // them or they came back from Surreal), so the validator passes.
        var idType = $"global::{(string.IsNullOrEmpty(table.Namespace) ? table.Name : $"{table.Namespace}.{table.Name}")}Id";
        builder
            .Append(indent)
            .AppendLine("    if (json.TryGetProperty(\"id\", out var __idElem))")
            .Append(indent)
            .Append("        _id = new ")
            .Append(idType)
            .AppendLine("(global::Disruptor.Surface.Runtime.HydrationJson.ReadRecordId(__idElem).Value);");

        builder
            .Append(indent)
            .AppendLine("    sink.Track(this);");

        foreach (var p in table.Properties)
        {
            if (p.Kinds.HasFlag(PropertyKind.Property))
            {
                if (p.Type.MetadataName == SurrealArrayMetadata)
                {
                    EmitHydrateSurrealArray(builder, indent, p);
                }
                else
                {
                    EmitHydrateValueProperty(builder, indent, p);
                }
            }
            else if (p.Kinds.HasFlag(PropertyKind.Reference))
            {
                EmitHydrateReference(builder, indent, p);
            }
            else if (p.Kinds.HasFlag(PropertyKind.Parent))
            {
                EmitHydrateParent(builder, indent, p);
            }
            // [Children] is computed via parentByChild reverse lookup — nothing to read here.
            // Forward/inverse relation properties are populated by the per-aggregate loader's
            // edge query, not by per-row Hydrate.
        }

        builder
            .Append(indent)
            .AppendLine("}");
    }

    /// <summary>
    /// Hydrates any non-<c>SurrealArray</c> [Property] — scalar (int, bool, DateTime, …),
    /// array (<c>int[]</c>, <c>List&lt;T&gt;</c>), record, dictionary, anything
    /// <see cref="System.Text.Json.JsonSerializer"/> understands. String stays special-cased
    /// so its empty-string fallback matches the schema's <c>DEFAULT ""</c> clause without
    /// a round-trip through the serializer.
    /// </summary>
    private static void EmitHydrateValueProperty(StringBuilder builder, string indent, PropertyModel p)
    {
        var backing = $"_{ToCamel(p.Name)}";
        var fieldLit = Quote(SurrealNaming.ToFieldName(p.Name));
        var typeFqn = p.Type.FullyQualifiedName;

        if (typeFqn is "string" or "global::System.String" or "string?" or "global::System.String?")
        {
            builder
                .Append(indent)
                .Append("    ")
                .Append(backing)
                .Append(" = global::Disruptor.Surface.Runtime.HydrationJson.ReadString(json, ")
                .Append(fieldLit)
                .AppendLine(");");
            return;
        }

        // ReadOrDefault<T> returns the (possibly default!) T directly — assign without
        // coalescing. Works for value types (returns default(T) when missing) and
        // reference types (returns null! → matches the existing `_field = default!`
        // initialisation).
        var deserialiseAs = StripNullable(typeFqn);
        builder
            .Append(indent)
            .Append("    ")
            .Append(backing)
            .Append(" = global::Disruptor.Surface.Runtime.HydrationJson.ReadOrDefault<")
            .Append(deserialiseAs)
            .Append(">(json, ")
            .Append(fieldLit)
            .AppendLine(");");
    }

    /// <summary>
    /// Hydrates a <c>SurrealArray&lt;T&gt;</c>-typed property: reads the JSON array, deserialises
    /// each element into <c>T</c> via <see>
    ///     <cref>System.Text.Json.JsonSerializer</cref>
    /// </see>
    /// using
    /// <c>SurrealJson.SerializerOptions</c> (so the schema's snake_case field names match
    /// the C# record properties), and pre-populates the backing field with a tracked list
    /// initialised from the loaded items. Skips silently when the field is missing or the
    /// value isn't an array — first read will then return an empty wrapper.
    /// </summary>
    private static void EmitHydrateSurrealArray(StringBuilder builder, string indent, PropertyModel p)
    {
        var backing = $"_{ToCamel(p.Name)}";
        var fieldLit = Quote(SurrealNaming.ToFieldName(p.Name));
        var declaredType = p.Type.FullyQualifiedName;
        if (p.Type.TypeArguments.Count == 0)
        {
            // Should be unreachable — `partial SurrealArray Foo { get; }` without a type
            // argument doesn't compile. Escalate at runtime if it ever fires so we hear
            // about it rather than silently leaving the wrapper null.
            builder
                .Append(indent)
                .Append("    throw new global::System.NotSupportedException(\"Hydrate: SurrealArray element type for property '")
                .Append(p.Name)
                .AppendLine("' could not be resolved at codegen time.\");");
            return;
        }

        var elementType = p.Type.TypeArguments[0].FullyQualifiedName;

        var localItems = $"__{ToCamel(p.Name)}Items";
        var localElem = $"__{ToCamel(p.Name)}Elem";

        builder.Append(indent)
            .Append("    if (json.TryGetProperty(")
            .Append(fieldLit)
            .Append(", out var ")
            .Append(localElem)
            .Append(") && ")
            .Append(localElem)
            .AppendLine(".ValueKind == global::System.Text.Json.JsonValueKind.Array)")
            .Append(indent)
            .AppendLine("    {")
            .Append(indent)
            .Append("        var ")
            .Append(localItems)
            .Append(" = new global::System.Collections.Generic.List<")
            .Append(elementType)
            .Append(">(")
            .Append(localElem)
            .AppendLine(".GetArrayLength());")
            .Append(indent)
            .Append("        foreach (var __row in ")
            .Append(localElem)
            .AppendLine(".EnumerateArray())")
            .Append(indent)
            .AppendLine("        {")
            .Append(indent)
            .Append("            var __decoded = global::System.Text.Json.JsonSerializer.Deserialize<")
            .Append(elementType)
            .AppendLine(">(__row, global::Disruptor.Surface.Runtime.SurrealJson.SerializerOptions);")
            .Append(indent)
            .Append("            if (__decoded is not null) ")
            .Append(localItems)
            .AppendLine(".Add(__decoded);")
            .Append(indent)
            .AppendLine("        }")
            .Append(indent)
            .Append("        ")
            .Append(backing)
            .Append(" = new ")
            .Append(declaredType)
            .Append('(')
            .Append(localItems)
            .Append(", __items => __WriteField(")
            .Append(fieldLit)
            .AppendLine(", __items));")
            .Append(indent)
            .AppendLine("    }");
    }

    private static void EmitHydrateReference(StringBuilder builder, string indent, PropertyModel p)
    {
        var fieldLit = Quote(SurrealNaming.ToFieldName(p.Name));
        var typeArg = StripNullable(p.Type.FullyQualifiedName);
        // HydrationJson.HydrateReference<T> handles both the id-only and inline-record
        // shapes — for the inline form (`field.*` projection) it constructs and hydrates
        // the referenced entity from the same payload so reads can resolve it.
        builder
            .Append(indent)
            .Append("    global::Disruptor.Surface.Runtime.HydrationJson.HydrateReference<")
            .Append(typeArg)
            .Append(">(json, ")
            .Append(fieldLit)
            .AppendLine($", (({EntityInterface})this).Id, sink);");
    }

    private static void EmitHydrateParent(StringBuilder builder, string indent, PropertyModel p)
    {
        var fieldLit = Quote(SurrealNaming.ToFieldName(p.Name));
        builder
            .Append(indent)
            .Append("    if (global::Disruptor.Surface.Runtime.HydrationJson.TryReadRecordId(json, ")
            .Append(fieldLit)
            .Append(", out var __parent_")
            .Append(ToCamel(p.Name))
            .AppendLine("))")
            .Append(indent)
            .Append($"        sink.Parent((({EntityInterface})this).Id, __parent_")
            .Append(ToCamel(p.Name))
            .AppendLine(");");
    }

    // ──────────────────────────── helpers ────────────────────────────────────

    private static string Quote(string s) => $"\"{s.Replace("\"", "\\\"")}\"";

    private static string StripNullable(string typeName)
        => typeName.EndsWith("?") ? typeName[..^1] : typeName;

    private static string FormatAccessibility(string raw) => raw switch
    {
        "Public" => "public",
        "Internal" => "internal",
        "Private" => "private",
        "Protected" => "protected",
        "ProtectedOrInternal" => "protected internal",
        "ProtectedAndInternal" => "private protected",
        "NotApplicable" => string.Empty,
        _ => raw.ToLowerInvariant(),
    };
}
