using System.Text;
using Disruptor.Surface.Generator.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Disruptor.Surface.Generator.Emit;

/// <summary>
/// Emits a per-<c>[Table]</c> <c>{Name}Q</c> static class carrying one
/// <c>PropertyExpr&lt;T&gt;</c> field per <c>[Property]</c>/<c>[Id]</c>. The factory is the
/// type-safe entry point for predicate composition:
/// <code>
/// var p = ConstraintQ.Description.Eq("security");
/// var q = workspace.Query.Constraints.Where(p);
/// </code>
/// <para>
/// Only scalar columns get accessors today — <c>[Reference]</c> / <c>[Parent]</c> /
/// <c>[Children]</c> / relation properties are skipped because the runtime predicate
/// vocabulary doesn't yet know how to express graph-walking constraints. They'll come back
/// when traversal-aware predicates land.
/// </para>
/// <para>
/// The accessor for <c>[Id]</c> is emitted as <c>PropertyExpr&lt;{Name}Id&gt;</c> so users
/// pass strongly-typed ids; <see cref="QueryCompiler"/> normalises to canonical
/// <c>RecordId</c> at parameter-binding time.
/// </para>
/// </summary>
internal static class PredicateFactoryEmitter
{
    private const string SurrealArrayMetadata = "Disruptor.Surface.Runtime.SurrealArray`1";
    private const string PropertyExprFqn = "global::Disruptor.Surface.Runtime.Query.PropertyExpr";

    public static void Emit(SourceProductionContext spc, TableModel table)
    {
        var members = CollectMembers(table);
        if (members.Count == 0)
        {
            // No scalar columns — nothing to emit (the {Name}Q class would be empty).
            return;
        }

        var qTypeName = $"{table.Name}Q";

        var sb = new StringBuilder()
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(table.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(table.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        var indent = hasNamespace ? "    " : string.Empty;
        var memberIndent = $"{indent}    ";

        sb.Append(indent)
          .AppendLine($"/// <summary>Predicate factory for <see cref=\"{table.Name}\"/>. One <c>PropertyExpr&lt;T&gt;</c> per scalar column; compose via <c>.Eq(...)</c> and the <c>Predicate</c> static helpers.</summary>");
        sb.Append(indent).Append("public static class ").AppendLine(qTypeName);
        sb.Append(indent).AppendLine("{");

        for (var i = 0; i < members.Count; i++)
        {
            var (propertyName, surrealField, csharpType) = members[i];
            sb.Append(memberIndent)
              .Append("public static readonly ")
              .Append(PropertyExprFqn).Append('<').Append(csharpType).Append("> ")
              .Append(propertyName)
              .Append(" = new(\"").Append(surrealField).AppendLine("\");");
        }

        sb.Append(indent).AppendLine("}");

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        var hint = string.IsNullOrEmpty(table.Namespace)
            ? $"{qTypeName}.g.cs"
            : $"{table.Namespace}.{qTypeName}.g.cs";
        spc.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    /// Returns the (property name, snake-cased SurrealDB field, fully-qualified C# type)
    /// for every property that should appear on the <c>{Name}Q</c> factory. <c>[Id]</c> is
    /// rendered against the SurrealDB built-in <c>id</c> field with the typed
    /// <c>{Name}Id</c> as its C# operand type. Other supported kinds are scalar
    /// <c>[Property]</c>; <c>SurrealArray&lt;T&gt;</c> / <c>[Reference]</c> / <c>[Parent]</c>
    /// / <c>[Children]</c> / relation properties are skipped.
    /// </summary>
    private static List<(string PropertyName, string SurrealField, string CSharpType)> CollectMembers(TableModel table)
    {
        var result = new List<(string, string, string)>();
        var idFqn = string.IsNullOrEmpty(table.Namespace)
            ? $"global::{table.Name}Id"
            : $"global::{table.Namespace}.{table.Name}Id";

        foreach (var p in table.Properties)
        {
            if (p.RelationRole != RelationRole.None) continue;

            if (p.Kinds.HasFlag(PropertyKind.Id))
            {
                result.Add((p.Name, "id", idFqn));
                continue;
            }

            if (!p.Kinds.HasFlag(PropertyKind.Property)) continue;

            // SurrealArray<T> stores as array<object> — equality predicates against the
            // whole array don't have a sensible SurrealQL shape yet. Skip until we have a
            // collection-aware predicate (Contains-element, Length, …).
            if (p.Type.MetadataName == SurrealArrayMetadata) continue;

            result.Add((p.Name, SurrealNaming.ToFieldName(p.Name), p.Type.FullyQualifiedName));
        }

        return result;
    }
}
