using System.Text;
using Disruptor.Surface.Generator.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Disruptor.Surface.Generator.Emit;

/// <summary>
/// Emits the SurrealDB DDL covering every <c>[Table]</c> in the consuming assembly as an
/// ordered list of chunks. Each chunk is a self-contained statement (or small group of
/// related statements) suitable for one transport call. Iterate
/// <c>GeneratedSchema.Script</c> at boot:
/// <code>
/// foreach (var chunk in GeneratedSchema.Script)
///     await transport.ExecuteAsync(chunk);
/// </code>
/// All chunks are idempotent (<c>DEFINE … IF NOT EXISTS</c>); reapplications are safe.
/// <para>
/// Chunk layout (in order): runtime <c>writer_lease</c> table → entity-tables block →
/// per-<c>[Table]</c> field block → per-relation-kind table definition. Splitting the
/// script lets callers run pieces in separate transactions, filter / log / introspect
/// individual chunks, or apply only the bits they need for a migration.
/// </para>
/// <para>
/// Mapping (when adding a new shape, mirror it here too):
/// <list type="bullet">
///   <item>Entity table → <c>DEFINE TABLE {pluralised} SCHEMAFULL</c>.</item>
///   <item>Scalar <c>[Property]</c> → <c>TYPE string|int|bool|float|decimal|datetime</c>;
///         non-nullable types get a <c>DEFAULT</c>, nullable types wrap in <c>option&lt;T&gt;</c>.</item>
///   <item><c>[Property] SurrealArray&lt;T&gt;</c> → <c>TYPE array&lt;object&gt; DEFAULT []</c>.</item>
///   <item><c>[Reference]</c> → <c>TYPE record&lt;target&gt;</c> (or <c>option&lt;record&lt;…&gt;&gt;</c> when nullable),
///         plus <c>REFERENCE ON DELETE {behavior}</c> matching the <c>[Reject]</c>/<c>[Unset]</c>/
///         <c>[Cascade]</c>/<c>[Ignore]</c> attribute.</item>
///   <item><c>[Parent]</c> → <c>TYPE option&lt;record&lt;parent&gt;&gt; REFERENCE ON DELETE REJECT</c>.</item>
///   <item><c>[Children]</c> → <c>COMPUTED &lt;~(child_table FIELD parent_field)</c>.</item>
///   <item>Forward relation kind → <c>DEFINE TABLE {edge} TYPE RELATION FROM source TO target ENFORCED</c>.</item>
/// </list>
/// </para>
/// </summary>
internal static class SchemaEmitter
{
    private const string SurrealArrayMetadata = "Disruptor.Surface.Runtime.SurrealArray`1";

    public static void Emit(SourceProductionContext spc, ModelGraph graph)
    {
        if (graph.Tables.Count == 0)
        {
            return;
        }
        if (graph.CompositionRoots.Count != 1) return;
        var root = graph.CompositionRoots[0];
        if (!root.IsPartial) return;

        var chunks = BuildChunks(graph);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(root.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(root.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        var indent = hasNamespace ? "    " : string.Empty;
        var memberIndent = $"{indent}    ";

        // Partial fragment of the [CompositionRoot]: the public Schema accessor + the
        // convenience ApplySchemaAsync that just iterates and dispatches to transport.
        sb.Append(indent).Append(FormatAccessibility(root.DeclaredAccessibility))
          .Append(" partial class ").AppendLine(root.Name);
        sb.Append(indent).AppendLine("{");
        sb.Append(memberIndent).AppendLine("/// <summary>Ordered, idempotent SurrealDB DDL chunks. Use <see cref=\"ApplySchemaAsync\"/> for the common path, or iterate this directly when you need to filter chunks, run them in custom transactions, or log per-chunk progress.</summary>");
        sb.Append(memberIndent).AppendLine("public static System.Collections.Generic.IReadOnlyList<string> Schema => DisruptorSurfaceSchema._chunks;");
        sb.AppendLine();
        sb.Append(memberIndent).AppendLine("/// <summary>Applies every chunk of <see cref=\"Schema\"/> to <paramref name=\"transport\"/> in order. Idempotent — every <c>DEFINE</c> uses <c>IF NOT EXISTS</c>, so re-running this at boot is safe.</summary>");
        sb.Append(memberIndent).AppendLine("public static async global::System.Threading.Tasks.Task ApplySchemaAsync(global::Disruptor.Surface.Runtime.ISurrealTransport transport, global::System.Threading.CancellationToken ct = default)");
        sb.Append(memberIndent).AppendLine("{");
        sb.Append(memberIndent).AppendLine("    foreach (var chunk in Schema)");
        sb.Append(memberIndent).AppendLine("    {");
        sb.Append(memberIndent).AppendLine("        await transport.ExecuteAsync(chunk, null, ct);");
        sb.Append(memberIndent).AppendLine("    }");
        sb.Append(memberIndent).AppendLine("}");
        sb.Append(indent).AppendLine("}");
        sb.AppendLine();

        // Internal companion class holds the actual chunk array — keeps the user's
        // partial surface uncluttered while still living in the same namespace so the
        // accessor can reach it without a global:: qualifier.
        sb.Append(indent).AppendLine("internal static class DisruptorSurfaceSchema");
        sb.Append(indent).AppendLine("{");
        sb.Append(memberIndent).AppendLine("internal static readonly string[] _chunks = new[]");
        sb.Append(memberIndent).AppendLine("{");
        sb.Append(memberIndent).AppendLine("    global::Disruptor.Surface.Runtime.WriterLease.SchemaScript,");
        foreach (var chunk in chunks)
        {
            // Raw string literal — content and closing """ both flush-left so the
            // compiler's prefix-stripping leaves the chunk text byte-for-byte intact.
            sb.Append(memberIndent).AppendLine("    \"\"\"");
            sb.Append(chunk);
            if (!chunk.EndsWith("\n"))
            {
                sb.AppendLine();
            }
            sb.AppendLine("\"\"\",");
        }
        sb.Append(memberIndent).AppendLine("};");
        sb.Append(indent).AppendLine("}");

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        spc.AddSource($"{root.FullName}.Schema.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string FormatAccessibility(string raw) => raw switch
    {
        "Public" => "public",
        "Internal" => "internal",
        "Private" => "private",
        "Protected" => "protected",
        "ProtectedOrInternal" => "protected internal",
        "ProtectedAndInternal" => "private protected",
        "NotApplicable" => string.Empty,
        _ => raw.ToLowerInvariant(),
    };

    /// <summary>
    /// Build the per-chunk DDL strings. Order is fixed: entity-tables block first (so
    /// fields can reference them), then one chunk per <c>[Table]</c> for its fields,
    /// then one chunk per forward-relation kind for the edge table.
    /// </summary>
    private static List<string> BuildChunks(ModelGraph graph)
    {
        var chunks = new List<string>();
        var orderedTables = graph.Tables.OrderBy(t => t.Name, StringComparer.Ordinal).ToList();

        // Chunk: entity table declarations.
        var entityTablesSb = new StringBuilder();
        foreach (var t in orderedTables)
        {
            entityTablesSb.Append("DEFINE TABLE IF NOT EXISTS ")
                          .Append(SurrealNaming.ToTableName(t.Name))
                          .AppendLine(" SCHEMAFULL;");
        }
        chunks.Add(entityTablesSb.ToString());

        // Chunks: per-entity field blocks.
        foreach (var t in orderedTables)
        {
            var fieldsSb = new StringBuilder();
            EmitTableFields(fieldsSb, t, graph);
            var content = fieldsSb.ToString();
            if (!string.IsNullOrWhiteSpace(content))
            {
                chunks.Add(content);
            }
        }

        // Chunks: per-relation-kind table definitions.
        var fwdKinds = graph.RelationKinds
            .Where(k => k.Direction == RelationDirection.Forward)
            .OrderBy(k => k.Name, StringComparer.Ordinal);
        foreach (var fwdKind in fwdKinds)
        {
            var relSb = new StringBuilder();
            EmitRelationTable(relSb, fwdKind, graph);
            var content = relSb.ToString();
            if (!string.IsNullOrWhiteSpace(content))
            {
                chunks.Add(content);
            }
        }

        return chunks;
    }

    private static void EmitTableFields(StringBuilder sb, TableModel table, ModelGraph graph)
    {
        var tableName = SurrealNaming.ToTableName(table.Name);
        var any = false;

        foreach (var p in table.Properties)
        {
            // [Id] is implicit on every Surreal record. Relation properties (forward/
            // inverse collections) are edge-table reads, not entity columns.
            if (p.Kinds.HasFlag(PropertyKind.Id)) continue;
            if (p.RelationRole != MethodRole.None) continue;

            if (!any)
            {
                sb.Append("// ").AppendLine(tableName);
                any = true;
            }

            var fieldName = SurrealNaming.ToFieldName(p.Name);

            if (p.Kinds.HasFlag(PropertyKind.Reference))
            {
                EmitReferenceField(sb, tableName, fieldName, p);
            }
            else if (p.Kinds.HasFlag(PropertyKind.Parent))
            {
                EmitParentField(sb, tableName, fieldName, p);
            }
            else if (p.Kinds.HasFlag(PropertyKind.Children))
            {
                EmitChildrenField(sb, tableName, fieldName, table, p, graph);
            }
            else if (p.Kinds.HasFlag(PropertyKind.Property))
            {
                EmitPropertyField(sb, tableName, fieldName, p);
            }
        }
    }

    private static void EmitReferenceField(StringBuilder sb, string tableName, string fieldName, PropertyModel p)
    {
        var targetTable = SurrealNaming.ToTableName(SurrealNaming.SimpleName(p.Type.FullyQualifiedName));
        var typePart = p.Type.IsNullable
            ? $"option<record<{targetTable}>>"
            : $"record<{targetTable}>";
        var deletePart = ReferenceDeleteClause(p.ReferenceDelete);
        sb.Append("DEFINE FIELD IF NOT EXISTS ").Append(fieldName)
          .Append(" ON ").Append(tableName)
          .Append(" TYPE ").Append(typePart)
          .Append(' ').Append(deletePart).AppendLine(";");
    }

    private static void EmitParentField(StringBuilder sb, string tableName, string fieldName, PropertyModel p)
    {
        // Parent links are always option<record<...>> in Surreal — the field needs to
        // be nullable at the schema level so a child can be inserted before its parent
        // ref is set, even though the C# surface treats it as non-nullable in the
        // steady state. Delete behaviour is REJECT: you can't drop a parent that still
        // has children pointing at it.
        var parentTable = SurrealNaming.ToTableName(SurrealNaming.SimpleName(p.Type.FullyQualifiedName));
        sb.Append("DEFINE FIELD IF NOT EXISTS ").Append(fieldName)
          .Append(" ON ").Append(tableName)
          .Append(" TYPE option<record<").Append(parentTable).Append(">>")
          .AppendLine(" REFERENCE ON DELETE REJECT;");
    }

    private static void EmitChildrenField(StringBuilder sb, string tableName, string fieldName, TableModel parent, PropertyModel p, ModelGraph graph)
    {
        // Computed reverse-fk: <~(child_table FIELD parent_field). Find the [Parent] on
        // the child element type that points back at this parent table.
        var elementType = p.Type.ElementType ?? p.Type;
        var childTypeName = SurrealNaming.SimpleName(elementType.FullyQualifiedName);
        var childTable = graph.Tables.FirstOrDefault(t => t.Name == childTypeName);
        if (childTable is null)
        {
            sb.Append("// SCHEMA: child element type '").Append(childTypeName).Append("' for ")
              .Append(tableName).Append('.').Append(fieldName).AppendLine(" not a [Table]; field omitted.");
            return;
        }

        var parentField = FindParentFieldName(parent, childTable);
        if (parentField is null)
        {
            sb.Append("// SCHEMA: no [Parent] on '").Append(childTable.Name).Append("' pointing at '")
              .Append(parent.Name).Append("' for ").Append(tableName).Append('.').Append(fieldName)
              .AppendLine("; field omitted.");
            return;
        }

        sb.Append("DEFINE FIELD IF NOT EXISTS ").Append(fieldName)
          .Append(" ON ").Append(tableName)
          .Append(" COMPUTED <~(").Append(SurrealNaming.ToTableName(childTable.Name))
          .Append(" FIELD ").Append(parentField).AppendLine(");");
    }

    private static void EmitPropertyField(StringBuilder sb, string tableName, string fieldName, PropertyModel p)
    {
        // Inline collection backed by SurrealArray<T> — array<object> at the field, plus
        // {field}.*.{member} sub-field DDL for each public instance property of T.
        // InlineMembers is populated by TableExtractor.ResolveInlineMembers.
        if (p.Type.MetadataName == SurrealArrayMetadata)
        {
            sb.Append("DEFINE FIELD IF NOT EXISTS ").Append(fieldName)
              .Append(" ON ").Append(tableName).AppendLine(" TYPE array<object> DEFAULT [];");

            foreach (var im in p.InlineMembers)
            {
                var memberFieldName = SurrealNaming.ToFieldName(im.Name);
                var (memberType, memberDefault) = MapScalarType(im.Type);
                if (memberType is null)
                {
                    sb.Append("// SCHEMA: inline member type '").Append(im.Type.FullyQualifiedName)
                      .Append("' on ").Append(tableName).Append('.').Append(fieldName)
                      .Append(".*.").Append(memberFieldName).AppendLine(" not mapped; sub-field omitted.");
                    continue;
                }

                sb.Append("DEFINE FIELD IF NOT EXISTS ").Append(fieldName).Append(".*.").Append(memberFieldName)
                  .Append(" ON ").Append(tableName)
                  .Append(" TYPE ").Append(memberType);
                if (memberDefault is not null)
                {
                    sb.Append(" DEFAULT ").Append(memberDefault);
                }
                sb.AppendLine(";");
            }
            return;
        }

        var (surrealType, defaultExpr) = MapScalarType(p.Type);
        if (surrealType is null)
        {
            sb.Append("// SCHEMA: scalar type '").Append(p.Type.FullyQualifiedName)
              .Append("' on ").Append(tableName).Append('.').Append(fieldName)
              .AppendLine(" not mapped; field omitted.");
            return;
        }

        sb.Append("DEFINE FIELD IF NOT EXISTS ").Append(fieldName)
          .Append(" ON ").Append(tableName)
          .Append(" TYPE ").Append(surrealType);
        if (defaultExpr is not null)
        {
            sb.Append(" DEFAULT ").Append(defaultExpr);
        }
        sb.AppendLine(";");
    }

    private static (string? Type, string? Default) MapScalarType(TypeRef type)
    {
        var fqn = StripGlobal(type.FullyQualifiedName);
        if (fqn.EndsWith("?")) fqn = fqn[..^1];

        var (raw, def) = fqn switch
        {
            "string" or "System.String"               => ("string",   "\"\""),
            "int" or "System.Int32"                   => ("int",      "0"),
            "long" or "System.Int64"                  => ("int",      "0"),
            "bool" or "System.Boolean"                => ("bool",     "false"),
            "double" or "System.Double"               => ("float",    "0"),
            "float" or "System.Single"                => ("float",    "0"),
            "decimal" or "System.Decimal"             => ("decimal",  "0"),
            "System.DateTime" or "System.DateTimeOffset" => ("datetime", null),
            "System.Guid" or "System.Ulid"            => ("string",   null),
            _ => (null, null),
        };

        if (raw is null)
        {
            return (null, null);
        }
        if (type.IsNullable)
        {
            return ($"option<{raw}>", null);
        }
        return (raw, def);
    }

    private static string ReferenceDeleteClause(ReferenceDeletePolicy policy) => policy switch
    {
        ReferenceDeletePolicy.Reject  => "REFERENCE ON DELETE REJECT",
        ReferenceDeletePolicy.Unset   => "REFERENCE ON DELETE UNSET",
        ReferenceDeletePolicy.Cascade => "REFERENCE ON DELETE CASCADE",
        ReferenceDeletePolicy.Ignore  => "REFERENCE ON DELETE IGNORE",
        _ => "REFERENCE ON DELETE REJECT",
    };

    private static string? FindParentFieldName(TableModel parent, TableModel child)
    {
        foreach (var cp in child.Properties)
        {
            if (!cp.Kinds.HasFlag(PropertyKind.Parent)) continue;
            var parentTypeName = SurrealNaming.SimpleName(cp.Type.FullyQualifiedName);
            if (parentTypeName == parent.Name)
            {
                return SurrealNaming.ToFieldName(cp.Name);
            }
        }
        return null;
    }

    private static void EmitRelationTable(StringBuilder sb, RelationKindModel fwdKind, ModelGraph graph)
    {
        var edgeName = SurrealNaming.ToEdgeName(fwdKind.Name);
        var sourceTables = FindSourceTables(graph, fwdKind.FullName)
            .Select(t => SurrealNaming.ToTableName(t.Name))
            .ToList();
        var targetTables = FindTargetTables(graph, fwdKind.FullName)
            .Select(t => SurrealNaming.ToTableName(t.Name))
            .ToList();

        if (sourceTables.Count == 0 || targetTables.Count == 0)
        {
            sb.Append("// SCHEMA: relation '").Append(edgeName)
              .AppendLine("' missing source or target tables; relation table omitted.");
            return;
        }

        sb.Append("DEFINE TABLE IF NOT EXISTS ").Append(edgeName).AppendLine(" SCHEMAFULL")
          .AppendLine("TYPE RELATION")
          .Append("FROM ").AppendLine(string.Join("|", sourceTables))
          .Append("TO ").AppendLine(string.Join("|", targetTables))
          .AppendLine("ENFORCED;");
    }

    private static List<TableModel> FindSourceTables(ModelGraph graph, string fwdKindFullName)
    {
        var result = new List<TableModel>();
        foreach (var t in graph.Tables)
        {
            foreach (var p in t.Properties)
            {
                if (p.RelationRole == MethodRole.ForwardRelation && p.RelationKindFullName == fwdKindFullName)
                {
                    result.Add(t);
                    break;
                }
            }
        }
        return result;
    }

    private static List<TableModel> FindTargetTables(ModelGraph graph, string fwdKindFullName)
    {
        var inverseKind = graph.RelationKinds.FirstOrDefault(k =>
            k.Direction == RelationDirection.Inverse && k.PairedForwardFullName == fwdKindFullName);
        if (inverseKind is null) return [];

        var result = new List<TableModel>();
        foreach (var t in graph.Tables)
        {
            foreach (var p in t.Properties)
            {
                if (p.RelationRole == MethodRole.InverseRelation && p.RelationKindFullName == inverseKind.FullName)
                {
                    result.Add(t);
                    break;
                }
            }
        }
        return result;
    }

    private static string StripGlobal(string fqn) =>
        fqn.StartsWith("global::") ? fqn[8..] : fqn;
}
