using System.Text;
using Disruptor.Surface.Generator.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Disruptor.Surface.Generator.Emit;

/// <summary>
/// Emits a per-<c>[Table]</c> <c>{Name}TraversalBuilder</c> class — the typed sub-builder
/// passed to <c>Include*</c> methods on <c>Query&lt;T&gt;</c>. Each builder carries:
/// <list type="bullet">
///   <item><c>Where(IPredicate)</c> — accumulates filter (AND-merge across calls).</item>
///   <item>One <c>Include{Name}()</c> per <c>[Reference, Inline]</c> — adds an inline-ref
///         expansion to the projection.</item>
///   <item>One <c>Include{Name}(Action&lt;{Child}TraversalBuilder&gt;? configure = null)</c>
///         per <c>[Children]</c> — recursively descends with its own builder.</item>
///   <item><c>Build()</c> (internal) — snapshots accumulated state into <c>(IPredicate? Filter, IReadOnlyList&lt;IIncludeNode&gt; Nested)</c>.</item>
/// </list>
/// <para>
/// Forward-relation traversals are out of scope for v1 — they'd need a different SurrealQL
/// shape (subselect over the edge table joined back to the target). They'll come in a
/// later PR alongside <see cref="EdgeQuery{TIn,TOut}"/>'s richer projections.
/// </para>
/// </summary>
internal static class TraversalBuilderEmitter
{
    private const string IncludeNodeFqn = "global::Disruptor.Surface.Runtime.Query.IIncludeNode";
    private const string IncludeChildrenNodeFqn = "global::Disruptor.Surface.Runtime.Query.IncludeChildrenNode";
    private const string IncludeInlineRefNodeFqn = "global::Disruptor.Surface.Runtime.Query.IncludeInlineRefNode";
    private const string PredicateFqn = "global::Disruptor.Surface.Runtime.Query.IPredicate";
    private const string PredicateHelperFqn = "global::Disruptor.Surface.Runtime.Query.Predicate";

    public static void Emit(SourceProductionContext spc, TableModel table, ModelGraph graph)
    {
        var inlineRefs = CollectInlineRefs(table);
        var children = CollectChildren(table, graph);

        // Always emit the builder type — even with zero traversable members, the user can
        // still call .Where(...) on it. Keeps the codegen surface uniform across tables.
        var typeName = $"{table.Name}TraversalBuilder";

        var sb = new StringBuilder()
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(table.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(table.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        var indent = hasNamespace ? "    " : string.Empty;
        var memberIndent = $"{indent}    ";
        var bodyIndent = $"{memberIndent}    ";

        sb.Append(indent)
          .AppendLine($"/// <summary>Traversal builder for <see cref=\"{table.Name}\"/>. Emitted by <c>TraversalBuilderEmitter</c>; passed as the configure-action argument to <c>Query&lt;{table.Name}&gt;.Include*</c> extensions.</summary>");
        sb.Append(indent).Append("public sealed class ").AppendLine(typeName);
        sb.Append(indent).AppendLine("{");

        // Mutable accumulators. Builders are throw-away (per-Include invocation) so a
        // tiny per-instance List<> is fine; no concern about cross-call aliasing.
        sb.Append(memberIndent).Append("private ").Append(PredicateFqn).AppendLine("? _filter;");
        sb.Append(memberIndent).Append("private readonly System.Collections.Generic.List<")
          .Append(IncludeNodeFqn).AppendLine("> _nested = new();");
        sb.AppendLine();

        // Where(predicate) — AND-merges into _filter, returns this for fluent chaining.
        sb.Append(memberIndent)
          .Append("public ").Append(typeName).Append(" Where(").Append(PredicateFqn).AppendLine(" predicate)");
        sb.Append(memberIndent).AppendLine("{");
        sb.Append(bodyIndent).Append("_filter = _filter is null ? predicate : ").Append(PredicateHelperFqn).AppendLine(".And(_filter, predicate);");
        sb.Append(bodyIndent).AppendLine("return this;");
        sb.Append(memberIndent).AppendLine("}");

        foreach (var inline in inlineRefs)
        {
            EmitInlineRefInclude(sb, memberIndent, bodyIndent, typeName, inline);
        }

        foreach (var child in children)
        {
            EmitChildrenInclude(sb, memberIndent, bodyIndent, typeName, child);
        }

        // Build() — snapshot accumulator state for the AST. Called by the per-table
        // Include extension on Query<T>.
        sb.AppendLine();
        sb.Append(memberIndent)
          .AppendLine("/// <summary>Snapshot the accumulated state. Called by the per-table <c>Include</c> extension on <c>Query&lt;T&gt;</c>.</summary>");
        sb.Append(memberIndent)
          .Append("internal (").Append(PredicateFqn).Append("? Filter, System.Collections.Generic.IReadOnlyList<")
          .Append(IncludeNodeFqn).AppendLine("> Nested) Build()");
        sb.Append(memberIndent).AppendLine("    => (_filter, _nested.ToArray());");

        sb.Append(indent).AppendLine("}");

        // Sibling class: extension methods on Query<{Table}> with the same Include
        // surface as the traversal builder above. Lets the user pivot from
        // "Workspace.Query.Designs.IncludeConstraints(...)" at the root to the
        // identically-named "...IncludeConstraints(c => c.IncludeDetails())" inside a
        // configure lambda — same vocabulary at every level.
        if (inlineRefs.Count > 0 || children.Count > 0)
        {
            EmitQueryExtensions(sb, indent, memberIndent, bodyIndent, table, inlineRefs, children);
        }

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        var hint = string.IsNullOrEmpty(table.Namespace)
            ? $"{typeName}.g.cs"
            : $"{table.Namespace}.{typeName}.g.cs";
        spc.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    /// Emit a static extension class hosting <c>Query&lt;{Table}&gt;.Include*</c> methods.
    /// Mirrors the traversal-builder shape but anchors on the root <see cref="Query{T}"/>
    /// — every <c>Include</c> ends with <c>query.WithInclude(node)</c> rather than
    /// accumulating into a builder field.
    /// </summary>
    private static void EmitQueryExtensions(
        StringBuilder sb,
        string indent,
        string memberIndent,
        string bodyIndent,
        TableModel table,
        IReadOnlyList<InlineRefMember> inlineRefs,
        IReadOnlyList<ChildrenMember> children)
    {
        var entityFqn = string.IsNullOrEmpty(table.Namespace)
            ? $"global::{table.Name}"
            : $"global::{table.Namespace}.{table.Name}";
        var queryFqn = $"global::Disruptor.Surface.Runtime.Query.Query<{entityFqn}>";
        var extName = $"{table.Name}QueryIncludes";

        sb.AppendLine();
        sb.Append(indent)
          .AppendLine($"/// <summary>Root-level <c>Include*</c> extensions on <c>Query&lt;{table.Name}&gt;</c>. Mirror the per-level methods on <see cref=\"{table.Name}TraversalBuilder\"/>.</summary>");
        sb.Append(indent).Append("public static class ").AppendLine(extName);
        sb.Append(indent).AppendLine("{");

        var first = true;
        foreach (var inline in inlineRefs)
        {
            if (!first) sb.AppendLine();
            first = false;
            sb.Append(memberIndent)
              .AppendLine($"/// <summary>Pulls the inline <c>[Reference, Inline]</c> record at <c>{inline.Field}</c> into the projection (<c>{inline.Field}.*</c>).</summary>");
            sb.Append(memberIndent)
              .Append("public static ").Append(queryFqn).Append(" Include").Append(inline.PropertyName)
              .Append("(this ").Append(queryFqn).AppendLine(" query)");
            sb.Append(memberIndent).AppendLine("{");
            sb.Append(bodyIndent).Append("return query.WithInclude(new ").Append(IncludeInlineRefNodeFqn)
              .Append("(\"").Append(inline.Field).AppendLine("\"));");
            sb.Append(memberIndent).AppendLine("}");
        }

        foreach (var child in children)
        {
            if (!first) sb.AppendLine();
            first = false;

            var childBuilderFqn = string.IsNullOrEmpty(child.ChildNamespace)
                ? $"global::{child.ChildTypeName}TraversalBuilder"
                : $"global::{child.ChildNamespace}.{child.ChildTypeName}TraversalBuilder";

            sb.Append(memberIndent)
              .AppendLine($"/// <summary>Pulls children rows from <c>{child.ChildTable}</c> (parent link <c>{child.ParentField}</c>). Pass <paramref name=\"configure\"/> to filter or descend further.</summary>");
            sb.Append(memberIndent)
              .Append("public static ").Append(queryFqn).Append(" Include").Append(child.PropertyName)
              .Append("(this ").Append(queryFqn).Append(" query, global::System.Action<")
              .Append(childBuilderFqn).AppendLine(">? configure = null)");
            sb.Append(memberIndent).AppendLine("{");
            sb.Append(bodyIndent).Append("var __sub = new ").Append(childBuilderFqn).AppendLine("();");
            sb.Append(bodyIndent).AppendLine("configure?.Invoke(__sub);");
            sb.Append(bodyIndent).AppendLine("var (__filter, __nested) = __sub.Build();");
            sb.Append(bodyIndent).Append("return query.WithInclude(new ").Append(IncludeChildrenNodeFqn)
              .Append("(\"").Append(child.ChildTable).Append("\", \"").Append(child.ParentField).Append("\", __filter, __nested, ")
              .Append(child.HydratorExpression).Append(", \"").Append(child.SliceKey).AppendLine("\"));");
            sb.Append(memberIndent).AppendLine("}");
        }

        sb.Append(indent).AppendLine("}");
    }

    private static void EmitInlineRefInclude(StringBuilder sb, string memberIndent, string bodyIndent, string typeName, InlineRefMember inline)
    {
        sb.AppendLine();
        sb.Append(memberIndent)
          .AppendLine($"/// <summary>Pulls the inline <c>[Reference, Inline]</c> record at <c>{inline.Field}</c> into the projection (<c>{inline.Field}.*</c>).</summary>");
        sb.Append(memberIndent)
          .Append("public ").Append(typeName).Append(" Include").Append(inline.PropertyName).AppendLine("()");
        sb.Append(memberIndent).AppendLine("{");
        sb.Append(bodyIndent).Append("_nested.Add(new ").Append(IncludeInlineRefNodeFqn)
          .Append("(\"").Append(inline.Field).AppendLine("\"));");
        sb.Append(bodyIndent).AppendLine("return this;");
        sb.Append(memberIndent).AppendLine("}");
    }

    private static void EmitChildrenInclude(StringBuilder sb, string memberIndent, string bodyIndent, string typeName, ChildrenMember child)
    {
        var childBuilderFqn = string.IsNullOrEmpty(child.ChildNamespace)
            ? $"global::{child.ChildTypeName}TraversalBuilder"
            : $"global::{child.ChildNamespace}.{child.ChildTypeName}TraversalBuilder";

        sb.AppendLine();
        sb.Append(memberIndent)
          .AppendLine($"/// <summary>Pulls children rows from <c>{child.ChildTable}</c> (parent link <c>{child.ParentField}</c>). Pass <paramref name=\"configure\"/> to filter or descend further.</summary>");
        sb.Append(memberIndent)
          .Append("public ").Append(typeName).Append(" Include").Append(child.PropertyName)
          .Append("(global::System.Action<").Append(childBuilderFqn).AppendLine(">? configure = null)");
        sb.Append(memberIndent).AppendLine("{");
        sb.Append(bodyIndent).Append("var __sub = new ").Append(childBuilderFqn).AppendLine("();");
        sb.Append(bodyIndent).AppendLine("configure?.Invoke(__sub);");
        sb.Append(bodyIndent).AppendLine("var (__filter, __nested) = __sub.Build();");
        sb.Append(bodyIndent).Append("_nested.Add(new ").Append(IncludeChildrenNodeFqn)
          .Append("(\"").Append(child.ChildTable).Append("\", \"").Append(child.ParentField).Append("\", __filter, __nested, ")
          .Append(child.HydratorExpression).Append(", \"").Append(child.SliceKey).AppendLine("\"));");
        sb.Append(bodyIndent).AppendLine("return this;");
        sb.Append(memberIndent).AppendLine("}");
    }

    /// <summary>
    /// Inline-ref members for traversal: <c>[Reference, Inline]</c> properties on the
    /// table. The field name is the snake-cased SurrealDB column; the property name is
    /// the C# member that becomes <c>Include{PropertyName}()</c>.
    /// </summary>
    private static List<InlineRefMember> CollectInlineRefs(TableModel table)
    {
        var result = new List<InlineRefMember>();
        foreach (var p in table.Properties)
        {
            if (!p.Kinds.HasFlag(PropertyKind.Reference)) continue;
            if (!p.IsInline) continue;
            result.Add(new InlineRefMember(p.Name, SurrealNaming.ToFieldName(p.Name)));
        }
        return result;
    }

    /// <summary>
    /// Children members for traversal: <c>[Children]</c> properties on the table whose
    /// element type is another <c>[Table]</c>, paired with the matching <c>[Parent]</c>
    /// field on the child that points back at this table. If no matching <c>[Parent]</c>
    /// exists the [Children] entry is skipped (mirrors <see cref="SchemaEmitter.EmitChildrenField"/>'s
    /// "no parent path → field omitted" guard).
    /// </summary>
    private static List<ChildrenMember> CollectChildren(TableModel parent, ModelGraph graph)
    {
        var result = new List<ChildrenMember>();
        foreach (var p in parent.Properties)
        {
            if (!p.Kinds.HasFlag(PropertyKind.Children)) continue;

            var elementType = p.Type.ElementType ?? p.Type;
            var childTypeName = SurrealNaming.SimpleName(elementType.FullyQualifiedName);
            var childTable = graph.Tables.FirstOrDefault(t => t.Name == childTypeName);
            if (childTable is null) continue;

            var parentField = FindParentFieldName(parent, childTable);
            if (parentField is null) continue;

            var childEntityFqn = string.IsNullOrEmpty(childTable.Namespace)
                ? $"global::{childTable.Name}"
                : $"global::{childTable.Namespace}.{childTable.Name}";
            // Static lambda — no captures, gets cached as a delegate field once per
            // include node. The cast threads the entity through IEntity so we hit the
            // explicit-impl Hydrate emitted by PartialEmitter.
            var hydratorExpr =
                $"static (row, sink) => {{ var __e = new {childEntityFqn}(); ((global::Disruptor.Surface.Runtime.IEntity)__e).Hydrate(row, sink); }}";

            result.Add(new ChildrenMember(
                PropertyName: p.Name,
                ChildTable: SurrealNaming.ToTableName(childTable.Name),
                ChildTypeName: childTable.Name,
                ChildNamespace: childTable.Namespace,
                ParentField: parentField,
                HydratorExpression: hydratorExpr,
                SliceKey: SurrealNaming.ToFieldName(p.Name)));
        }
        return result;
    }

    private static string? FindParentFieldName(TableModel parent, TableModel child)
    {
        foreach (var cp in child.Properties)
        {
            if (!cp.Kinds.HasFlag(PropertyKind.Parent)) continue;
            var parentTypeName = SurrealNaming.SimpleName(cp.Type.FullyQualifiedName);
            if (parentTypeName == parent.Name)
            {
                return SurrealNaming.ToFieldName(cp.Name);
            }
        }
        return null;
    }

    private readonly record struct InlineRefMember(string PropertyName, string Field);

    private readonly record struct ChildrenMember(
        string PropertyName,
        string ChildTable,
        string ChildTypeName,
        string ChildNamespace,
        string ParentField,
        string HydratorExpression,
        string SliceKey);
}
